flyteorg/flyte

- README.md
- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- kustomize/overlays/sandbox/admindeployment/admindeployment.yaml
In order to run end2end tests, FltyeAdmin needs to sync the cluster resources before starting.
> sync-cluster-resources before FlyteAdmin starts

- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- kustomize/base/admindeployment/deployment.yaml
Update Flyte Admin to latest version.
> Update to FlyteAdmin v0.1.3

- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- kustomize/base/admindeployment/deployment.yaml
Update Flyteadmin to v0.1.4. 
v0.1.3 did not include all changes incorporated with migrations.
Tested in sandbox deployment to ensure all migrations are run.
> Update Flyteadmin to v0.1.4

- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- kustomize/overlays/sandbox/admindeployment/cron.yaml
All control plane components should use the flyteadmin service account. Currently none was provided which works with local cluster as local cluster has default permissions. This fails on cloud sandbox deployments.
> The Cluster resource syncer should use the flyteadmin service account

- script/kustomize.sh
By accepting an argument, users of this script would be able to specify
which deployment to build.
Internally we have customized overlay which doesn't make sense to
open source, but still we would like to utilize as much as possible from
this repo.
> pass argument to kustomize script

- rsts/administrator/install/getting_started.rst
In Minikube deployment, the Contour NodePort does not become readily available outside the cluster. 
Hence, a statement 
> For local deployments, this endpoint is typically http://localhost:30081/console.
is misleading to Minikube users. 
Adding an extra instruction for Minikube users clarifies how to access the console.
> Add a step for Minikube deployment instructions

- rsts/administrator/install/production.rst
zsh and bash behave differently regarding *(asterisk)
In zsh, when you say "*.bak" it looks in your current working directory for files that end with .bak, so just added single quotation marks
tested in both bash and zsh
thx
> Fix command not working in zsh

- rsts/user/getting_started/create_first.rst
Trivial fix of typo in variable name.
> Fix typo in DOCKER_REGISTRY_USERNAME

- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- kustomize/base/admindeployment/deployment.yaml
- kustomize/base/propeller/deployment.yaml
- kustomize/overlays/sandbox/admindeployment/admindeployment.yaml
- kustomize/overlays/sandbox/admindeployment/cron.yaml
- kustomize/overlays/sandbox/propeller/plugins/qubole/config.yaml
Admin and propeller to use versions that use go mod for dependency management.  There was a bug in Admin that was fixed which is why we've gone one version beyond.
See related issue: https://github.com/lyft/flyte/issues/129
Also,
* Removing a broken key in propeller config that's been removed
> Go mod versions

- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- kustomize/base/adminserviceaccount/adminserviceaccount.yaml
This is needed to dynamically set per-namespace cluster quotas for memory, cpu, etc.
> Add resourcequotas perms for flyteadmin serviceaccount

- deployment/sandbox/flyte_generated.yaml
- kustomize/base/datacatalog/deployment.yaml
v0.1.1 is quite old and this PR upgrades to latest tag according to https://hub.docker.com/r/lyft/datacatalog/tags
> upgrade to latest tag of datacatalog

- .github/workflows/tests.yml
- script/kustomize.sh
This PR configures a step of GitHub Workflow to ensure that in case of modification of kustomize code, `make kustomize` was executed and the newly generated `flyte_generated.yaml` was added as a part of the commit.
This PR is inspired by https://github.com/lyft/flyteidl/blob/master/generate_protos.sh#L58
It is very likely that a new contributor of this repo updated some kustomize file but didn't do `make kustomize`. Having an automated step telling what is missing would be useful.
* https://github.com/lyft/flyte/pull/200/checks?check_run_id=496295498 as a successful workflow execution
* https://github.com/lyft/flyte/pull/200/checks?check_run_id=496307946 as a failed one
> check generated file as part of GitHub Workflow

- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- end2end/tests/endtoend.yaml
- kustomize/base/admindeployment/deployment.yaml
- kustomize/base/propeller/deployment.yaml
- kustomize/overlays/sandbox/admindeployment/admindeployment.yaml
Bump Admin to 0.2.3.  Bump internal flytetester image to flytekit version 0.6.0b1.
Propeller is now already at 0.2.13 so branch name is incorrect.
> Admin to 0.2.3 (propeller 0.2.11)

- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- kustomize/base/admindeployment/deployment.yaml
- kustomize/overlays/sandbox/admindeployment/admindeployment.yaml
- kustomize/overlays/sandbox/admindeployment/cron.yaml
See https://github.com/lyft/flyteadmin/pull/92 and https://github.com/lyft/flyte/issues/198
cc @rstanevich
> Update admin release version to include scheduled workflow executor debug logs

- rsts/introduction/index.rst
- rsts/introduction/roadmap.rst
Updated the docs to have a roadmap section, also created a roadmap Spreadsheet and a ideas document
> Roadmap and ideas

- deployment/sandbox/flyte_generated.yaml
- kustomize/base/operators/spark/deployment.yaml
- kustomize/base/operators/spark/kustomization.yaml
- kustomize/base/operators/spark/spark-operator.yaml
- kustomize/base/operators/spark/webhook.yaml
Ref https://github.com/lyft/flyte/issues/285
> Add support for sparkoperator webhook

- rsts/user/tasktypes/presto.rst
Looks like without this extra newline, the query does not show up properly
> Fix Presto doc

- deployment/sandbox/flyte_generated.yaml
- kustomize/base/admindeployment/service.yaml
- kustomize/overlays/eks/datacatalog/datacatalog.yaml
- kustomize/overlays/eks/datacatalog/service.yaml
- kustomize/overlays/sandbox/dependencies/kustomization.yaml
- kustomize/overlays/sandbox/dependencies/service.yaml
- kustomize/overlays/sandbox/flyte/kustomization.yaml
When developing Flyte, it is necessary often to run both Propeller and Admin from the contributor's laptop (from Goland for instance).  In these cases, contributors currently need to port forward each of Minio and Postgres in order to do so.
This exposes 30083 for the sandbox Postgres instance and 30084 for Minio, thereby making port forwarding no longer necessary.
> Expose sandbox node ports for Minio and Postgres

- .github/workflows/tests.yml
- deployment/eks/flyte_generated.yaml
- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- end2end/tests/endtoend.yaml
- kustomize/base/admindeployment/deployment.yaml
- kustomize/base/propeller/deployment.yaml
- rsts/user/features/index.rst
- rsts/user/features/on_failure_policy.rst
https://github.com/lyft/flyte/issues/191
> OnFailurePolicy docs & endtoend tests

- CHANGELOG/CHANGELOG-v0.5.0.md
- Makefile
- deployment/eks/flyte_generated.yaml
- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- end2end/tests/endtoend.yaml
- kustomize/overlays/eks/admindeployment/admindeployment.yaml
- kustomize/overlays/eks/admindeployment/cron.yaml
- kustomize/overlays/sandbox/admindeployment/admindeployment.yaml
- kustomize/overlays/sandbox/admindeployment/cron.yaml
- rsts/conf.py
Propeller: v0.2.64
Admin: v0.2.11
Flytekit: v0.10.0
Console: v0.5.3
IDL: 0.17.34
> Milestone v0.5.0

- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- kustomize/overlays/sandbox/admindeployment/kustomization.yaml
I've been playing with raw containers and this seemed to be missing piece to run the `flytecopilot` container successfully.
> Add flyte-data-config ConfigMap to sandbox kustomization

- rsts/user/features/index.rst
- rsts/user/features/interruptible.rst
Adding documentation around interruptible feature for users.
> Add documentation around interruptible

- CHANGELOG/CHANGELOG-v0.8.0.md
- Makefile
- README.md
- deployment/eks/flyte_generated.yaml
- deployment/gcp/flyte_generated.yaml
- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- end2end/tests/endtoend.yaml
- kustomize/overlays/eks/kustomization.yaml
- kustomize/overlays/gcp/kustomization.yaml
- kustomize/overlays/sandbox/kustomization.yaml
- kustomize/overlays/test/kustomization.yaml
- rsts/administrator/install/multi_cluster.rst
- rsts/administrator/install/production.rst
- rsts/conf.py
flytekit: v0.13.1
flytepropeller: v0.4.2
flyteidl: v0.18.8
flyteadmin: v0.3.7
flyteplugins: v0.5.1
flyteconsole: v0.12.1
> Flyte milestone Release v0.8.0

- rsts/user/features/single_task_execution.rst
Realized when reviewing this for the katacoda tutorial PR there were a few typos. Annoying!
> Fix single task typos

- end2end/execute.sh
> Increase e2e test timeout

- rsts/user/getting_started/create_first.rst
Minikube uses a separate docker daemon from the normal system docker
daemon, so you need to tell your shell how to access the minikube docker
daemon. Otherwise when the Task runs it fails immediately because it
tries to pull from Dockerhub.
This also removes a redundant "to" in the following sentence.
> Add instructions to make minikube's docker env available during 'make docker_build'

- deployment/eks/flyte_generated.yaml
- deployment/gcp/flyte_generated.yaml
- deployment/sandbox/flyte_generated.yaml
- kustomize/base/operators/spark/scheduledsparkapplications-crd.yaml
- kustomize/base/operators/spark/sparkapplications-crd.yaml
Spark resource definition currently fail on 1.18+ . Ref: https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/1065 
Cherry-picked https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/commit/5b2fe9218108baa6456eb3472196d5eb55b41efd to fix the same
> Update Spark CRDs to support 1.18+

- deployment/eks/flyte_generated.yaml
- deployment/gcp/flyte_generated.yaml
- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- kustomize/base/single_cluster/headless/config/propeller/plugins/copilot.yaml
- kustomize/overlays/eks/kustomization.yaml
- kustomize/overlays/gcp/kustomization.yaml
- kustomize/overlays/sandbox/kustomization.yaml
- kustomize/overlays/test/kustomization.yaml
https://github.com/lyft/flyte/issues/627
> Update flyte to use container registry images instead

- README.md
> Mention Java as out of the box supported language

- deployment/eks/flyte_generated.yaml
- deployment/gcp/flyte_generated.yaml
- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- kustomize/base/admindeployment/service.yaml
- kustomize/overlays/sandbox/dependencies/contour_ingress_controller/contour.yaml
- kustomize/overlays/sandbox/dependencies/contour_ingress_controller/service.yaml
Between previous versions and later version the annotation to access a grpc service was change. Also during the previous change localhost:30084 was accidently removed. This change keeps the nodeport but also allows grpc to seamlessly work on port 80.
Thus to use the new sandbox config with flyte-cli use the following cli
```bash
$ flyte-cli -h localhost:80  -i list-projects
```
`Note the :80` this is required. Also assuming you are using docker for mac or running k8s locally`
here localhost can be replaced with envoy external IP
for flytectl use the following config
```yaml
admin:
endpoint: localhost:80
insecure: true
```
> Access GRPC services using projectcontour

- deployment/eks/flyte_generated.yaml
- deployment/gcp/flyte_generated.yaml
- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- kustomize/base/single_cluster/headless/config/admin/server.yaml
- This change enables event version 1.0 by default. This is useful in
complex node to node relationships
> Enabling Event version 1 by default

- README.md
Current url is broken, changed to documentation url used in https://flyte.org/
> update readme with correct docs url

- deployment/sandbox/flyte_generated.yaml
- kustomize/overlays/sandbox/admin/deployment.yaml
- This is because the getting started guide uses this
> FlyteExamples should be one of the seedprojects

- CHANGELOG/CHANGELOG-v0.11.0.md
- deployment/eks/flyte_generated.yaml
- deployment/gcp/flyte_generated.yaml
- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- end2end/tests/endtoend.yaml
- kustomize/overlays/eks/kustomization.yaml
- kustomize/overlays/gcp/kustomization.yaml
- kustomize/overlays/sandbox/kustomization.yaml
- kustomize/overlays/test/kustomization.yaml
- rsts/conf.py
Milestone v0.11 release.  See change log for details.
Versions:
flytekit: v0.16.0b15
flyteadmin: v0.3.37
flyteplugins: v0.5.27
> Milestone v0.11

- rsts/howto/productionize/index.rst
- rsts/howto/productionize/production_eks.rst
> AWS EKS Illustration: Production single cluster mode

- rsts/conf.py
This diff makes the top nav consistent so that users can toggle between the main docs.flyte.org docs, the cookbook tutorials, and flytekit reference docs.
> add flytekit docs link to top navbar

- deployment/eks/flyte_generated.yaml
- deployment/gcp/flyte_generated.yaml
- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- kustomize/base/admindeployment/deployment.yaml
- kustomize/base/propeller/kustomization.yaml
- kustomize/base/propeller/webhook.yaml
- kustomize/base/single_cluster/headless/config/propeller/core.yaml
- kustomize/overlays/eks/kustomization.yaml
- kustomize/overlays/gcp/kustomization.yaml
- kustomize/overlays/sandbox/flyte/admin/deployment.yaml
- kustomize/overlays/sandbox/flyte/kustomization.yaml
- kustomize/overlays/sandbox/flyte/propeller/webhook-secret.yaml
- kustomize/overlays/sandbox/flyte/propeller/webhook.yaml
- kustomize/overlays/sandbox/kustomization.yaml
- kustomize/overlays/test/kustomization.yaml
- rsts/conf.py
- rsts/getting_started/run_on_flyte.rst
- rsts/howto/index.rst
- rsts/howto/secrets.rst
https://github.com/flyteorg/flyte/issues/800
> Pod Webhook deployment & Doc

- deployment/eks/flyte_generated.yaml
- deployment/gcp/flyte_generated.yaml
- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- kustomize/base/admindeployment/clustersync/cron.yaml
- kustomize/base/admindeployment/deployment.yaml
- kustomize/base/single_cluster/headless/config/admin/remote_data.yaml
- kustomize/base/single_cluster/headless/config/admin/server.yaml
- kustomize/base/single_cluster/headless/kustomization.yaml
- kustomize/overlays/eks/flyte/config/admin/remote_data.yaml
- kustomize/overlays/eks/flyte/kustomization.yaml
- kustomize/overlays/eks/kustomization.yaml
- kustomize/overlays/gcp/flyte/config/admin/remote_data.yaml
- kustomize/overlays/gcp/flyte/kustomization.yaml
- kustomize/overlays/gcp/kustomization.yaml
- kustomize/overlays/sandbox/flyte/admin/deployment.yaml
- kustomize/overlays/sandbox/kustomization.yaml
- kustomize/overlays/test/flyte/admin/deployment.yaml
- kustomize/overlays/test/kustomization.yaml
We can also remove the domains and the db options if we really want to, but I think it's instructive to leave those in since I imagine they're more frequently configured per-deployment and having a base to work off of is helpful.
On the flipside, would it be useful to include task resource request & limit defaults in flyteadmin too?
> Remove flyteadmin config options which now have defaults

- deployment/eks/flyte_generated.yaml
- deployment/gcp/flyte_generated.yaml
- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- kustomize/base/propeller/rbac.yaml
By explicitly granting flyteworkflow finalizer permissions to flytepropeller, it is clearer which specific permissions are necessary for flyte to work.
> explicitly grant flyteworkflow finalizer permissions to flytepropeller

- .github/workflows/publish-menifest.yml
- .gitignore
- .goreleaser.yml
- Makefile
- script/prepare_artifacts.sh
Fix: #946
- Added Github workflow for publishing deployment manifest in release
- Goreleaser will create a general discussion for each release 🤩
> Added goreleaser for publishing menifest

- rsts/index.rst
> Add tagline

- rsts/getting_started.rst
since we're consolidating our docs, we want to use the getting
started example originally from flytesnacks. Here we're moving
it into the flyte repo since the flytesnacks example should be
the canonical getting started guide
> update getting started guide

- helm/templates/common/ingress.yaml
"Hey so, I noticed that you are using the Ingress class out of beta, which is kind of an issue-- the Ingress class was moved out of beta in the 1.19 release, which happened in late august. If flyte is run in clusters older than this (e.g. 1.18), then this will fail. EKS only started offering 1.19 a couple of months ago, and the GKE regular channel defaults to 1.18, so this really won't work for most of your users. Do you guys mind if I file a pr to move back to the beta ingress version? I don't see you guys using anyhting required from the GA version, and beta has been serving everyone well for the past 6 years"
> Use beta version of ingress

- docker/sandbox/wait-for-flyte.sh
`k3s kubectl apply -f /flyteorg/share/flyte_generated.yaml` is an async command and doesn't wait for the deployments to be created.
Hence when on the next line we call wait-for-flyte.sh it fails in rare cases where the deployment hasn't yet been created and we call into `k3s kubectl wait --for=condition=available`
Following is the error that thrown
```
Error from server (NotFound): deployments.apps "datacatalog" not found
Error from server (NotFound): deployments.apps "flyteadmin" not found
Error from server (NotFound): deployments.apps "flyteconsole" not found
Error from server (NotFound): deployments.apps "flytepropeller" not found
Timed out while waiting for the Flyte deployment to start
```
Would be ideal for kubectl …
> Wait for deployments to be created using rollout before checking for availability

- README.md
- rsts/howto/enable_and_use_schedules.rst
- rsts/howto/launchplans.rst
- rsts/howto/notifications.rst
- rsts/index.rst
- rsts/plugins/spark_k8s.rst
due to https://github.com/flyteorg/flytesnacks/pull/200
we need to update a bunch of links referring to auto-generated
flytesnacks examples
> update links to autogenerated flytesnacks pages

- helm/templates/_helpers.tpl
- helm/templates/propeller/deployment.yaml
- helm/templates/propeller/webhook.yaml
- helm/values.yaml
Based on a8c01e5a Pod Webhook deployment & Doc (#857)
@kumare3 @EngHabu please have a look. Also feel free to push any enhancements/fixes directly here. I skimmed through https://github.com/flyteorg/flyte/blob/master/rsts/howto/secrets.rst but I couldn't really test it.
> Add Pod Webhook deployment to Helm chart

- rsts/community/troubleshoot.rst
- rsts/getting_started.rst
Getting started change
Troubleshooting change
> Added tip for make start to check troubleshooting page

- doc-requirements.in
- doc-requirements.txt
- rsts/conf.py
- rsts/index.rst
This PR adds the edit on github link to the bottom of the page and icons to the main nav items to make it appear more distinct from the bottom nav:
> add fontawesome icon to main nav toc, add edit on github link

- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
- helm/templates/_helpers.tpl
- helm/templates/admin/cluster_resource_configmap.yaml
- helm/values-eks.yaml
- helm/values.yaml
Auto-generates a new cluster configuration template for copilot that has the storage configuration.
> Helm template upgrade to auto-generate co-pilot configuration

- Makefile
- Added mkdir before running make `preprare_artifacts`
> Hotfix for release workflow

- README.md
- deployment/eks/flyte_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
- deployment/test/flyte_generated.yaml
- end2end/tests/endtoend.yaml
- helm/README.md
- helm/values.yaml
- kustomize/base/single_cluster/headless/config/propeller/plugins/copilot.yaml
- kustomize/overlays/eks/kustomization.yaml
- kustomize/overlays/gcp/kustomization.yaml
- kustomize/overlays/sandbox/kustomization.yaml
- kustomize/overlays/test/kustomization.yaml
- rsts/getting_started.rst
- script/generate_helm.sh
This change updates ghcr.io container references to instead use flyte's new cr.flyte.org domain. All generated yaml files have been updated as well. Please let me know if I missed anything, changed something that shouldn't be, etc. Thanks!
> Use cr.flyte.org to fetch flyte containers

- deployment/gcp/flyte_helm_generated.yaml
- helm/templates/admin/deployment.yaml
- helm/templates/postgres/service.yaml
Signed-off-by: ajsalow <ajsalow@umich.edu>
Close #1142
> use values.yaml when testing for postgres readiness

- helm/README.md
- helm/templates/_helpers.tpl
- helm/templates/admin/deployment.yaml
- helm/values.yaml
This change allows customizing the projects created on helm install. Defaults to the previously hardcoded list of ["flytesnacks","flytetester","flyteexamples"].
> Make initial projects customizable

- helm/manifest.yaml
- helm/values-eks.yaml
This arn points to self signed cert generated for flyte.example.org
arn:aws:acm:us-east-2:832573439839:certificate/577f9991-a6cf-4d1c-b56d-447b24077f46
User can directly hit the ingress https endpoint to browse UI console and also hit grpc to query through flytectl
User has to ignore the warning when browsing the UI console which is expected and new flag in flytectl has been added to do the same skip. This won't be the case in production flyte deployment where a CA verified cert will be used.
> Added conditional annotation for grpc to use HTTP2 as target group

- .github/workflows/tests.yml
Kind started failing to bring up CNI plugin and causing E2E tests to fail across all repos. We're not sure what caused this but something in the Github environment is probably to blame.
> Update Kind to 0.11.1 to fix CNI issue

- docker/sandbox/Dockerfile
- docker/sandbox/flyte-entrypoint-default.sh
- docker/sandbox/flyte-entrypoint-dind.sh
- docker/sandbox/kustomization.yaml
- docker/sandbox/kustomization.yaml.tmpl
Context : In flytectl sandbox, I am introducing a new flag i.e. `--kustomize`, But for that container should build manifest before deployment in the entry point.`. Currently, Pytest-flyte maintains the logic for kustomize build-in entry point (https://github.com/flyteorg/pytest-flyte/tree/main/src/pytest_flyte/docker). 
- I used the same implementation that pytest has but after these changes flytectl and pytest can share the same dependency.
> Added kustomize support in docker sandbox

- docker/sandbox/Dockerfile
- Added kustomize file in docker for non dind image 
Currently non did image is failing because of  kustomize file. 
```bash
$ docker run --rm --privileged -p 30081:30081 -p 30084:30084 cr.flyte.org/flyteorg/flyte-sandbox
Starting k3s cluster...
Done.
Deploying Flyte...
error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/flyteorg/sh
```
Fix : #1321
> Bugfix - Added kustomize file in non dind image 

- .github/workflows/sandbox.yml
- docker/sandbox/Dockerfile
- docker/sandbox/flyte-entrypoint-default.sh
- docker/sandbox/flyte-entrypoint-dind.sh
- docker/sandbox/wait-for-flyte.sh
Bug Sandbox break after a new release. The issue was I didn't add `helm dep update` and it got passed in local testing because I have all the dependency when I build the image and it didn't through error
Fix:
- Made changes in GitHub workflow, Now we will publish sandbox image in each release
- At runtime in the entry point script, Sandbox will add helm registry and always install the latest release with `values-sandbox.yaml`....values-sandbox is always available in docker image but we can override it
Tested:  Tested for both images dind & nondind...Also able to excute basic workflow 
```
Starting Docker daemon...
Done.
Starting k3s cluster...
Done.
Deploying Flyte...
"flyteorg" has been added to your repositories
NAME: flyte
LAST DEPLOYED: Fri Sep 3 10:42:32 2021
NAMESPACE: flyte
STATUS: …
```
> [WIP] Added hotfix for sandbox

- .dockerignore
- .github/workflows/sandbox.yml
- CHANGELOG/CHANGELOG-v0.17.1.md
- charts/flyte/templates/minio/service.yaml
- charts/flyte/values-gcp.yaml
- charts/flyte/values-sandbox.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
- docker/sandbox/Dockerfile
- docker/sandbox/flyte-entrypoint-default.sh
- docker/sandbox/flyte-entrypoint-dind.sh
- Added .dockerignore 
- Added changelog for v0.17.1
- Added k8s dashboard & minio nodePort in sandbox helm values
- Revert GitHub workflow for sandbox
> patch v0.17.1 - Fixed sandbox issue

- rsts/concepts/tasks.rst
The recent [flyteidl](https://github.com/flyteorg/flyteidl/pull/220) reverted the variable map entry change. This PR partially reverts https://github.com/flyteorg/flyte/pull/1400/files which added variable map entry.
The link now points to
https://docs.flyte.org/projects/flyteidl/en/latest/protos/docs/core/core.html#variablemap-variablesentry
Signed-off-by: Sean Lin <sean@union.ai>
> Revert variablemapentry change in task.rst

- end2end/execute.sh
Try to run the end2end test locally, and found that macOS doesn't have a timeout command
Add a timeout function to support cross-platform.
Refer to: https://gist.github.com/jaytaylor/6527607
```
+ echo /Users/kevin/git/flyteadmin/boilerplate/flyte/end2end/tmp/end2end
/Users/kevin/git/flyteadmin/boilerplate/flyte/end2end/tmp/end2end
+ kubectl -n flyte create -f /Users/kevin/git/flyteadmin/boilerplate/flyte/end2end/tmp/end2end/tests/endtoend.yaml
pod/endtoend created
+ /usr/bin/timeout 1200 /Users/kevin/git/flyteadmin/boilerplate/flyte/end2end/tmp/end2end/test_monitor.sh
end2end/execute.sh: line 48: /usr/bin/timeout: No such file or directory
++ /Users/kevin/git/flyteadmin/boilerplate/flyte/end2end/tmp/end2end/print_logs.sh
+ df -H
Filesystem …
```
> Add timeout function

- rsts/deployment/plugin_setup/index.rst
- rsts/deployment/plugin_setup/k8s/index.rst
- rsts/deployment/plugin_setup/k8s/mpi_operator.rst
- rsts/deployment/plugin_setup/k8s/pytorch_operator.rst
- Refactor folder structure for plugin
Fix: https://github.com/flyteorg/flyte/issues/820
> Refactor plugin docs

- .github/workflows/sandbox.yml
- docker/sandbox/Dockerfile
Updated Dockerfile for helm and k3s installations to be platform agnostic
Modified sandbox build pipeline to build linux/amd64 and linux/arm64 versions
Uses docker/build-push-action@v2 to build docker images as docker-build-with-cache-action doesn't support multi-platform builds
Fix: #1248
Depends on https://github.com/flyteorg/flytectl/pull/209 to add arm entries to `install.sh`
> Sandbox support for arm64

- rsts/getting_started.rst
- rsts/getting_started_iterate.rst
- rsts/getting_started_scale.rst
This is the corresponding changes to the Getting Started docs in order to reflect the introduction of[ cookiecutter templates in flytekit](https://github.com/flyteorg/flytekit/pull/738). 
This should only be merged after we cut the new `flytekit` release.
The Getting started docs now look like: https://flyte--1801.org.readthedocs.build/en/1801/getting_started.html
> Update the Getting started docs to use `pyflyte init`

- .github/workflows/sandbox.yml
- docker/sandbox/flyte-entrypoint-default.sh
- docker/sandbox/flyte-entrypoint-dind.sh
- Added fix for sandbox restart
Problem: Currently k3s bring all the resource during restart, Ideally in this case we don't need `helm install` but our entrypoint script has `helm install` steps  that's why it through error 
```
Deploying Flyte...
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://googlecloudplatform.github.io/spark-on-k8s-operator" chart repository
...Successfully got an update from the "https://kubernetes.github.io/dashboard/" chart repository
...Successfully got an update from the "https://charts.bitnami.com/bitnami" chart repository
Saving 3 charts
Downloading contour from repo https://charts.bitnami.com/bitnami
Downloading spark-operator from repo https://googlecloudplatform.github.io/spark-on-k8s-operator
Downloading …
```
> fix sandbox restart

- Makefile
Nit: Generate config docs only when running release workflow
> Generate config docs only when running release workflow

- .github/workflows/sandbox.yml
- docker/sandbox/Dockerfile
- docker/sandbox/flyte-entrypoint-default.sh
- docker/sandbox/flyte-entrypoint-dind.sh
Currently for local testing if user wants to upgrade the sandbox then they need clone the flyte repo because of chart but with new changes user can use registry name for installing/upgrading the sandbox. 
For new release user can use `flyteorg/flyte` for installing/upgrading helm in sandbox, For older version user need to clone flyte repo for installing/upgrading flyte helm
> Added helm registry in sandbox

- charts/flyte-core/values-gcp.yaml
- deployment/gcp/flyte_helm_generated.yaml
With trial GCP account , the e3-medium machines 940 mCPU allocatable per node.
Reducing the default for task resources.
Tested this on GCP by running the basic greet worflow from flytesnack
s
> Reduced the defaults on gcp

- charts/flyte/Chart.yaml
- charts/flyte/README.md
- deployment/sandbox/flyte_helm_generated.yaml
Currently if we used sandbox chart name `flyte-sandbox` then it will publish new chart and old chart will not work, In this way user just need to update values.yaml for helm chart migration. 
https://artifacthub.io/packages/search?ts_query_web=flyte&sort=relevance&page=1
> rename chart for backword compatibility

- .github/workflows/create-release.yml
Currently github action has wrong key for getting up the right copilot image, Fixed the key name in workflow.
Test: https://github.com/evalsocket/flyte/settings/secrets/actions
> Added fix for copilot in release pipeline

- rsts/concepts/flyte_console.rst
- rsts/index.rst
A doc to explain Flyte UI's utilities.
Preview: https://flyte--1885.org.readthedocs.build/en/1885/concepts/flyte_console.html
> How to use Flyte UI

- rsts/deployment/gcp/manual.rst
The `values-gcp.yaml` is no more under the flyte charts folder. I updated the link to the version under flyte-core.
Also missing two permissions are added to `DataCatalog` role to make caching available.
Tracking issue: https://github.com/flyteorg/flyte/issues/1950
> Docs: Add missing permissions in GCP Manual Deployment and update missing values

- charts/flyte-core/templates/common/ingress.yaml
Looks like I missed the separate GRPC ingress in #1907.
> Make TLS secret name configurable for separate GRPC ingress too

- docker/sandbox/flyte-entrypoint-default.sh
- docker/sandbox/flyte-entrypoint-dind.sh
- Removed files in sandbox after successful deployment 
- 
Fix: https://github.com/flyteorg/flyte/issues/1989 
Testing
```
Starting Docker daemon...
Done.
Starting k3s cluster...
Done.
Deploying Flyte...
"flyteorg" has been added to your repositories
Release "flyte" does not exist. Installing it now.
NAME: flyte
LAST DEPLOYED: Tue Dec 28 09:34:09 2021
NAMESPACE: flyte
W1228 09:34:03.314490 710 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W1228 09:34:03.606660 710 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W1228 09:34:03.829549 710 …
```
> remove .cache .helm .kube root files in sandbox

- rsts/concepts/architecture.rst
- rsts/concepts/basics.rst
- rsts/concepts/control_plane.rst
- rsts/deployment/index.rst
- rsts/reference/index.rst
fixes https://github.com/flyteorg/flyte/issues/2013
These three PRs together will update the main section TOC card styles
https://github.com/flyteorg/flyte/pull/2027
https://github.com/flyteorg/flytesnacks/pull/575
https://github.com/flyteorg/furo/pull/9
Once these changes are merged the TOC cards should look like:
> update main section TOC card styles

- opta/aws/flyte.yaml
- opta/gcp/flyte.yaml
Currently in aws opta setup, We are not overriding the propeller config for bucket name, That's why execution is failing in cluster, 
To avoid the conflict, I added the user setting in opta so if we missed something then `values-eks.yaml` will override it 
Fix: https://github.com/flyteorg/flyte/issues/1827
> Added user setting in opta, 

- doc-requirements.in
- doc-requirements.txt
Issue started because of github changes https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
pip install stop working because of deprecated protocol, Change it from git:// to https://
> fix github security issue in requirments

- charts/flyte-core/templates/admin/rbac.yaml
- charts/flyte-core/templates/common/ingress.yaml
- charts/flyte-core/templates/propeller/crds/flyteworkflow.yaml
- charts/flyte-core/templates/propeller/rbac.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
The CRD for the flyteworkflows is incomplete, atm. A schema should be
added in the near future.
See #1273
> Update apis to allow for compatibility with k8s 1.22

- charts/flyte/Chart.yaml
- charts/flyte/README.md
- deployment/sandbox/flyte_helm_generated.yaml
Make use of `contour 5.0.0` and `spark-operator 1.1.15` which uses `v1` deployment API  instead of `v1beta1`.
> fix: Make Chart compatible to K8s 1.19+

- rsts/deployment/aws/manual.rst
Context: https://flyte-org.slack.com/archives/C01P3B761A6/p1644289769067409
> fix: add explanation about insecure option

- README.md
Currently, the community meeting google doc points to the bottom of the google doc.
The PR changes it to point to the top of the docs page
> Update readme - to fix the community meeting google docs link

- charts/flyte-core/README.md
- charts/flyte-core/templates/admin/deployment.yaml
- charts/flyte-core/templates/console/deployment.yaml
- charts/flyte-core/templates/datacatalog/deployment.yaml
- charts/flyte-core/templates/flytescheduler/deployment.yaml
- charts/flyte-core/templates/propeller/deployment.yaml
- charts/flyte-core/templates/propeller/manager.yaml
- charts/flyte-core/values.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
- script/generate_helm.sh
Under pressure, k8s starts evicting pods and all pods being equal, critical flyte pods can also get evicted and new ones get stuck in a pending state. [Setting priorityClassName](https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/) can help prioritize these pods to ensure the flyte cluster is up and continues to be responsive.
> Support setting priorityClassName for flyte pods

- charts/flyte-core/README.md
- charts/flyte-core/templates/admin/rbac.yaml
- charts/flyte-core/templates/propeller/crds/flyteworkflow.yaml
- charts/flyte-core/templates/propeller/rbac.yaml
- charts/flyte-core/templates/propeller/webhook.yaml
- charts/flyte-core/values.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
- add namespace as prefix to ClusterRole and ClusterRoleBinding
- add a config to disable flyteworkflow CRD installation
Helps to avoid clashes of cluster-scoped resources so we can have multiple flyte-installations side-by-side in different namespaces in the same cluster.
> Make it possible to install multiple flyte installation in a single cluster

- charts/flyte-core/README.md
- charts/flyte-core/templates/admin/deployment.yaml
- charts/flyte-core/templates/datacatalog/deployment.yaml
- charts/flyte-core/values-eks.yaml
- charts/flyte-core/values.yaml
- deployment/gcp/flyte_helm_controlplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
- docker/sandbox/Dockerfile
Flyteadmin and datacatalog use check-db-ready init containers before running the migrations.
This is to avoid the following error during the migrations
```
kubectl logs -f -n flyte flyteadmin-c787fff7b-vhk2q  run-migrations
time="2022-03-14T06:05:10Z" level=info msg="Using config file: [/etc/flyte/config/cluster_resources.yaml /etc/flyte/config/db.yaml /etc/flyte/config/domain.yaml /etc/flyte/config/logger.yaml /etc/flyte/config/remoteData.yaml /etc/flyte/config/server.yaml /etc/flyte/config/storage.yaml /etc/flyte/config/task_resource_defaults.yaml]"
2022/03/14 06:06:25 /go/src/github.com/flyteorg/flyteadmin/pkg/repositories/database.go:102
[error] failed to initialize database, got error failed to connect to …
```
> Removed db check container from sandbox

- charts/flyte-core/README.md
- charts/flyte-core/values-eks.yaml
- charts/flyte-core/values.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_controlplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_controlplane_generated.yaml
- deployment/gcp/flyte_helm_dataplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
- script/generate_helm.sh
- GCP helm deployment is failing because of priority class, Removed for GCP
- Replaced `go get` with `go install` in ci
> remove priority class from gcp helm values

- RELEASE.md
Functional tests run as reusable workflows now.
> Remove unnecessary steps from release guide

- charts/flyte-core/templates/propeller/webhook.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
- deployment/test/flyte_generated.yaml
- kustomize/base/pod_webhook/rbac.yaml
without granting this permission, installation of the mutatingwebhookconfiguration fails with the following error:
```
Error: mutatingwebhookconfigurations.admissionregistration.k8s.io "flyte-pod-webhook" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
```
> explicitly grant replicasets finalizer permissions to flyte-pod-webhook

- docker/sandbox-lite/Dockerfile
- Remove `kubectl`, we can use `k3s kubectl` instead 
The main reason why the sandbox lite dnd image takes an hour to build is that it's our first time building the image, and we don't even cache any image layers.
I built the image in my fork repo a second time, it only took 3 mins
https://github.com/pingsutw/flyte/actions/runs/2163267735
> Speed up building process of sandbox-lite image

- charts/flyte-core/README.md
- charts/flyte-core/values-eks.yaml
- charts/flyte-core/values-gcp.yaml
- charts/flyte-core/values.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_controlplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_controlplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- flyte.yaml
- flyte_local.yaml
- Defaults for task resources are too low
- Upgrading the defaults to slightly higher values. Having these low
defaults on cloud k8s is just wrong!
fixes: https://github.com/flyteorg/flyte/issues/2376
> Update default task resources

- rsts/getting_started/index.rst
https://github.com/flyteorg/flytekit/pull/960 modified the `pyflyte run` interaction. 
We should only merge this after flytekit `1.0.0` is out. Also, it'd be good to mention that running `pyflyte run <workflow_file.py> <workflow_name> --help` actually produces a message containing the description of the workflow parameters, including their types.
> Update getting started guide to follow new style of pyflyte run

- rsts/deployment/cluster_config/performance.rst
Currently the performance doc discusses increasing the rate limiting parameters on kube API server but doing so may result in transparent throttling which results in steep performance decreases. Adding a brief warning and information on how to debug kube API server throttling will help alleviate duplicate questions when tuning propeller performance for large scale workloads.
Signed-off-by: Daniel Rammer <daniel@union.ai>
> Update performance doc to include kube API server throttling warning

- charts/flyte-core/templates/clusterresourcesync/cronjob.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_controlplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_controlplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
The pod annotations for `flyteadmin` and `clusterresourcesync` are inconsistent in the `flyte-core` helm chart. 
Flyteadmin:
```yaml
template:
metadata:
annotations:
configChecksum: {{ include (print .Template.BasePath "/admin/configmap.yaml") . | sha256sum | trunc 63 | quote }}
{{- with .Values.flyteadmin.podAnnotations }}
{{- toYaml . | nindent 8 }}
{{- end }}
```
Clusterresourcesync: 
```yaml
template:
{{- with .Values.flyteadmin.podAnnotations }}
metadata:
annotations: {{ tpl (toYaml .) $ | nindent 12 }}
{{- end }}
```
Note that one will try to complete the template, whereas the other will not. 
So with annotations defined as: 
```yaml
flyteadmin:
podAnnotations:
vault.hashicorp.com/agent-inject-template-flyte-admin-database: |
{{- with secret "secret/flyte/admin/database" -}}
{{- …
```
> Use the same pod annotation formatting in syncresources cronjob

- charts/flyte-core/templates/console/service.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_controlplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_controlplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
Port naming is required for some tools to function correctly 
Istio requires the following naming convention: https://istio.io/v1.0/docs/setup/kubernetes/spec-requirements/
Ports in the `admin` template are already named using this convention: 
https://github.com/flyteorg/flyte/blob/6c3d3abe55eda0199a866f77cfd09da4707f5960/charts/flyte-core/templates/admin/service.yaml#L20
> Add "http" name to port 80 in console template (flyte-core helm chart)

- rsts/getting_started/index.rst
`grpcio` python 3.10 wheel [is mislabeled as universal](https://github.com/flyteorg/flyte/issues/2486), which makes it so that all uses cases in flytekit that require a connection to admin are going to fail.
Here's how it renders:
The next step is to figure out a way of doing this automatically in flytekit itself, but just to unblock M1 users, let's add a note in the docs.
> Add note about python 3.10 on Mac M1's

- docker/sandbox-lite/Dockerfile
- flyte.yaml
Related to https://unionai.slack.com/archives/C01H0FN1NJX/p1652311344484609
1. we will expose the webhook service(30090) in flytectl so that the k8s API server can connect to it. 
2. Add env POD_NAMESPACE=flyte to [dockerfile](https://github.com/flyteorg/flyte/blob/81044f8b1d620b123318db3fb9fe8d38fe74f565/docker/sandbox-lite/Dockerfile#L86), just like we did in [webhook deployment](https://github.com/flyteorg/flyte/blob/0f4ccfc58ad0d3656a37baf483a4cec073dae960/charts/flyte-core/templates/propeller/webhook.yaml#L57-L60)
> single binary: Add env POD_NAMESPACE to dockerfile

- rsts/deployment/aws/manual.rst
Made it clear that the Account ID requires quotation marks on the helm yaml.
Also updated the flyte config yaml to use the correct keys for the storage block: type instead of kind and connection instead of config.
Signed-off-by: Roberto Ruiz <robertorrw@gmail.com>
> Updated AWS manual deployment doc

- charts/flyte-core/templates/clusterresourcesync/deployment.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_controlplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_controlplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
This is done as otherwise we would get a ` <.Template.BasePath>: nil pointer evaluating interface {}.BasePath` error when setting e.g.:
```yaml
cluster_resource_manager:
podAnnotations:
foo: bar
```
Signed-off-by: Bernhard Stadlbauer <11799671+bstadlbauer@users.noreply.github.com>
> Re-order clusterresourcesync annotations

- .github/workflows/create_release.yml
Fixes the repository dispatch event to update the release on flyte.org
> fix repository dispatch

- charts/flyte-core/README.md
- charts/flyte-core/templates/flytescheduler/deployment.yaml
- charts/flyte-core/values.yaml
This PR adds a configuration option to make the `precheck` init-container optional for `flytescheduler`. This is useful, as it enables the use of the scheduler together with Istio (see #2562 for more information).
Happy to rename/reorder the configuration option, just let me know :-) 
Also @pmahindrakar-oss, I've tried runnning `make helm`, but it seems like `helm` can't resolve the  `bitnami/contour` chart in version `5.0.0` (dependency of the `flyte` chart), seems like that might have been yanked? 
Closes #2562 
Signed-off-by: Bernhard Stadlbauer <11799671+bstadlbauer@users.noreply.github.com>
> Add `runPrecheck` option to `flytescheduler`

- rsts/deployment/sandbox.rst
Issue: https://github.com/flyteorg/flyte/issues/2589
Changed 'kubect' to 'kubectl' in 2 commands
Signed-off-by: SmritiSatyanV smriti@union.ai
> Change 'kubect' to 'kubectl' in commands

- .github/workflows/create_release.yml
- .github/workflows/update_site.yml
The current repository dispatch event is somehow not working. @evalsocket suggested adding a new workflow to handle it.
> modify repository dispatch event

- rsts/deployment/cluster_config/auth_setup.rst
This updates the authentication docs to deal with a few challenges I faced when setting up auth:
* fixes incorrect indentation in a code example
* adds more explicit instructions for an Okta integration
* adds some warnings, clarifications, and callouts around problem areas - such as audience vs authorizedUri mismatches, and missing scopes.
> Update flyte auth documentation

- charts/flyte-core/values-eks.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_controlplane_generated.yaml
- deployment/eks/flyte_helm_dataplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
This PR solved the problem mentioned in this Slack thread: https://flyte-org.slack.com/archives/C01P3B761A6/p1657134258930409
In short: The backend protocol should be GRPC as `flytectl` talks to `flyteadmin` through `GRPC`.
My Flyte on EKS Deployment could not communicate with Flyte Admin as long as I did not apply this fix.
> Add GRPC as backend protocol version instead of HTTP2 for values eks.

- rsts/deployment/cluster_config/general.rst
[Issue](https://github.com/flyteorg/flyte/issues/2616)
Document how a default PodTemplate can be used to configure K8s Pods.
Signed-off-by: SmritiSatyanV smriti@union.ai
> update general.rst to show how PodTemplate can be used to configure K8s Pods

- README.md
Adds new conferences and podcasts to the README file.
> Adds conferences and podcasts to README

- rsts/deployment/aws/manual.rst
People who create a self-signed certificate could smoothly follow the guide and run flytectl command
Context: https://flyte-org.slack.com/archives/C01P3B761A6/p1660034053737829?thread_ts=1659969940.256979&cid=C01P3B761A6
Signed-off-by: Jacob Wang <jacob.wang@monto.ai>
> Improve AWS manual deployment doc

- charts/flyte-core/README.md
- charts/flyte-core/templates/propeller/deployment.yaml
- charts/flyte-core/values.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_dataplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_dataplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
Add `terminationMessagePolicy` to the flytepropeller templates and set to `FallbackToLogsOnError` by default. This makes failure info available through the k8s pod status interface.
> Fallback to logs in propeller termination message by default

- rsts/deployment/cluster_config/general.rst
Signed-off-by: Rahul Mehta <rahul@theoremlp.com>
Fix docs for Task Resources to correctly refer to `task_resource_defaults`
See https://flyte-org.slack.com/archives/C01P3B761A6/p1661876831008679 for related discussion
> Fix "Task Resources" default values link

- charts/flyte-core/README.md
- charts/flyte-core/templates/admin/deployment.yaml
- charts/flyte-core/values.yaml
This change adds an optional value to append containers to the flyteadmin containters list. This can be used to co-deploy sidecar functionality.
Verified that the following local changes
```
-  additionalContainers: {}
+  additionalContainers:
+  - command:
+    - flyteadmin
+    - --config
+    - "{{ .Values.flyteadmin.configPath }}"
+    - ...
```
Produce the expected output
```
--- a/deployment/eks/flyte_aws_scheduler_helm_generated.yaml
+++ b/deployment/eks/flyte_aws_scheduler_helm_generated.yaml
@@ -965,6 +965,11 @@ spec:
name: clusters-config-volume
- mountPath: /etc/secrets/
name: admin-secrets
+      - command:
+        - flyteadmin
+        - --config
+        - '/etc/flyte/config/*.yaml'
+        - '...'
serviceAccountName: flyteadmin
volumes:
- name: db-pass
```
> Add 'additionalContainers' value for flyteadmin

- charts/flyte-core/templates/admin/deployment.yaml
- charts/flyte-core/templates/datacatalog/deployment.yaml
- charts/flyte-core/templates/propeller/deployment.yaml
- charts/flyte-core/templates/propeller/manager.yaml
This changes fixes the formatting of optional `extraArgs` in the deployment templates
> Fix extraArgs templating in deployments

- rsts/deployment/multicluster.rst
I ran into some issues with the example config of the multi-cluster setup:
- underscores are not allowed when naming volumes/volumeMounts in kubernetes
- `enabled: true` is not indented correctly. This is quite nasty as Flyteadmin doesn't fail, but the setup doesn't work
> Fix example config

- docker/sandbox-lite/flyte-entrypoint-dind.sh
- docker/sandbox/flyte-entrypoint-default.sh
When deploying the flyte-sandbox-lite image I ran into races between `k3s server` and `helm upgrade`. Previously the entrypoint scripts waited for `k3s kubectl explain deployment` to complete successfully. With this change we now explicitly wait on the node to be up and ready.
```
$ docker build -t flyte-sandbox-lite --target=dind --compress=true -f ./docker/sandbox-lite/Dockerfile .
$ docker run --rm -it --privileged flyte-sandbox-lite
$ docker build -t flyte-sandbox --target=dind --compress=true -f ./docker/sandbox/Dockerfile .
$ docker run --rm -it --privileged flyte-sandbox
```
> Add explicit check for k3s server startup completion

- .github/workflows/selfassign.yml
Signed-off-by: Krishna Agarwal <dmkrishna.agarwal@gmail.com>
Commenting `#self-assign` or `#take` in any issue will let repository members to self-assign that issue to themselves.
👉 This reduces chores for repo-maintainer(s).
It's very helpful
cc @eapolinario and @wild-endeavor, @SmritiSatyanV
> Allow contributors to self-assign issues with GitHub workflow

- .gitignore
- Dockerfile
- docker/sandbox-ultra/Makefile
- docker/sandbox-ultra/README.md
- docker/sandbox-ultra/bootstrap/output.yaml
- docker/sandbox-ultra/flyte.yaml
- docker/sandbox-ultra/images/dockerfiles/k3s/Dockerfile
changes to your PR @evalsocket are:
* Add a `flyte.yaml` file so that we can embed it in the docker image itself.  This will work with the `flytectl demo init` command to copy the file to the user's local directory if missing.
* add the rancher pause image to the bundle.
* adding output.yaml (though we should move away from this and move to the output of the `helm template` command.
* had to change around the command a bit for the images folder.  it kept trying to make `amd64` and `arm64` subfolders even though i'm not using the $BUILDARCH var in the cp destination.  So i just went with a move.
> Cicd sandbox lite yt -> cicd-sandbox-lite

- charts/flyte-core/templates/clusterresourcesync/configmap.yaml
- charts/flyte-core/templates/clusterresourcesync/deployment.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_controlplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_controlplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
This PR adds the missing `clusters` configmap as well as cluster credentials to the `syncresources` deployment of the `flyte-core` helm chart.
The changes assumes the appropriate cluster credentials existing in the `flyteadmin.secrets` config (as used by `flyteadmin`) and the secret for it exists. We could extract that into a separate secret for `syncresources` if needed, however that might just duplicate data that'll most likely be there in the first place anyways.
Fixes #3001
> Fix multi-cluster support for syncresources helm deployment

- go.mod
- go.sum
Uses version of flyteadmin and datacatalog that ignore db already exists errors on db creation which can occur when single binary starts up both migrations which reference the same database.
N/A
N/A
> Bump flyteadmin and datacatalog versions

- rsts/deployment/cluster_config/auth_setup.rst
See configmap name [here](https://github.com/flyteorg/flyte/blob/e40426e24e500b2031e9ba6d8ae28790c5a7fbd1/charts/flyte-core/templates/admin/configmap.yaml#L18).
Signed-off-by: Fabio M. Graetz, Ph.D. <fabiograetz@googlemail.com>
> Fix wrong configmap name in Auth tutorial

- README.md
#3017 
- Add links for commits, milestones, openssf and twitter
- Remove plastic style for consistency
- Remove newline in `a` tags to prevent unwanted underline on hover
- Bump milestone to current version
- Add link to LF AI & Data image
> Improve shields and header in README (Close #3017)

- flyte.yaml
Signed-off-by: Andrew Dye <andrewwdye@gmail.com>
The flyte-sandbox-lite tasks logs template [defaults to](https://github.com/flyteorg/flyteplugins/blob/master/go/tasks/logs/config.go#L46) `http://localhost:30082/#!/log/...`, which is invalid. The correct form, at least for the kubernetes dashboard deployed in sandbox is `http://localhost:30082/#/log/...`. This change sets the template in the config file. Note this is consistent with the [value set for flyte-sandbox](https://github.com/flyteorg/flyte/blob/master/charts/flyte-core/values-sandbox.yaml#L85).
Not sure of the history of the `/#!/log` form, but possible we want to change the default in flyteplugins instead.
> Fix k8s log template for flyte-sandbox-lite

- README.md
Currently this phrase is interrupted as there is no list after the `via:` 
```
- Guaranteed **[reproducibility](https://docs.flyte.org/projects/cookbook/en/latest/auto/core/flyte_basics/task_cache.html)** of pipelines via:
```
Two solutions could be:
- to remove totaly the `via:`
- to provide the list that was removed in commit 80baa791c02e82cc258c1dfd7184e1b9440a386d, which gives more hints about how reproducibility can be achieved
```
- Guaranteed **[reproducibility](https://docs.flyte.org/projects/cookbook/en/latest/auto/core/flyte_basics/task_cache.html)** of pipelines via:
-  - Versioned data, code, and models
-  - Automatically tracked executions
-  - Declarative pipelines
```
> Update README with list of features that provide reproducibility

- rsts/getting_started/index.rst
Reverts flyteorg/flyte#2487
hey I have verified if you are using python 3.10 with Mac M1's, `pip install flyekit` would work ... 
grpcio                   1.46.5
grpcio-status            1.46.5
and above works fine ...
https://github.com/flyteorg/flyte/issues/3132
> Revert "Add note about python 3.10 on Mac M1's"

- .github/workflows/create_release.yml
- .github/workflows/single-binary.yml
* Update the release job to rely on the fact that the `single-binary.yml` job has already pushed to tag with the release version.
* Remove the publish step from `single-binary.yml`
* Always run single-binary build on merge to master
> Add separate step for binary tagging in Flyte release

- charts/flyte-core/templates/clusterresourcesync/deployment.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_controlplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_controlplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
https://github.com/flyteorg/flyte/issues/3141
https://github.com/flyteorg/flyte/pull/3002 adds the secret mount for admin to be able to other clusters in the multicluster setup but this will cause issues if there are no additional clusters.
> Add conditional around the admin secrets

- Makefile
- charts/flyte-sandbox/README.md
- charts/flyte-sandbox/templates/_helpers.tpl
- charts/flyte-sandbox/templates/local/endpoint.yaml
- charts/flyte-sandbox/templates/local/service.yaml
- charts/flyte-sandbox/templates/proxy/configmap.yaml
- charts/flyte-sandbox/templates/proxy/deployment.yaml
- charts/flyte-sandbox/templates/proxy/service.yaml
- charts/flyte-sandbox/values.yaml
- docker/sandbox-bundled/Makefile
- docker/sandbox-bundled/bin/k3d-entrypoint-load-manifest.sh
- docker/sandbox-bundled/kustomize/dev/kustomization.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
- flyte-single-binary-local.yaml
- script/get_flyteconsole_dist.sh
This PR completes support for running Flyte locally against a sandbox cluster running on your machine. Specifically, it adds:
1. Support for Propeller's secret webhook. It does so by creating a headless service pointing to the docker host's IP address. The host IP is injected via the `%{HOST_GATEWAY_IP}%` template variable.
2. Support for Flyteconsole while running Flyte locally.
> Add Kubernetes objects for dev mode with single-binary sandbox

- charts/flyte-core/values-eks.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_controlplane_generated.yaml
- deployment/eks/flyte_helm_dataplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
This change does not close an open Issue per se, but to I had to make this change in my config to get the ALB creation to work at all. See this Slack Thread for additional background: 
https://flyte-org.slack.com/archives/C01P3B761A6/p1671215817793359
Route traffic for EKS deployment directly from ALB to pods. For details: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#target-type
`alb.ingress.kubernetes.io/target-type: ip `
> Add ip alb ingress target type for EKS values

- docker/sandbox-bundled/Makefile
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
Failed to build the image for single binary.
```
$ make build
=> => exporting manifest sha256:fd5ffa0a5cbfaf72dd4bc89f70be185c856e26656bc6b7456a87600636c0fdac                0.0s
=> => exporting config sha256:83112bc87339d549419c587008ed89b886ce3b34432ccb8a371bf58744eed15b                  0.0s
=> => sending tarball                                                                                           1.9s
mkdir -p manifests
kustomize build \
--enable-helm \
--load-restrictor=LoadRestrictionsNone \
kustomize/complete > manifests/complete.yaml
Error: Error: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: docker-registry, flyte-binary, …
```
> Update helm dependency before kustomize build

- cmd/single/start.go
_NA_
Starting the k8s controller runtime manager so that watches on k8s resources work in plugins. This is necessary to ensure propeller promptly evaluates the workflow after a change in task status is detected.
_NA_
_NA_
> starting controller runtime manager

- cmd/single/start.go
Reverts flyteorg/flyte#3471
```
{"json":{"src":"entrypoint.go:55"},"level":"info","msg":"Starting controller-runtime manager","ts":"2023-03-17T18:46:00Z"}
panic: close of closed channel
goroutine 5276 [running]:
sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).Start.func3()
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/manager/internal.go:493 +0xb6
created by sigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).Start
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.1/pkg/manager/internal.go:483 +0x553
```
> Revert "starting controller runtime manager"

- rsts/deployment/plugins/k8s/index.rst
Tensorflow plugin should be enabled using lowercase letters. Here the typo made it uppercase. This patch fixes it.
> Fix typo for enabling tensorflow plugin doc

- .github/workflows/helm-charts.yaml
This publishes the two Helm charts supported by Flyte (`flyte-core` and `flyte-binary`) to ghcr on every commit to master.  This makes it easier for people testing early versions of Flyte to pick up and test changes.
This should not affect the existing charts published under https://flyteorg.github.io/flyte at all.
Links:
https://github.com/orgs/flyteorg/packages/container/package/helm-charts%2Fflyte-binary
https://github.com/orgs/flyteorg/packages/container/package/helm-charts%2Fflyte-core
> github actions pipeline for publishing developmental helm charts

- charts/flyte-binary/templates/configmap.yaml
- charts/flyte-core/templates/_helpers.tpl
- deployment/gcp/flyte_generated.yaml
- deployment/gcp/flyte_helm_controlplane_generated.yaml
- deployment/gcp/flyte_helm_dataplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- kustomize/overlays/gcp/flyte/config/common/storage.yaml
The previous default scope for stow in GCP
`https://www.googleapis.com/auth/devstorage.read_write` seems to be no longer enough in GKE versions >=1.25.0. We could not find any release notes from Google pointing in this direction but noticed that Flyte would no longer work after we updated the GKE cluster version to 1.25.5.
Fast registration failed with this error response from `flyteadmin`:
```py
..
File "/opt/pyenv-root/versions/3.9.12/lib/python3.9/site-packages/flytekit/remote/remote.py", line 580, in fast_package
return self._upload_file(pathlib.Path(zip_file))
File "/opt/pyenv-root/versions/3.9.12/lib/python3.9/site-packages/flytekit/remote/remote.py", line 598, in _upload_file
upload_location = self.client.get_upload_signed_url(
File …
```
> Fix stow token scope for GKE >= 1.25.0

- rsts/conf.py
This fixes an issue with the copy-button on the `flyte` repo docs
> fixes copy button issue

- docker/sandbox-bundled/Dockerfile
Following k3s instructions here: https://ranchermanager.docs.rancher.com/v2.5/reference-guides/single-node-rancher-in-docker/advanced-options#custom-ca-certificate
Placing extra CA certs in PEM format within `~/.flyte/sandbox/ca-certificates` will suffice to add those to the sandbox trust store.
> Use additional ca-certificates in flyte sandbox configuration directory

- doc-requirements.txt
- rsts/deployment/configuration/auth_setup.rst
https://github.com/flyteorg/flyte/issues/3620
Add azure ad setup doc to **Authenticating in Flyte**
> Add azure ad auth setup doc

- rsts/deployment/plugins/k8s/index.rst
This PR updates the installation instructions accordingly. For the tensorflow operator this was already documented correctly. I copied the installation instructions from there.
The kubeflow pytorch operator has been deprecated in favor of the new training operator.
> Replace installation instructions for pytorch operator with training operator

- charts/flyte-binary/README.md
- charts/flyte-binary/values.yaml
- charts/flyte-sandbox/README.md
- charts/flyte-sandbox/values.yaml
- deployment/sandbox-binary/flyte_sandbox_binary_helm_generated.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
update endpoint. `flyte-sandbox-http` -> `flyte-binary-http`
> Update agent endpoint in the single binary

- charts/flyte-core/templates/clusterresourcesync/deployment.yaml
N/A
This change allows setting optional resource requests & limits for the cluster resource deployment
**Testing**
Modified `charts/flyte-core/values.yaml` to add a resources block and verified that running `make helm` updated the generated helm chart:
```
apiVersion: apps/v1
kind: Deployment
metadata:
name: syncresources
namespace: flyte
...
spec:
...
template:
metadata:
annotations:
configChecksum: "475154c41cdb06999025ab796aa1264fa3d235df51ac088a39c89c7ce300408"
labels:
app.kubernetes.io/name: flyteclusterresourcesync
app.kubernetes.io/instance: flyte
helm.sh/chart: flyte-v0.1.10
app.kubernetes.io/managed-by: Helm
spec:
...
serviceAccountName: flyteadmin
resources:
limits:
cpu: 250m
ephemeral-storage: 100Mi
memory: 500Mi
requests:
cpu: 10m
ephemeral-storage: 50Mi
memory: 50Mi
volumes: …
```
> Allow setting resources for cluster resource controller deployment

- charts/flyte-core/templates/agent/rbac.yaml
- deployment/sandbox/flyte_helm_generated.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
As the title, add a service account without a role for the agent. people can add annotations, and image secrets for SA by updating the helm chart value.yaml
> Add service account for agent

- flyte_local.yaml
The existing flyte_local.yaml configuration file has fallen out of date, causing issues when running single binaries. The standard process ideally looks like this:
```shell
flytectl demo start --dev
sudo make compile
flyte start --config flyte_local.yaml
```
This PR introduces necessary updates to the flyte_local.yaml configuration file.
```shell
flytectl demo start --dev
sudo make compile
flyte start --config flyte_local.yaml
pyflyte run --remote core/flyte_basics/hello_world.py my_wf
pyflyte run --remote core/flyte_basics/deck.py wf
```
Able to run the task
Able to see the deck:
Able to see the kubernetes logs:
> Fix single binary config

- rsts/deployment/configuration/general.rst
- rsts/deployment/plugins/k8s/index.rst
In the Flyte Slack community there have been multiple questions recently how timeout errors can be avoided which occur when the workers of distributed training jobs don't start at the same time due to resource constraints.
The best solution to this problem is to use a Kubernetes scheduler which supports gang scheduling. In this PR I add documentation how this can be configured.
> Doc: gang-scheduling for kubeflow training-operator

- charts/flyte-core/README.md
- charts/flyte-core/templates/admin/rbac.yaml
- charts/flyte-core/values.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_controlplane_generated.yaml
- deployment/eks/flyte_helm_dataplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_controlplane_generated.yaml
- deployment/gcp/flyte_helm_dataplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
We deploy use LimitRanges for flyte created namespaces. It would be practical if syncresources can also create this, otherwise we would need to create the rbac resources ourselves
> Add LimitRange resource permission to flyteadmin serviceaccount

- .github/workflows/single-binary.yml
- .github/workflows/tests.yml
- Makefile
- boilerplate/flyte/end2end/functional-test-config.yaml
- boilerplate/flyte/end2end/run-tests.py
- boilerplate/flyte/golang_test_targets/Makefile
- boilerplate/flyte/golang_test_targets/Readme.rst
- boilerplate/flyte/golang_test_targets/download_tooling.sh
- boilerplate/flyte/golang_test_targets/go-gen.sh
- boilerplate/flyte/golang_test_targets/goimports
- boilerplate/update.cfg
This PR:
- Updates boilerplate
- Add `golang_test_targets`
- Runs tests for single binary in CI
> Run tests in CI

- .github/workflows/stale.yml
By default stalebot only handles 30 issues at a time (as can be evidenced by its first [run](https://github.com/flyteorg/flyte/actions/runs/5957979371)). This PR bumps this limit to 500. Also, let's favor older issues before the limit is hit.
> Increase limits of stalebot

- cmd/single/start.go
- go.mod
- go.sum
https://github.com/flyteorg/flyte/issues/2975
Starting the profiler http endpoint for the single binary and exposing k8s metrics using a separate handler.
_NA_
_NA_
> Starting profiler for single binary with k8s metrics

- .github/workflows/bump-tags.yml
- .github/workflows/checks.yml
- .github/workflows/create_release.yml
- .github/workflows/helm-charts.yaml
- datacatalog/pull_request_template.md
This PR adds a github workflow to bump the patch version of all necessary git tags (as described in https://go.dev/ref/mod#vcs-version). This is necessary so that downstream golang repositories can update to specific versions of components.
In terms of the mechanics of the gh workflow, on merges to master we bump the patch version of the latest tag and we use that version create tags for each component. For example, let's say that the we're updating to version v1.9.1, this is going to create 7 tags:
- v1.9.1
- datacatalog/v1.9.1
- flyteadmin/v1.9.1
- flytecopilot/v1.9.1
- flyteplugins/v1.9.1
- flytepropeller/v1.9.1
- flytestdlib/v1.9.1
I also took the chance to improve the fork-ability of the flyte repo. I also tested these changes on a fork.
A subsequent change is going to modify the …
> Add bump git tags workflow

- datacatalog/Makefile
- flyteadmin/Makefile
- flytepropeller/Makefile
- script/generate_config_docs.sh
- script/release.sh
This PR changes the generation of manifests to use the versions of components in the monorepo.
A few things to note:
1. This process relies on the fact that changes to components trigger the creation of tags once they are merged to master. This essentially means that two consecutive releases are not supported since component tags are only generated once changes to components are merged to master. We might need to relax this constraint and assume that all merges to master produce component tags.
2. In order to generate the config docs we no longer download component binaries from releases, instead we compile them in place. 
3. The release process described in https://github.com/flyteorg/flyte/blob/master/RELEASE.md#create-a-release stays unchanged.
> [Monorepo] Update manifest using the monorepo components

- flytepropeller/pkg/controller/controller.go
- flytepropeller/pkg/controller/executors/dag_structure.go
- flytepropeller/pkg/controller/executors/execution_context.go
- flytepropeller/pkg/controller/executors/kube.go
- flytepropeller/pkg/controller/executors/node_lookup.go
- flytepropeller/pkg/controller/executors/workflow.go
- flytepropeller/pkg/controller/nodes/factory/handler_factory.go
- flytepropeller/pkg/controller/nodes/task/handler.go
- flytepropeller/pkg/controller/nodes/task/handler_test.go
- flytepropeller/pkg/controller/nodes/task/k8s/event_watcher.go
- flytepropeller/pkg/controller/nodes/task/k8s/event_watcher_test.go
- flytepropeller/pkg/controller/nodes/task/k8s/plugin_manager.go
- flytepropeller/pkg/controller/nodes/task/k8s/plugin_manager_test.go
- flytepropeller/pkg/controller/nodes/task/plugin_config.go
- flytepropeller/pkg/controller/nodes/task/plugin_config_test.go
- flytepropeller/pkg/controller/nodes/task/transformer.go
- flytepropeller/pkg/controller/workflow/executor_test.go
- rsts/deployment/index.rst
As PR title says. This PR brings flytepropeller to [v1.1.129](https://github.com/flyteorg/flytepropeller/releases/tag/v1.1.129).
> [Monorepo]  Bump flytepropeller to v1.1.129

- flyteadmin/pkg/common/service.go
- flyteadmin/pkg/server/service.go
- flyteadmin/plugins/registry.go
Extends the plugin registry with a configurable gPRC service handler hook to serve additional endpoints on the flyteadmin gRPC server.
> Add Additional gRPC service handler hook

- flyteplugins/go/tasks/plugins/k8s/kfoperators/tensorflow/tensorflow.go
> [flyteplugins] Make the TF Job Worker Spec Correct

- charts/flyte-binary/eks-production.yaml
- rsts/deployment/deployment/cloud_production.rst
- rsts/deployment/deployment/cloud_simple.rst
- rsts/deployment/deployment/index.rst
- rsts/deployment/deployment/multicluster.rst
- rsts/deployment/deployment/sandbox.rst
Closes #3973 
* Add references to tutorials in multiple places
* Updates the Multicluster setup guide
* Removes or rewrites sentences to better match current status
> Updates to deployment guides

- boilerplate/flyte/end2end/run-tests.py
> allow passing cluster pool to run-tests.py

- .github/workflows/flyteidl-release.yml
- script/release.sh
This PR adds a github workflow to publish flyteidl to PyPI and npm, those were moved from their original places in the flyteidl repo (https://github.com/flyteorg/flyteidl/blob/master/.github/workflows/pythonpublish.yaml and https://github.com/flyteorg/flyteidl/blob/master/.github/workflows/npmpublish.yaml). 
I also fixed the way we're pulling the latest tag to be used in the release. The `--version-sort` instructs `sort` to use semantic versions.
> Add gh workflow to publish flyteidl release to PyPI and npm

- flyteplugins/go/tasks/pluginmachinery/internal/webapi/monitor_test.go
- flytestdlib/cache/auto_refresh.go
- flytestdlib/cache/auto_refresh_test.go
- rsts/deployment/index.rst
I found that Propeller keeps sending the request to the agent even workflow is done.
The work queue only has unique items, so we add `itemID` to it. The workers won't process the item again after the task is done. 
Before:
||enqueueBatches| workqueue | sync (10 workers) |
|----|----|-----|----|
| t1 | obj(1) | obj(1) |  |
| t2 |  |  |  |
| t3 | obj(2)  |  obj(1), obj(2) |  |
| t4 |  |  |  |
| t5 | obj(1) | obj(1), obj(2), obj(1) |  |
| t6 |  |  | obj(1), obj(2), obj(1) |
After:
||enqueueBatches| workqueue | sync (10 workers) |
|----|----|-----|----|
| t1 | 1 | 1 |  |
| t2 |  |  |  |
| t3 | 2  |  1, 2 |  |
| t4 |  |  |  |
| t5 | 1 | 1, 2 |  |
| t6 |  |  | 1, 2 |
100 workflows, each has 100 tasks.
Before:
After:
^^^
_NA_
_NA_
> Update the item only if it exists in the cache

- flyteidl/clients/go/admin/auth_interceptor.go
- flyteidl/clients/go/admin/client.go
@andrewwdye noticed that the newly introduced proxy authorization in the admin client breaks propeller, see https://github.com/flyteorg/flyte/pull/4216#event-10638102477.
I ran flytepropeller locally in a debugger (with the flyte-core helm chart deployed in the cluster and flyteadmin and datacatalog port-forwarded).
With the debugger, I confirmed that [this](https://github.com/flyteorg/flyte/blob/68c055b7b51eebc4cf009b5caf488026328cfcc0/flyteidl/clients/go/admin/client.go#L157) if statement which adds proxy authorization is hit even if no proxy command is provided in the platform config.
The reason is that I check for `cfg.ProxyCommand != nil` but the default value of proxy command is [empty string slice  ](https://github.com/flyteorg/flyte/blob/68c055b7b51eebc4cf009b5caf488026328cfcc0/fly …
> Fix: Prevent unintended use of proxy authorization when no command is provided

- rfc/system/3749-sane-overridable-defaults.md
Fixes typo discusison -> discussion
> docs: fix typo in rfc/system/3749-sane-overridable-defaults.md

- kustomize/README.md
Fixes typo indiviudal -> individual
> docs: fix typo in ./kustomize/README.md

- flyteplugins/go/tasks/plugins/webapi/databricks/plugin.go
The databricks plugin does not check for all possible terminal states as returned from the Databricks Jobs API. As a result, if the Databricks jobs API returns a state which the plugin is not written to recognise, the plugin will think that the job is still in a running phase.
https://github.com/flyteorg/flyte/issues/4243
Transition task status to `Failure` if the lifeCycleState is `SKIPPED` or `INTERNAL_ERROR`
> Fix databricks plugin

- flytestdlib/profutils/server.go
Start metrics server in a separate go routine to prevent this [errGroup.Wait()](https://github.com/flyteorg/flyte/blob/master/cmd/single/start.go#L173) from hanging.
As part of this investigation we realized that our usage of `errGroup` is not correct, since we mix them with panics and logrus `Fatalf` (which exit the process and set its status to 1). I opened https://github.com/flyteorg/flyte/issues/4255 to track this.
> Start metrics server in a goroutine

- .github/workflows/checks.yml
- .github/workflows/codespell.yml
- .github/workflows/flyteidl-checks.yml
- .github/workflows/helm-charts.yaml
- .github/workflows/sandbox.yml
- .github/workflows/single-binary.yml
- .github/workflows/tests.yml
- datacatalog/.github/workflows/checks.yml
- flyteadmin/.github/workflows/checks.yml
- flytecopilot/.github/workflows/checks.yml
- flyteidl/.github/workflows/verification.yml
- flytepropeller/.github/workflows/checks.yml
- flytepropeller/.github/workflows/codeql-analysis.yml
as title, always run the latest workflow in the PR.
https://stackoverflow.com/a/72408109/9574775
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
_How did you fix the bug, make the feature etc. Link to any design docs etc_
https://github.com/flyteorg/flyte/issues/<number>
_NA_
> Cancel a currently running workflow from the same PR when a new workflow is triggered

- flyteadmin/auth/authzserver/metadata_provider_test.go
> Fix broken unit tests

- cmd/single/start.go
- flytestdlib/profutils/server.go
This PR fixes the initialization of the profiling server.
> Start the profiling server properly

- .github/workflows/flyteidl-release.yml
This PR separates the jobs that publish flyteidl to PyPI and npm into 2 jobs and it also fixes the generation of the python package.
> Fix flyteidl release

- flyteadmin/pkg/config/config.go
- flyteadmin/pkg/config/serverconfig_flags.go
- flyteadmin/pkg/config/serverconfig_flags_test.go
- flyteadmin/pkg/server/service.go
https://github.com/flyteorg/flyte/issues/4214
See PR title, the recently added admin config option doesn't conform to the existing flytepropeller one
> Rename grpc histogram metrics flag for consistency with flytepropeller

- flyteidl/clients/go/admin/pkce/auth_flow_orchestrator.go
- flyteidl/clients/go/admin/pkce/auth_flow_orchestrator_test.go
Previous PR introduced authentication with proxy http Client but it added a hard dependency to fetch this from the context .
This causes regression in cases the context is not set with this object.
Current change makes it backward compatible by using the default http client in case the context is not set with it.
Tested this change locally by pulling this commit as saw authentication working fine in the broken environments
> Make fetching HttpClient optional from context in PKCE auth flow

- charts/flyte-core/templates/admin/configmap.yaml
- flyteadmin/pkg/async/notifications/factory.go
Fixes #3070
This change
* Restores population of the `NotificationConfig.Region` field from the flyte-core configmap template. This was removed in #4055. While the config struct field has a comment indicating deprecated, the alternative `NotificationConfig.AWSConfig.Region` is not consumed everywhere yet. It is not safe to stop populating this field yet, and is in fact required for all existing versions of flyteadmin to use NotificationsProcessor and Emailer. The deprecated field is only populated in the absence of the `aws` block.
* Updates flyteadmin to consume `NotificationConfig.AWSConfig.Region` and only fallback to the deprecated field if necessary.
I ran through a couple EKS and GCP helm templating scenarios to verify the fix correctly populates the deprecated region field if used …
> Restore deprecated NotificationsConfig.Region field

- rsts/community/contribute.rst
https://flyte--4257.org.readthedocs.build/en/4257/community/contribute.html
https://github.com/flyteorg/flyte/issues/4188
- Update the "hello world" example in flytesnacks
- Update the setup guide to reflect the Monorepo structure.
- Update the flytekit install plugins guideline, since flytekitplugins doesn't support lazy import.
@Yicheng-Lu-llll, @samhita-alla, @pingsutw please take a look, thanks a lot!
> [Docs] Update Development Environment Setup Guide for MonoRepo

- boilerplate/flyte/golang_test_targets/Makefile
- datacatalog/boilerplate/flyte/golang_test_targets/Makefile
- flyteadmin/boilerplate/flyte/golang_test_targets/Makefile
- flytecopilot/boilerplate/flyte/golang_test_targets/Makefile
- flyteidl/boilerplate/flyte/golang_test_targets/Makefile
- flyteplugins/boilerplate/flyte/golang_test_targets/Makefile
- flytepropeller/boilerplate/flyte/golang_test_targets/Makefile
- flytestdlib/boilerplate/flyte/golang_test_targets/Makefile
Right now, users don't need to type `make lint; make goimports` to lint the golang files.
They just need to type `make lint` only.
You can see the line here.
`GL_DEBUG=linters_output,env golangci-lint run --fix --deadline=5m --exclude deprecated -v`
> Support `make lint` auto fix `goimport packages`  in all flyte components

- Dockerfile
Use a newer version of debian as base image. This brings a newer version of openssl and other updates:
```
❯ docker run --rm -it debian:bullseye-slim bash -c "apt-get update && apt-get install --no-install-recommends --yes ca-certificates tini && openssl version" | grep OpenSSL
OpenSSL 1.1.1w  11 Sep 2023
❯ docker run --rm -it debian:bookworm-slim bash -c "apt-get update && apt-get install --no-install-recommends --yes ca-certificates tini && openssl version" | grep OpenSSL
OpenSSL 3.0.11 19 Sep 2023 (Library: OpenSSL 3.0.11 19 Sep 2023)
```
> Use debian bookworm as single binary base image 

- charts/flyte-core/templates/datacatalog/service.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_controlplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_controlplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
<br>
- Issue asks to remove the following code:
```
name: grpc-2
port: 8089
protocol: TCP
targetPort: 8089
```
<br>
- **service.yaml** (charts/flyte-core/templates/datacatalog/service.yaml)
<br> 
<br>
> fix: remove unused setting in deployment charts

- rsts/concepts/tasks.rst
Adds documentation for RFC https://github.com/flyteorg/flyte/pull/3902.
Not to be merged before https://github.com/flyteorg/flyte/pull/3902 and https://github.com/flyteorg/flytepropeller/pull/596 are merged.
> Document simplified retry behaviour introduced in #3902

- flytepropeller/pkg/controller/nodes/task/handler.go
- flytepropeller/pkg/controller/nodes/task/handler_test.go
_NA_
Currently, if the plugin state has already been observed we immediately return without incrementing `parallelism` or marking the task as "dirty", indicating that it has already been processed this round. This means that, in scenarios where a task is the downstream dependency of multiple nodes, tasks may be unnecessarily evaluated multiple times within a single round. More seriously, if the task state has no changed (ex. in same phase as previous round) then additional tasks will be scheduled to satisfy the parallelism. This means that, effectively `max_parallelism` settings may be ignored.
In this PR we correctly increment `parallelism` if the state has already been seen and mark the task node as "dirty" to indicate that it should not be evaluated again this round.
_NA_
_NA_
> Not revisiting task nodes and correctly incrementing parallelism

- flyteplugins/tests/end_to_end.go
Closes https://github.com/flyteorg/flyte/issues/4343
Remove duplicated mock without `Run` that produces that the output file is not saved to the inmemory store.
```
time="2023-11-01T10:34:44+01:00" level=error msg="Failed to read from the raw store [fake://bucket/prefix/2g6/outputs.pb] Error: file does not exist"
Error:      	Received unexpected error:
file does not exist
path:fake://bucket/prefix/2g6/outputs.pb
github.com/flyteorg/flyte/flytestdlib/storage.DefaultProtobufStore.ReadProtobuf
/Users/andresg/go/pkg/mod/github.com/flyteorg/flyte/flytestdlib@v1.10.0/storage/protobuf_store.go:39
github.com/flyteorg/flyte/flyteplugins/tests.RunPluginEndToEndTest
/Users/andresg/go/pkg/mod/github.com/flyteorg/flyte/flyteplugins@v1.10.0/tests/end_to_end.go:261
....
```
> Fix RunPluginEndToEndTest util

- .github/workflows/stale.yml
This PR disables prevents stalebot from closing issues automatically. We're going to implement a step where the core maintainers engage with stale issues instead.
As per the stalebot [docs](https://github.com/actions/stale#days-before-close), any negative number indicates that stalebot does not close issues/PRs.
> Do not automatically close stale issues

- charts/flyte-core/templates/common/ingress.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_controlplane_generated.yaml
- deployment/eks/flyte_helm_dataplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_controlplane_generated.yaml
- deployment/gcp/flyte_helm_dataplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
Flyte can be configured to use TLS between the ingress (or rather load balancer) and the flyteadmin backend.
*This is required for instance in GKE clusters when using the GCE ingress controller (instead of nginx) since gRPC requires http2 and http2 between GCE load balancers and backends in GKE clusters requires TLS ([source](https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-http2#:~:text=Note%3A%20To%20ensure%20the%20load%20balancer%20can%20make%20a%20correct%20HTTP2%20request%20to%20your%20backend%2C%20your%20backend%20must%20be%20configured%20with%20SSL.)):*
> Note: To ensure the load balancer can make a correct HTTP2 request to your backend, your backend must be configured with SSL.
Whether flyteadmin uses TLS (and with which certificate) is controlled in the helm values …
> Fix: Set flyteadmin gRPC port to 80 in ingress if using TLS between load balancer and backend

- flyteplugins/go/tasks/plugins/webapi/databricks/integration_test.go
- flyteplugins/go/tasks/plugins/webapi/databricks/plugin.go
- flyteplugins/go/tasks/plugins/webapi/databricks/plugin_test.go
- Fix `Delete` function, post request `data` format error
- Add `Message` in TaskInfo when `Pending` State
- Fix the bug in `lifeCycleState`. (`SKIPPED` doesn't have `resultState`, but `TERMINATING` does)
https://docs.databricks.com/en/workflows/jobs/jobs-2.0-api.html#runresultstate
- Currently, we only support Databricks API 2.0 and only the `new_cluster` key in the Databricks config.
However, some users want to use Databricks API 2.1 and want to use `existing_cluster_id` in the databricks config.
Here's the screenshot from the official documentation.
you can find the difference between `existing_cluster_id` and `new_cluster`
https://docs.databricks.com/en/workflows/jobs/jobs-2.0-api.html#request-structure
Config yaml in dev mode
```yaml
tasks:
task-plugins:
enabled-plugins:
- container …
```
> Support Databricks WebAPI 2.1 version and Support `existing_cluster_id` and `new_cluster` options to create a Job

- flytestdlib/storage/stow_store.go
- flytestdlib/storage/stow_store_test.go
Closes #4368
Compare limit at byte level to avoid accuracy loss when converting to MB.
NA
NA
> Fix read raw limit

- charts/flyte-binary/eks-starter.yaml
- charts/flyte-binary/templates/deployment.yaml
- deployment/sandbox-binary/flyte_sandbox_binary_helm_generated.yaml
- script/generate_helm.sh
- `eks-starter.yaml` is missing a database username - probably a better practice to be explicit about it. Also, since it's meant for less advanced users, it will help them remember to provide this information.
- `deployment.yaml` template - readiness and liveness probes had the wrong port (and probably missing initial delay)
> minor fix to eks-starter.yaml

- flyteplugins/go/tasks/pluginmachinery/flytek8s/pod_helper.go
- flyteplugins/go/tasks/pluginmachinery/flytek8s/pod_helper_test.go
- flyteplugins/go/tasks/plugins/k8s/pod/plugin.go
- flyteplugins/go/tasks/plugins/k8s/pod/sidecar_test.go
fixes https://github.com/flyteorg/flyte/issues/4332
If the primary container status is not found we check if the pod definition contains the containers name. In this scenario the container status has not yet been reported, but will be when it begins executing.
_NA_
_NA_
> Reporting running if the primary container status is not yet reported

- flyteplugins/go/tasks/plugins/array/core/state.go
- flyteplugins/go/tasks/plugins/array/core/state_test.go
fixes https://github.com/flyteorg/flyte/issues/4331
Check if any subtasks are in phase retryable failure before transitioning to succeeded.
_NA_
_NA_
> completing retries even if minSuccesses are achieved

- flyteadmin/auth/token.go
following some confusion in OSS slack.
> Add comment to auth scope

- rsts/deployment/configuration/general.rst
Closes #4372 
Updates the cluster resources config to work with both `uctl` and `flytectl`.
Not applicable
None
> Update order of cluster resources config to work with both uctl and flytectl

- flyteadmin/pkg/manager/impl/task_execution_manager.go
- flytepropeller/pkg/controller/nodes/array/event_recorder.go
_NA_
Setting `PluginIdentifier` and Input and Output values.
_NA_
_NA_
> Update metadata in ArrayNode TaskExecutionEvents

- flyteplugins/go/tasks/plugins/k8s/ray/ray.go
Ray operator sets a few different possible transient statuses as well as different cluster deployment statuses. The plugin doesn't handle all of them and silently attempts to make an illegal state transition instead of erroring. This change does two things:
> Handle all ray job statuses

- flyteplugins/go/tasks/logs/config.go
- flyteplugins/go/tasks/logs/logging_utils.go
- flyteplugins/go/tasks/logs/logging_utils_test.go
- flyteplugins/go/tasks/pluginmachinery/tasklog/plugin.go
- flyteplugins/go/tasks/pluginmachinery/tasklog/template.go
- flyteplugins/go/tasks/pluginmachinery/tasklog/template_test.go
> Refactor task logs framework

- flyteadmin/pkg/errors/errors.go
- flyteadmin/pkg/errors/errors_test.go
- flyteadmin/pkg/executioncluster/impl/random_cluster_selector.go
- flyteadmin/pkg/manager/impl/execution_manager.go
- flyteadmin/pkg/manager/impl/executions/quality_of_service.go
- flyteadmin/pkg/manager/impl/executions/queues.go
- flyteadmin/pkg/manager/impl/util/resources.go
- flyteadmin/pkg/manager/impl/util/shared.go
Closes #4387
Do not issue warning log when the error is NotFound because that is in most cases intended.
> Silence NotFound when get task resource

- flyteplugins/go/tasks/plugins/webapi/athena/plugin.go
- flyteplugins/go/tasks/plugins/webapi/athena/plugin_test.go
N/A
Adds support for the Log Links for AWS gov environments instead of hard-coding to commercial
> adding consoleUrl parameterization based on partition

- flyteplugins/go/tasks/plugins/k8s/ray/ray.go
- flyteplugins/go/tasks/plugins/k8s/ray/ray_test.go
Adds support for `{{ .rayClusterName }}` and `{{ .rayJobID }}` template variables in Ray plugin log template links.
> Add more context for ray log template links

- flyteartifacts/Makefile
> add dummy comment

- charts/flyte-binary/README.md
- charts/flyte-binary/templates/_helpers.tpl
- charts/flyte-binary/templates/configmap.yaml
- charts/flyte-binary/values.yaml
1. Update configmap and helper to support Azure cloud storage.
2. Update values with sample config and regen helm doc readme.
- [X ] I updated the documentation accordingly.
- [X ] All new and existing tests passed.
- [X ] All commits are signed-off.
This will allow users of the `flyte-binary` chart to configure Azure storage accounts. The stow version bump is needed in order to use [Workload Identity](https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview?tabs=dotnet).
This PR does not include an implementation of [RemoteURLInterface](https://github.com/flyteorg/flyte/blob/master/flyteadmin/pkg/data/implementations/aws_remote_url.go), which would be required before using signed URLs in Azure. A potential fix is being discussed in …
> Support Azure Cloud Provider (via Stow)

- flyteplugins/go/tasks/plugins/k8s/kfoperators/tensorflow/tensorflow.go
- flyteplugins/go/tasks/plugins/k8s/kfoperators/tensorflow/tensorflow_test.go
- flyteplugins/go/tasks/plugins/webapi/athena/plugin_test.go
- Add a function `getReplicasCount` to give replica pointer with default value.
```python
image_spec = ImageSpec(
packages=["flytekit",
"flytekitplugins-kftensorflow",
"tensorflow"],
registry="localhost:30000")
task_config = TfJob(
worker=Worker(replicas=1),
chief=Chief(replicas=0),
ps=PS(replicas=0),
evaluator=Evaluator(replicas=0),
)
@task(
task_config=task_config,
cache=True,
requests=Resources(cpu="1"),
cache_version="1",
container_image=image_spec,
)
def my_tensorflow_task(x: int = 10, y: str = "abc") -> int:
return x
if __name__ == "__main__":
print(my_tensorflow_task(x=10, y="hello"))
```
> Fix Kubeflow TF Operator `GetTaskPhase` Bug

- flyteadmin/run.sh
- flyteadmin/scheduler/core/gocron_scheduler.go
- flyteadmin/scheduler/core/gocron_scheduler_test.go
https://github.com/flyteorg/flyte/issues/4285
All kudos to @leonlnj who discovered this bug in Gojek production deployment and helped debug this nasty loop variable issue which caused unnecessary production issue where schedules ran with incorrect times
Overall the issue that was observed was when Gojek redeployed there scheduler, scheduler ran its regular catchup routine to recover from the missed schedule time during the redeploy and found schedules it needed to trigger.
This is well tested behavior in the fleet and we never encountered any issues with it.
But in case of Gojek, it mysteriously ran the schedules which shouldn't have been run and also ran with incorrect catcup from time.
There is much detail in the attached issue. 
To summarize, 
* The lastExecTime for each active …
> Fix the loop variable scheduler issue

- .github/workflows/generate_flyte_manifest.yml
The `needs` step was not removed from the `flyte_generate_manifest` gh workflow in https://github.com/flyteorg/flyte/pull/4304. This PR removes it.
> Remove 'needs' from generate_flyte_manifest

- .github/workflows/create_release.yml
In https://github.com/flyteorg/flyte/pull/4304 we modified the way all version were fetched from the values file, however that's not correct in the case of flytecopilot.  In this PR we go back to the correct way of fetching the version of flytecopilot from the values file.
> Modify how flytecopilot version is parsed from values file

- rsts/deployment/deployment/sandbox.rst
Adds notes on updating and reloading Flyte sandbox cluster configuration.
> Add note on updating sandbox cluster configuration

- .github/workflows/create_release.yml
We introduced a way to skip certain tags in https://github.com/flyteorg/flyte/pull/4497 but in order to use that we need a newer version of goreleaser/goreleaser-action@v5
> Bump version of goreleaser gh action to v5

- docs/_ext/import_projects.py
This PR fixes a breakage in the monodocs build introduced by https://github.com/flyteorg/flytekit/commit/f0d4f1357a770b66dc8344ab97b8b41d19eca9df, where a `_version.py` file is being created in the package build process.
> manually create flytekit/_version.py file in docs build

- flyteadmin/cmd/entrypoints/serve.go
- flyteadmin/pkg/manager/impl/workflow_manager.go
- flyteadmin/pkg/manager/impl/workflow_manager_test.go
https://github.com/flyteorg/flyte/issues/4565
Invalid workflow specs passed to CreateWorkflow calls currently return Internal grpc status response codes and are erroneously treated as server rather than user errors.
As far as I could tell, the [compiler](https://github.com/flyteorg/flyte/blob/d03a0bc1c0e8f8a5fa0d83407df3a87827359079/flytepropeller/pkg/compiler/workflow_compiler.go) propagates compiler errors that only surface due to invalid workflow definitions
Updates workflow compilation handling to return a more accurate response code.
Added unit tests.
> Return InvalidArgument for workflow compilation failures in CreateWorkflow

- docs/integrations.md
Currently, https://github.com/flyteorg/flytesnacks/pull/1314 is failing the monodocs build step because it adds a new plugin page that has not been added to the integrations TOC.
Adds the flyin plugin index link to the integrations docs config page.
https://github.com/flyteorg/flytesnacks/pull/1314
TBD
> Add flyin plugin to monodocs integrations page

- flyteadmin/pkg/manager/impl/testutils/mock_requests.go
- flyteadmin/pkg/manager/impl/validation/launch_plan_validator_test.go
- flyteadmin/pkg/repositories/transformers/launch_plan.go
- flyteadmin/pkg/repositories/transformers/launch_plan_test.go
Create schedule launchplan is using deprecated field to determine if schedule type is CRON and saving it in the DB
This causes the list launchplan with filter for CRON type schedule returns null 
This fixes the logic of saving all new scheduled launchplans.
We are not planning to support this for older scheduled launchplans and hence no migration script for it.
Tested this on an internal tenant by registering the latest version of the examples
*  flytectl register examples  --project flytesnacks  --domain development 
* flytectl update launchplan my_cron_scheduled_lp  --project flytesnacks --domain development --version v0.3.248   --activate
* flytectl update launchplan my_fixed_rate_lp   --project flytesnacks --domain development  --version v0.3.248   --activate
Verified the result  of …
> Use updated cronSchedule in CreateLaunchPlanModel

- flytepropeller/pkg/controller/nodes/executor.go
_NA_
Flytes templating and flytekit both rely on this zero length file to indicate there are no inputs.
This PR re-introduces writing a zero length input file if the node has no inputs.
Flytesnacks workflows.
_NA_
_NA_
- [this PR](https://github.com/flyteorg/flyte/pull/4535) introduced the issue.
_NA_
> Writing zero length inputs

- .github/workflows/single-binary.yml
Since single-binary is a fundamental part of the dev experience, let's get more coverage by running functional tests on every PR.
Run single-binary functional tests on all PRs.
> Run single-binary gh workflows on all PRs

- docs/_ext/import_projects.py
- docs/conf.py
This PR elegantly handles the case when an external repo (flytekit, flytesnacks, flytectl) does not have tags due to a cloning a copy of the repo with a depth of 0. This fixes a docs build issue caused by the fact that github actions `checkout` will fetch the latest commit (since `fetch-depth: 0` by default), see: https://github.com/flyteorg/flytesnacks/actions/runs/7204216790/job/19625299915?pr=1315
> monodocs - gracefully handle case when external repo doesn't contain tags: use current commit

- docs/_ext/import_projects.py
Fix a minor issue: git commit object should be converted to string in `import_project` sphinx extension.
> convert commit to string

- flyteplugins/go/tasks/pluginmachinery/core/phase.go
- flyteplugins/go/tasks/plugins/array/core/state.go
- flyteplugins/go/tasks/plugins/array/k8s/executor.go
- flyteplugins/go/tasks/plugins/array/k8s/management.go
- flytepropeller/pkg/controller/nodes/task/transformer.go
Updating to:
- enable use of the `Abort` phase directly in `ExternalResourceInfo` rather than a bool flag
- Remove failing w/ cleanup, because we only need to attempt abort once. While the workflow is running this happens with the `AbortSubTask` `ArrayNodePhase` and otherwise this is attempted during `Abort`
- Removed eventing as `Abort` during finalize. This function is used to handle finalizer cleanup and resource deletion (if requested), so tasks should not be phase transitioned.
> using Abort phase and cleaning up best-effort

- docs/.readthedocs.yaml
- docs/build-environment.yaml
- monodocs-environment.lock.yaml
- monodocs-environment.yaml
This PR changes the monodocs readthedocs config so that it uses the customizeable readthedocs build steps instead of the experimental `build.commands` config key. This is because there are some issues with correctly rendering the readthedocs flyout menu: https://github.com/readthedocs/readthedocs.org/issues/10955
Preview: https://flyte-next.readthedocs.io/en/monodocs-readthedocs-config/
vs.
https://flyte-next.readthedocs.io/en/latest/ (readthedocs inserted dropdown is missing)
> Don't use experimental readthedocs build.commands config

- flytepropeller/events/event_recorder.go
_NA_
This `MaxErrorMessageLength` value is now used to truncate `ArrayNode` errors, since it was actually 100MB this resulted in potentially large FlyteWorkflow CRs.
Correctly computing the 100KB to B conversion.
_NA_
_NA_
_NA_
_NA_
_NA_
> Fixing 100 kilobyte max error message size

- flytepropeller/pkg/controller/nodes/array/event_recorder.go
- flytepropeller/pkg/controller/nodes/array/handler.go
- flytepropeller/pkg/controller/nodes/array/handler_test.go
- flytepropeller/pkg/controller/nodes/array/mocks/array_event_recorder.go
_NA_
The external resource ID may be used in other locations to link to the executing entity. If this is incorrect, then it is impossible to determine the actual k8s resource.
Correcty setting the ExternalResourceInfo ExternalID field to the Pod name for each subtask.
local / cloud / etc
_NA_
_NA_
> Updating ArrayNode ExternalResourceInfo ID

- docs/_ext/import_projects.py
This PR updates the `import_projects` sphinx extension used by the monodocs build. It filters out repo tags that don't match a stable release.
> monodocs: do not use beta releases when importing projects

- flyteadmin/dataproxy/service.go
- flyteadmin/scheduler/executor/executor_impl.go
- flyteadmin/tests/bootstrap.go
- flyteadmin/tests/execution_test.go
- flytecopilot/cmd/root.go
- flyteidl/clients/go/admin/pkce/auth_flow_orchestrator.go
- flyteplugins/go/tasks/pluginmachinery/ioutils/paths.go
- flyteplugins/go/tasks/plugins/array/awsbatch/jobs_store.go
- flyteplugins/go/tasks/plugins/array/awsbatch/monitor.go
- flyteplugins/go/tasks/plugins/webapi/athena/plugin.go
- flyteplugins/go/tasks/plugins/webapi/bigquery/plugin.go
- flyteplugins/go/tasks/plugins/webapi/databricks/plugin.go
- flyteplugins/go/tasks/plugins/webapi/snowflake/plugin.go
- flytepropeller/cmd/kubectl-flyte/cmd/root.go
- flytepropeller/pkg/controller/nodes/executor.go
- flytepropeller/pkg/controller/nodes/subworkflow/launchplan/admin.go
- flytepropeller/pkg/controller/nodes/task/backoff/handler.go
- flytestdlib/random/weighted_random_list.go
- flytestdlib/storage/protobuf_store.go
Fixed a bunch of places where we weren't using the correct logger function, i.e., `logger.Error(...)` instead of `logger.Errorf(...)`
Before
```
❯ rg "logger.(Fatal|Error|Info|Warn|Debug)\(" -g '!flyte' | rg "%"
flytepropeller/pkg/controller/nodes/executor.go:				logger.Warn(ctx, "failed to save recovered checkpoint uri for [%+v]: [%+v]",
flytepropeller/pkg/controller/nodes/task/backoff/handler.go:	logger.Debug(ctx, "BackOff params [BackOffBaseSecond: %v] [BackOffExponent: %v] [MaxBackOffDuration: %v]",
flytepropeller/pkg/controller/nodes/subworkflow/launchplan/admin.go:		logger.Info(ctx, "Failed to add ExecID [%v] to auto refresh cache", executionID)
flytepropeller/cmd/kubectl-flyte/cmd/root.go:		logger.Error(context.TODO(), "Error in initializing: %v", err) …
```
> Use logger with formatter

- docs/deployment/agents/bigquery.rst
- docs/deployment/agents/databricks.rst
- docs/deployment/agents/index.md
- docs/deployment/agents/mmcloud.rst
- docs/deployment/plugins/webapi/snowflake.rst
This PR reapplies docs changes made to the old docs after the monodocs branch was created, specifically, the changes in #4008.
See #4008 -- this PR adds the Databricks agent doc, plus other changes from that PR, slightly modified to fit the new docs structure.
TBD
#4008 
https://flyte--4751.org.readthedocs.build/en/4751/flytesnacks/examples/databricks_plugin/index.html
> [Docs] Reapply Databricks agent docs changes from #4008

- flyteplugins/go/tasks/pluginmachinery/k8s/client.go
- flyteplugins/go/tasks/plugins/k8s/kfoperators/common/common_operator_test.go
NA
`TestGetLogsTemplateUri` would fail with error:
```
common_operator_test.go:216:
Error Trace:    /Users/eduardo/repos/flyte-copy/flyteplugins/go/tasks/plugins/k8s/kfoperators/common/common_operator_test.go:216
Error:          Not equal:
expected: "https://console.cloud.google.com/logs/query;query=resource.labels.pod_name=test-worker-0&timestamp>2022-01-01T12:00:00Z"
actual  : "https://console.cloud.google.com/logs/query;query=resource.labels.pod_name=test-worker-0&timestamp>2022-01-01T04:00:00-08:00"
Diff:
--- Expected
+++ Actual
@@ -1 +1 @@
-https://console.cloud.google.com/logs/query;query=resource.labels.pod_name=test-worker-0&timestamp>2022-01-01T12:00:00Z
+https://console.cloud.google.com/logs/query;query=resource.labels.pod_name=test-worker-0&timestamp>2022-01-01T04:00:00-08:00 …
```
> Fix test get logs template uri test

- docs/deployment/agents/index.md
- docs/deployment/agents/mmcloud.rst
I introduced a few small formatting issues in #4008; this PR fixes them.
* Agents index page - fix link to Databricks Agent doc
* MMCloud Agent page - fix formatting of last line 
#4751 
https://flyte--4758.org.readthedocs.build/en/4758/deployment/agents/index.html
https://flyte--4758.org.readthedocs.build/en/4758/deployment/agents/mmcloud.html#upgrade-the-deployment
> Small formatting fixes for Databrick agents docs

- flyteadmin/auth/handler_utils.go
- flyteadmin/auth/handler_utils_test.go
- flyteadmin/auth/handlers.go
Best practices recommend for not allowing open redirect URIs upon log-in, see https://developers.google.com/search/blog/2009/01/open-redirect-urls-is-your-site-being
This change uses flyteadmin's configured authorized URIs (for which flyteadmin is exposed and accessible) to validate redirect URIs
Tested on a local deployment. Tried with `/login?redirect_url=http://www.google.com` which now fails and with a valid redirect to `<flyteadmin>/console` which succeeded.
> Guard against open redirect URL parameters in login

- flytepropeller/pkg/controller/handler.go
- flytepropeller/pkg/controller/handler_test.go
_https://github.com/flyteorg/flyte/issues/4349_
A user pointed out that they had workflows stuck indefinitely in a update loop with updates failing to write to etcd.
This can happen when:
- updating the mutated workflow fails w/ ErrWorkflowToLarge propeller falls back to [updating the phase of the pre-mutated wf to failing ](https://github.com/flyteorg/flyte/blob/ace09677050eb6fd8cc8b712c9282019e1052439/flytepropeller/pkg/controller/handler.go#L388)such that the wf can transition to failing on the next loop
- on the next loop, [HandleFlyteWorkflow](https://github.com/flyteorg/flyte/blob/ace09677050eb6fd8cc8b712c9282019e1052439/flytepropeller/pkg/controller/handler.go#L142) will then transition/update the wf to WorkflowPhaseFailed. This doesn't matter if updating the CRD w/ the mutated …
> [BUG] Handle Potential Indefinite Propeller Update Loops

- flytepropeller/pkg/controller/nodes/executor.go
- flytepropeller/pkg/controller/nodes/subworkflow/subworkflow.go
- flytepropeller/pkg/controller/nodes/transformers.go
_https://github.com/flyteorg/flyte/issues/4087_
_https://github.com/flyteorg/flyte/issues/4765_
- When a subworkflow's task fails due to reaching node-active-deadline, the workflow does not fail. The workflow continues to run after the timed out task gets aborted and getting set to "UNKNOWN" state
- When a task time's out due to reaching node-active-deadline, the task's status gets set to "UNKNOWN"
- Have subworkflows handle TimedOut state 
- Transform EPhaseTimedout -> NodeExecution_TIMED_OUT when creating node execution events
Ran a couple workflows. Would be a decent effort to add unit testing - can add if needed.
Test subworkflow timeout propagation (will hit node-active-deadline on retry)
```
@task(
timeout=timedelta(seconds=10),
retries=1,
)
def demo_task():
time.sleep(3000)
@task …
```
> [BUG] subworkflow timeout propagation

- docs/index.md
- docs/introduction.md
Left navigation had repeated items in it
Remove redundant items in left nav
Local build of docs validated
> Fix repeated items in left nav

- docs/concepts/data_management.rst
Re-applies the change in https://github.com/flyteorg/flyte/pull/4518. I opened this new PR for this change since I was unable to fast forward or rebase the branch in https://github.com/flyteorg/flyte/pull/4547
The change in #4518 was made after the monodocs branch was created, so we need to bring that change over now that the monodocs PR has been merged.
Removes broken link from "[Bringing in Your Own Datastores for Raw Data](https://docs.flyte.org/en/latest/concepts/data_management.html#bringing-in-your-own-datastores-for-raw-data)" section of  "[Understand How Flyte Handles Data](https://docs.flyte.org/en/latest/concepts/data_management.html)" docs page.
#4518 
#4547 
https://flyte--4757.org.readthedocs.build/en/4757/concepts/data_management.html#bringing-in-your-own-datastores-for-raw-d …
> [Docs] Remove broken link from Understand How Flyte Handles Data page (for new monodocs site) (second attempt)

- charts/flyte-core/README.md
- charts/flyte-core/templates/_helpers.tpl
- charts/flyte-core/templates/admin/deployment.yaml
- charts/flyte-core/templates/clusterresourcesync/deployment.yaml
- charts/flyte-core/templates/console/deployment.yaml
- charts/flyte-core/templates/datacatalog/deployment.yaml
- charts/flyte-core/templates/flytescheduler/deployment.yaml
- charts/flyte-core/templates/propeller/deployment.yaml
- charts/flyte-core/templates/propeller/webhook.yaml
- charts/flyte-core/values.yaml
- charts/flyteagent/README.md
- charts/flyteagent/templates/_helpers.tpl
- charts/flyteagent/templates/agent/deployment.yaml
- charts/flyteagent/values.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_controlplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_controlplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
Hopefully this isn't too controversial a change. To deploy in our environments, we've standardized on the use of `podAnnotations`, `podLabels` and `podEnv` helm values. Globally, this allows for setting values across all deployment, statefulset and daemonset resources.
Flyte already has `podAnnotations`, but not `podLabels` or `podEnv`. This PR adds both to `flyte-core`.
Of not, `flyteadmin` has a `env: []` value set already, but it's the only one. I didn't want to break anything so left it as-is. Ideally I think  that would become `podEnv: {}` and would render in the same way as the other charts.
`make helm` was used locally to generate charts / docs. I set values explicitly in the `values.yaml` to verify correct rendering
i.e.
```helm …
```
> Fix webhook typo, add podLabels, add podEnv to flyte-core Helm chart

- flyteidl/setup.py
https://github.com/flyteorg/flyte/issues/4771
Close #4771 
Currently the flyteidl [Python library does not have a license specified](https://pypi.org/project/flyteidl/) in the metadata. Whilst the license is specified for the repository, specifying it for the library is useful for license checks.
Specify the license in the flyteidl setup.py
N/A
> feat: add apache 2.0 license to python flyteidl

- flyteplugins/go/tasks/plugins/array/k8s/executor.go
- flyteplugins/go/tasks/plugins/array/k8s/management.go
- flyteplugins/go/tasks/plugins/array/k8s/management_test.go
_NA_
In maptask, if any subtasks are in the `PhaseWaitingForResources` phase then the entire maptask task [transitions to that phase](https://github.com/flyteorg/flyte/blob/master/flyteplugins/go/tasks/plugins/array/core/state.go#L276-L279). The issue is that the `k8s-array` plugin uses a transition through `PhaseLaunch` to get back to `PhaseCheckingSubtaskExecutions` [here](https://github.com/flyteorg/flyte/blob/master/flyteplugins/go/tasks/plugins/array/k8s/executor.go#L106-L114). This causes events to be sent to flyteadmin to satisfy the phase update. With [this commit](https://github.com/flyteorg/flyte/commit/67e65c7a5f6f0dc394186f7a1010565af1754ff0) flyteadmin began processing phase reason updates in batches, which causes all reason updates to persist in a timeline. The continual …
> Reduce maptask transitions between WaitingForResources and CheckingSubtaskExecutions

- flytepropeller/pkg/controller/garbage_collector.go
_NA_
The GC TTL configuration defaults to 23 in propeller configuration, but the comparison logs a warning if the value is not less than 23 and then proceeds to reset to 23. The correct approach is to make the comparison allow 23.
^^^
Locally.
_NA_
_NA_
> propeller gc ttl comparison should allow 23

- flyteplugins/go/tasks/pluginmachinery/flytek8s/pod_helper.go
- flyteplugins/go/tasks/pluginmachinery/flytek8s/pod_helper_test.go
_https://github.com/flyteorg/flyte/issues/4704_
Propeller doesn't always fail OOMKilled pods as OOMKilled.
Catch potential OOMKilled errors that have a ExitCode: 0 + enrich error messages to mark error as OOMKilled. 
Will follow up with a PR to enrich other error messages.
- added unit test
- ran workflow
```
import subprocess
from flytekit import Resources, task, workflow
from flytekit.core.workflow import WorkflowFailurePolicy
@task(requests=Resources(mem="500Mi"))
def subproc_oom():
try:
subprocess.run(["tail", "/dev/zero"], check=True)
except subprocess.CalledProcessError as e:
print(f"Return code {e.returncode}")
raise e
@task(requests=Resources(mem="500Mi"))
def other_oom():
l = []
while True:
l.append('a' * 10**6)
@workflow( …
```
> [BUG] handle potential uncaught OOMKilled terminations

- charts/flyte-core/README.md
- charts/flyte-core/templates/console/deployment.yaml
- charts/flyte-core/templates/propeller/webhook.yaml
- charts/flyte-core/values.yaml
- The console doesn't have / need a ServiceAccount, but it still needs credentials to be able to pull image from secured registries
Add a new imagePullSecrets value for that
- The webhook ServiceAccount didn't have the correct imagePullSecrets set, so similarly could not pull images from security registries. Use the propeller settings
> Flyte-core add missing imagePullSecrets support

- docs/deployment/agents/airflow.rst
> [Doc] Airflow agent deployment

- docs/deployment/agents/snowflake.rst
> [Doc] Snowflake agent deployment

- docs/conf.py
- docs/index.md
- docs/introduction/core_use_cases/analytics.md
- docs/introduction/core_use_cases/data_engineering.md
- docs/introduction/core_use_cases/index.md
- docs/introduction/core_use_cases/machine_learning.md
- docs/introduction/flyte_fundamentals/extending_flyte.md
- docs/introduction/flyte_fundamentals/index.md
- docs/introduction/flyte_fundamentals/optimizing_tasks.md
- docs/introduction/flyte_fundamentals/package_register.md
- docs/introduction/flyte_fundamentals/run_schedule.md
- docs/introduction/flyte_fundamentals/tasks_and_workflows.md
- docs/introduction/flyte_fundamentals/visualizing_task_input_and_output.md
- docs/introduction/getting_started_with_workflow_development/creating_a_flyte_project.md
- docs/introduction/getting_started_with_workflow_development/flyte_project_components.md
- docs/introduction/getting_started_with_workflow_development/index.md
- docs/introduction/getting_started_with_workflow_development/installing_development_tools.md
- docs/introduction/getting_started_with_workflow_development/running_a_workflow_locally.md
- docs/introduction/index.md
- docs/introduction/quickstart_guide.md
Covers [DOCS-274](https://unionai.atlassian.net/browse/DOCS-274) which is the first step of [DOCS-273](https://unionai.atlassian.net/browse/DOCS-273)
Move the onboarding guide from flytesnacks to flyte repo without making any other visual changes to the docs site
[DOCS-274]: https://unionai.atlassian.net/browse/DOCS-274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DOCS-273]: https://unionai.atlassian.net/browse/DOCS-273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Move intro docs from flytesnacks to flyte

- docs/community/contribute.rst
`flytectl` [looks](https://github.com/flyteorg/flytectl/blob/71fbaf4291393d7e120df868e68404494849842f/pkg/docker/docker_util.go#L31) at the `sandbox/` subdirectory to get configuration so let's add that to the docs.
> [Docs] add sandbox to local cluster resource path

- charts/flyte-core/templates/admin/deployment.yaml
- charts/flyte-core/templates/console/deployment.yaml
- charts/flyte-core/templates/datacatalog/deployment.yaml
- charts/flyte-core/templates/flytescheduler/deployment.yaml
- charts/flyte-core/templates/propeller/webhook.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_controlplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_controlplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- In https://github.com/flyteorg/flyte/pull/4756 / https://github.com/flyteorg/flyte/commit/fb9ffd56e81e7f7e4657cd668e53b2f1557e9178, flyte-core got
consistent podEnv values established in values.yaml. However, these
values were not properly injected into *all* the containers being
used in various deployments.
Fix that so that they are used in all deployments
- Make sure console doesn't render an empty env: block
> Flyte-core add missing podEnv values

- charts/flyte-core/templates/propeller/webhook.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_dataplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_dataplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
- The webhook service exposes 443 and targets port 9443, but the container doesn't expose port 9443
> Flyte-core Expose propeller webhook port 9443 in charts

- .github/workflows/flyteidl-release.yml
- flyteidl/pyproject.toml
Follow up to https://github.com/flyteorg/flyte/pull/4799
This PR fixes the `pyproject.toml` when building the wheel.
Run `python -m build` and unzip the wheel in `dist/` to see the contents.
> MNT Fixes packaging for flyteidl wheel

- flyteidl/MANIFEST.in
This PR adds a MANIFEST.in for `flyteidl` so that the `sdist` only includes the necessary files.
> Adds MANIFEST.in for flyteidl

- flyteadmin/pkg/manager/impl/validation/launch_plan_validator.go
- flyteadmin/pkg/manager/impl/validation/launch_plan_validator_test.go
closes https://github.com/flyteorg/flyte/issues/4866
See tracking issue, launch plan registration and validation should catch unbounded inputs before schedule invocation
> Verify unbounded inputs for all scheduled launch plan types

- .github/workflows/flyteidl-release.yml
NA
Since we moved to the monorepo we haven't published a flyteidl npm package (from versions [1.10.0 onwards](https://github.com/flyteorg/flyte/actions/workflows/flyteidl-release.yml)). 
This PR fixes it (by ensuring that it's functionally the same as the [original code in the flyteidl repo](https://github.com/flyteorg/flyteidl/blob/master/.github/workflows/npmpublish.yaml#L11)).
Checkout the code before running the script to publish the new version.
> Fix npm publish of flyteidl package

- flyteidl/pyproject.toml
NA
We're fully moved to buf, this dependence is no longer needed (as it was replaced by `protoc-gen-openapiv2`).
Tested in sandbox by generating an image that contained a version of flyteidl using the code in this PR and a doctored version of flytekit that didn't require flyteidl (so that I could install both at the same time without conflicts).
> Remove protoc_gen_swagger

- CODEOWNERS
To flag the docs team when there are docs PRs.
Creates a CODEOWNERS file and adds docs team members (@neverett and @ppiegaze) as reviewers for files in the /docs directory.
> Create CODEOWNERS file and add docs team

- docs/deployment/deployment/cloud_simple.rst
[_https://github.com/flyteorg/flyte/issues/<number>_](https://github.com/flyteorg/flyte/issues/4865)
Closes #4865 
The link in the docs that points to the "hard way" tutorial for on-prem deployment is out of date
Updating the link. The link is found here, under this header: https://docs.flyte.org/en/latest/deployment/deployment/cloud_simple.html#flyte-in-on-premises-infrastructure
The link that is being changed to is working, it just added the `single-node` folder
Old link
New link
https://docs.flyte.org/en/latest/deployment/deployment/cloud_simple.html#flyte-in-on-premises-infrastructure
> [Docs] update outdated link to on-prem tutorial

- docs/quickstart_guide.md
Re-adds the link to the hosted sandbox so users can try Flyte in the browser.
https://flyte--4856.org.readthedocs.build/en/4856/quickstart_guide.html
> Re-add link to hosted sandbox

- docs/concepts/schedules.rst
The asterisks in the cron table in the [Schedules doc](https://docs.flyte.org/en/latest/concepts/schedules.html#cron-expression) are rendering as list items instead of asterisks.
Simply escaping the asterisk didn't work, since it's in a table, so I turned the rst table into an HTML table and that seemed to fix the issue.
https://flyte--4836.org.readthedocs.build/en/4836/concepts/schedules.html
> Fix asterisk in cron table being rendered as list item

- docs/community/contribute.rst
Update directions in contributing guide for building Flyte docs to align with new monodocs build system
> Update flyte docs build directions

- docker/sandbox-bundled/images/manifest.txt
- docker/sandbox-bundled/manifests/complete-agent.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
Docker repository `bitnami/bitnami-shell` has been deprecated for a while and was removed recently. Single binary builds fail due to that ([failed workflow example](https://github.com/flyteorg/flyte/actions/runs/7871419560/job/21474991056)). `bitnami/os-shell` is a [direct replacement](https://hub.docker.com/search?q=bitnami-shell).
This change updates deprecated image references with the new one.
Singe binary workflow was executed successfully with these changes applied.
N/A.
N/A.
> Replaced deprecated bitnami/bitnami-shell image with bitnami/os-shell

- charts/flyte-core/templates/admin/deployment.yaml
- charts/flyte-core/templates/console/deployment.yaml
- charts/flyte-core/templates/datacatalog/deployment.yaml
- charts/flyte-core/templates/flytescheduler/deployment.yaml
- charts/flyte-core/templates/propeller/webhook.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_controlplane_generated.yaml
- deployment/eks/flyte_helm_dataplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_controlplane_generated.yaml
- deployment/gcp/flyte_helm_dataplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
Like #4785 does for the agent, this defines the security context for flyte-core pods / containers.
- Define secure defaults for all pod / container specs:
* runAsNonRoot: true
* capabilities: drop: ['ALL']
* allowPrivilegeEscalation: false
* seLinuxOptions: type: spc_t
This is required in many locations where policy enforcement agents
may be installed (like OPA Gatekeeper) which may otherwise prevent
deployments from launching.
The hard work of making sure the containers run as non-0 uids seems
to have already been done given all containers are already specifying
a runAsUser value of 1000 or 1001, so this should hopefully just be a
little more hardening around restricting kernel permissions /
enforcement within the container runtime.
These are generally considered standard / secure …
> Flyte-core define pod and container securityContext

- charts/flyte-core/README.md
- charts/flyte-core/templates/_helpers.tpl
- charts/flyte-core/templates/admin/deployment.yaml
- charts/flyte-core/templates/console/deployment.yaml
- charts/flyte-core/templates/datacatalog/deployment.yaml
- charts/flyte-core/templates/flytescheduler/deployment.yaml
- charts/flyte-core/templates/propeller/deployment.yaml
- charts/flyte-core/templates/propeller/manager.yaml
- charts/flyte-core/templates/propeller/webhook.yaml
- charts/flyte-core/values.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_controlplane_generated.yaml
- deployment/eks/flyte_helm_dataplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_controlplane_generated.yaml
- deployment/gcp/flyte_helm_dataplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
Closes #4893 
Without chart modifications, we are unable to deploy the flyte-core chart into OpenShift environments or other k8s environments that do not allow specification of user IDs.
Adds ability to override securityContext in Helm chart deployment for flyteadmin, flyteconsole, datacatalog, flytepropeller, and flytescheduler.
Deployed in an on-prem environment.
> Adding securityContext configuration to flyte-core charts

- docs/getting_started_with_workflow_development/flyte_project_components.md
Update imageSpec [doc](https://docs.flyte.org/en/latest/getting_started_with_workflow_development/flyte_project_components.html#imagespec) in `docs/getting_started_with_workflow_development/flyte_project_components.md`
> Update imageSpec doc

- flyteplugins/go/tasks/plugins/k8s/ray/config.go
- flyteplugins/go/tasks/plugins/k8s/ray/config_test.go
- flyteplugins/go/tasks/plugins/k8s/ray/ray.go
https://github.com/flyteorg/flyte/issues/4797
Closes #4797
Changes are needed to ensure that pods are running as the appropriate serviceAccount.
This enables these pods to pull images in private registries, and to further customize permissions per kubernetes environments.
Change podSpecs to leverage a serviceAccount defined in the default config. Also ensure this is value can be modified.
Through unit tests.
> Service Account for V1 Ray Jobs

- cmd/single/console_dist.go
NA
We recently noticed that flyteconsole assets were not being cached in single binary. This causes an unnecessary slowdown, as it forces the browser to always download all assets.
This PR sets the [`Cache-Control` header](https://www.cloudflare.com/learning/cdn/glossary/what-is-cache-control/) to store the assets returned by single binary for 7 days.
```
❯ curl -I 'http://localhost:30080/console/assets/886-55c90ced75ee4d84c22e.chunk.js' --compressed
HTTP/1.1 200 OK
accept-ranges: bytes
cache-control: max-age=604800
content-length: 18796
content-type: text/javascript; charset=utf-8
date: Tue, 20 Feb 2024 00:49:09 GMT
x-envoy-upstream-service-time: 0
server: envoy
```
Notice the `Cache-control` header being set in the response.
> Cache console assets in single binary

- charts/flyte-core/templates/clusterresourcesync/deployment.yaml
- charts/flyte-core/templates/flytescheduler/deployment.yaml
- charts/flyte-core/templates/propeller/deployment.yaml
- charts/flyte-core/templates/propeller/manager.yaml
Closes #4908
If .Values.secrets.adminOauthClientCredentials.enabled is false in flyte-core chart, some deployments will mount flyte-secret-auth secret even though the secret isn't created.
Add conditional brach volume and volumeMount to make creation of secret and volume mount are consistent
Can test it locally via `helm template charts/flyte-core`
> fix: mount flyte-secret-auth secret conditionally

- docs/user_guide/data_types_and_io/structureddataset.md
Now that [the user guide has been moved from flytesnacks to flyte](https://github.com/flyteorg/flyte/pull/4887), the changes from [this flytesnacks PR](https://github.com/flyteorg/flytesnacks/pull/1516) need to be applied over here instead.
Update StructuredDataset page to clarify that pandas is the only dependency required to use StructuredDatasets.
TBD
>  Clarify that only pandas is needed for StructuredDataset

- charts/flyte-core/README.md
- charts/flyte-core/values.yaml
- Flyte agent now tries to render a specific set of podLabels, so assumes that there is an empty `podLabels: {}` set. This change to values.yaml for flyte-core ensures empty values are there.
- Fixes:
Error: template: flyte-core/charts/flyteagent/templates/agent/deployment.yaml:17:17: executing "flyte-core/charts/flyteagent/templates/agent/deployment.yaml" at <include "flyteagent.podLabels" .>: error calling include: template: flyte-core/templates/_helpers.tpl:122:16: executing "flyteagent.podLabels" at <.Values.flyteagent.podLabels>: nil pointer evaluating interface {}.podLabels
> Fix flyte-core rendering when flyteagent enabled

- docs/conf.py
- docs/core_use_cases/analytics.md
- docs/core_use_cases/data_engineering.md
- docs/flyte_agents/developing_agents.md
- docs/flyte_agents/index.md
- docs/flyte_fundamentals/optimizing_tasks.md
- docs/index.md
In this PR: 
* Updates needed to create a new "Deprecated integrations" section
* Copy edits for the recently published agents docs
**NOTE:** merge https://github.com/flyteorg/flytesnacks/pull/1528 first, then merge this PR immediately after.
TBD
> Further edits to agents docs

- flyteadmin/pkg/repositories/transformers/node_execution.go
- flytepropeller/pkg/controller/nodes/transformers.go
_NA_
If `IsParent` is set flyteconsole will continually attempt to retrieve child node executions. In the case of ArrayNode, child node executions are only populated with the eventing scheme == 1.
Only setting `IsParent` on the node execution metadata if the array node event version is 1.
locally.
_NA_
_NA_
> Correcting IsParent metadata in ArrayNode eventing

- docs/user_guide/development_lifecycle/failure_node.md
- docs/user_guide/development_lifecycle/index.md
Adds failure node example from https://github.com/flyteorg/flytesnacks/pull/1328 since user guide docs now live in this repo.
https://github.com/flyteorg/flytesnacks/pull/1328
TBD
> Add failure node example from flytesnacks #1328

- flyteadmin/pkg/server/service.go
NA
grpc-gateway v2 switched the marshaller used to encode JSON messages in 2.5.0. This changed the default encoding from using snake_case to the recommended by protobuf (i.e. use lowerCamelCase).
The protobuf [docs](https://protobuf.dev/programming-guides/proto3/#json-options) mention that JSON printers may provide a way to use the proto names as field names instead. This option is exposed in [grpc-gateway](https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizing_your_gateway/#using-proto-names-in-json) and it involves setting a custom marshaler. 
This PR adds this custom marshaler to the `runtime.NewServeMux` call (see the [grpc gateway guide](https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/customizing_your_gateway/#using-proto-names-in-json)).  This marshaler, …
> add mux option for application/json

- docker/sandbox-bundled/Makefile
The generate flyte manifest job was failing due to deps not being updated.  This updates them.
> also run dep update

- charts/flyte-core/README.md
- charts/flyte-core/templates/propeller/webhook.yaml
- charts/flyte-core/values.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_dataplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_dataplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
Various resources recommend setting resources and limits for k8s deployments, e.g: https://www.cncf.io/blog/2022/10/20/kubernetes-best-practice-how-to-correctly-set-resource-requests-and-limits/
Optionally allows specifying flyte pod deployment resource requests and limits.
In values.yaml
```
webhook:
...
resources:
limits:
cpu: 200m
ephemeral-storage: 100Mi
memory: 200Mi
requests:
cpu: 10m
ephemeral-storage: 50Mi
memory: 100Mi
```
verified the rendered webhook deployment included
```
...
securityContext:
allowPrivilegeEscalation: false
capabilities:
drop: ["ALL"]
resources:
limits:
cpu: 200m
ephemeral-storage: 100Mi
memory: 200Mi
requests:
cpu: 10m
ephemeral-storage: 50Mi
memory: 100Mi
volumeMounts:
- name: config-volume
mountPath: /etc/flyte/config
readOnly: true
- name: webhook-certs …
```
> Allow specifying flyte pod webhook deployment resources

- script/generate_helm.sh
https://github.com/flyteorg/flyte/issues/4950
`make helm` expects to run on go 1.21, but `github.com/norwoodj/helm-docs/cmd/helm-docs` recently published a new version where they use go 1.22.
Pin github.com/norwoodj/helm-docs/cmd/helm-docs to 1.12.0.
Made a change to `flyte-binary` chart and successfully ran `make helm`.
> Pin helmdocs to 1.12.0

- docker/sandbox-bundled/Makefile
Failed to build the sandbox-bundled
```bash
(flytekit-3.10) ➜  make flyte
```
```python
docker buildx build --build-arg FLYTECONSOLE_VERSION=latest --platform linux/amd64 --tag flyte-binary:sandbox --output type=docker,dest=images/tar/amd64/flyte-binary.tar ../..
[+] Building 0.0s (0/0)                                                                                                                                                                                       docker:desktop-linux
ERROR: Docker exporter is not supported for the docker driver.
Switch to a different driver, or turn on the containerd image store, and try again.
Learn more at https:/docs.docker.com/go/build-exporters/
make: *** [flyte] Error 1
```
Specify builder for docker build
> Specify builder for docker build

- docs/deployment/agents/bigquery.rst
- docs/deployment/agents/chatgpt.rst
- docs/deployment/agents/databricks.rst
- docs/deployment/agents/index.md
- docs/deployment/agents/mmcloud.rst
- docs/deployment/agents/snowflake.rst
- monodocs-environment.yaml
https://flyte--4992.org.readthedocs.build/en/4992/deployment/agents/index.html
https://github.com/flyteorg/flytesnacks/pull/1539
> [Docs] Chatgpt Agent Setup

- charts/flyte-core/templates/_helpers.tpl
- deployment/sandbox/flyte_helm_generated.yaml
- docker/sandbox-bundled/manifests/complete-agent.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
Closes #5004 
Deployed to an on-prem K8s cluster with minio and it successfully executes workflows.
I used `storage.type: sandbox`
> Fix minio config on helpers.tpl

- flyteadmin/pkg/manager/impl/validation/task_validator.go
- flyteadmin/pkg/manager/impl/validation/task_validator_test.go
https://github.com/flyteorg/flyte/issues/4965
We have a slight mismatch between the constants used to refer to ephemeral storage between the k8s pod spec and Flyte's resource object. This is especially important during task resource validation, since in the case of pod templates the pod spec is provided as is, whereas in the case of regular tasks the flytekit sdk ensures that the correct value is used. 
Special case the value "ephemeral-storage" during task resource validation only in the case of pod templates.
Unit tests and also ran on sandbox locally.
> Fix ephemeral storage validation in the case of pod templates

- flytepropeller/pkg/controller/nodes/task/k8s/task_exec_context.go
- flytepropeller/pkg/controller/nodes/task/k8s/task_exec_context_test.go
@ByronHsu recently implemented middleware to inject the user identity into the flyte workflow's ExecutionSpec: https://github.com/flyteorg/flyteadmin/pull/549 and in https://github.com/flyteorg/flyte/pull/4637 I injected the user identity into task pods as a label.
For IdPs like Okta, the execution identity is an email address which is not a valid Kubernetes label, causing the creation of the pod to fail.
In this PR I add sanitation to the execution identity before injecting it as a label.
* Ran flytepropeller with this change and ensured that pods can be created when the execution identity is an email address
* Added a unit test that would have caught this
> Fix: Sanitize user identity before injecting into task pod as K8s label

- docs/deployment/configuration/general.rst
NA
`//` is the wrong comment indicator in yaml.
> Fix yaml comment in pod template examples

- docs/deployment/configuration/general.rst
NA
Labels and annotations are dictionaries.
Tested on a Flyte cluster.
> Fix use of labels and annotations in pod template examples

- charts/flyte-core/templates/common/ingress.yaml
- Kubernetes 1.19 was released in August 2020 and it moved ingress out of beta
- Kubernetes 1.22 removed the beta ingress type in August 2021 and went out of support in October 2022
- As of March 2024, only Kubernetes 1.26 and later are supported
- Therefore, there's no reason to make this check!
- 
Simplify ingress code
> Flyte-core remove unnecessary ingress capability checks

- script/release.sh
https://github.com/flyteorg/flyte/issues/5036
We cannot release the flyteconsole revamp before Schedules are implemented.
> Pin flyteconsole version in release process

- .github/workflows/validate-helm-charts.yaml
Closes #4973 
We should be serious about changes to helm charts and manifests, The current CI doesn't ensure manifests are valid against to the schema for Kubernetes.
1. Create a new gha workflow to test helm charts if them are changed, and validate generated manifests.
2. We can specify k8s versions that we want to ensure manifests are still valid for that k8s version. (avoiding some apiVersion of resource is deprecated but we don't notice that)
1. Install [nektos/act](https://github.com/nektos/act) to test actions locally
2. Create an json file called `event.json`, and copy & paste the following code into event.json
```json
{
"repository": {
"default_branch": "master"
}
}
```
3. Run `act pull_request -W .github/workflows/validate-helm-charts.yaml --container-architecture linux/amd64 -e …
> CI workflow for helm charts and manifests

- charts/flyte-deps/Chart.yaml
- charts/flyte-deps/README.md
- charts/flyte/Chart.yaml
- charts/flyte/README.md
- docker/sandbox-bundled/manifests/complete-agent.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
https://github.com/flyteorg/flyte/issues/5055
`make helm` is failing becaues the Spark operator migrated repos.
Modify the address of the Spark operator in the helm charts.
> Update spark-on-k8s-operator address in helm charts

- .github/workflows/validate-helm-charts.yaml
NA
The original workflow can not be triggered correctly because of wrong path filtering.
> Fix wrong syntax for path filtering in validate-helm-charts.yaml

- charts/flyte-core/templates/flytescheduler/deployment.yaml
> Fix: flyte-secret-auth secret not mounted properly in flyte-core

- .github/workflows/single-binary.yml
NA
We should use the same version of flytekit to register and run tests, thereby decreasing the chances of mismatches in expectations of commands used to run the tasks in the tests.
In this specific case, we shipped https://github.com/flyteorg/flytekit/pull/2242 in version 1.12.0b0, which changed the the resolvers used in the registration of map tasks (arraynode-based and legacy). That change is present in the latest flytekit images (`ghcr.io/flyteorg/flytekit:py.3.11-latest`, etc). That is the same image used in the [registration](https://github.com/flyteorg/flyte/blob/master/.github/workflows/single-binary.yml#L194) of functional tests in single-binary. The issue happens when we use a different version to register those tests (because the task templates are produced during registration, …
> Match flytekit versions used to register and run functional tests

- .github/workflows/validate-helm-charts.yaml
- Makefile
- charts/event.json
- charts/flyte-binary/Chart.yaml
- charts/flyte-binary/values.yaml
- charts/flyte-core/Chart.yaml
- charts/flyte-core/values.yaml
- charts/flyte-deps/Chart.yaml
- charts/flyte/Chart.yaml
- charts/flyte/values.yaml
- charts/flyteagent/Chart.yaml
- charts/flyteagent/values.yaml
- docker/sandbox-bundled/manifests/complete-agent.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
- script/release.sh
NA
We enabled chart testing in https://github.com/flyteorg/flyte/pull/5027, but never got around fixing the lint errors caught by that check. This PR fixes the first batch of errors.
> Fix lint errors caught by `chart-testing`

- docs/_ext/import_projects.py
- docs/core_use_cases/machine_learning.md
- docs/deployment/agents/index.md
- docs/deployment/agents/sagemaker_inference.rst
- docs/flyte_fundamentals/extending_flyte.md
- docs/flyte_fundamentals/optimizing_tasks.md
- docs/user_guide/basics/workflows.md
- docs/user_guide/extending/backend_plugins.md
- docs/user_guide/productionizing/configuring_logging_links_in_the_ui.md
- monodocs-environment.lock.yaml
- monodocs-environment.yaml
Fixes https://github.com/flyteorg/flyte/issues/4079
These changes are required to add the additional library that the sagemaker agent requires while building docs and to document the backend setup config.
Documentation updates.
Built the documentation locally.
> sagemaker agent backend setup documentation

- charts/flyte-binary/Chart.yaml
- charts/flyte-binary/gke-starter.yaml
- docker/sandbox-bundled/manifests/complete-agent.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
_https://github.com/flyteorg/flyte/issues/5016_
Closes #5016 
There are examples  of how to deploy flyte minimally on AWS/EKS described in [Single Cluster Simple Cloud Deployment](https://docs.flyte.org/en/latest/deployment/deployment/cloud_simple.html) but not for GCP/GKE.
This values file makes it easier for new people to deploy.
A minimal value file with default settings filled in for a minimal deployment on GKE/GCP using the flyte-binary chart
I used it to deploy on GKE.
> add first version of gke-starter values file

- docs/deployment/agents/chatgpt.rst
NA
Secret name is actually slightly different. The [code](https://github.com/flyteorg/flytekit/blob/80fc5ebfb2749dd6f0d465b7fdd094c8e31451a9/plugins/flytekit-openai/flytekitplugins/chatgpt/agent.py#L17) expects it to be named `flyte_openai_api_key`.
> Fix open ai secret name

- flyteadmin/auth/authzserver/claims_verifier.go
[Improved flyte error messages #3502](https://github.com/flyteorg/flyte/discussions/3502)
When there is an audience mismatch during the `verifyClaims` step in the `authzserver`, the error message details the provided audience, but not the expected audience.
Include the expected audience(s) in the error message. This will greatly improve ease of debugging.
Old message:
```
{"json":{"src":"handlers.go:303"},"level":"info","msg":"Failed to parse Access Token from context. 
Will attempt to find IDToken. Error: invalid audience [&{[account] ... 2024-03-22 17:08:22 +0000 
UTC 2024-03-22 16:53:22 +0000 UTC 0001-01-01 00:00:00 +0000 UTC ...}]","ts":"2024-03-22T16:53:52Z"}
```
New message:
```
{"json":{"src":"handlers.go:303"},"level":"info","msg":"Failed to parse Access Token from context. 
Will …
```
> Improve audience mismatch debugging

- Makefile
- docs/community/contribute.rst
Clarify instructions and add make target to rebuild single-binary flyte console dependency. There is currently no guide about how to run the  newest flyteconsole in flyte demo sandbox.
Update the docs and add a new Makefile target `clean`.
> docs(sandbox): Add guide for running newest flyteconsole in flyte sandbox

- docs/community/contribute.rst
NA
https://github.com/flyteorg/flyte/pull/4509/files removed the unnecessary step, but during the monodocs work we ended up bringing that step back.
Remove the need to use `sed` to replace the contents of the `$HOME` env var in `flyte-single-binary-local.yaml`.
I also added a single space between the word `Step` and the number to increase readability.
> Remove unnecessary step and fix numbering in code examples

- charts/flyte-core/templates/_helpers.tpl
- charts/flyte-deps/Chart.yaml
- charts/flyte-deps/README.md
- charts/flyte/Chart.yaml
- charts/flyte/README.md
- charts/flyteagent/templates/_helpers.tpl
While testing out v1.11.0 ran into a couple of issues when enabling flyteagent from the flyte-core chart.
We define the templates `flyteagent.*` in both flyte-core and flyteagent charts.
Since template names are global across top level charts/subcharts, I ran into an issue dereferencing podValues.
In this case it was using the flyte-core definition of the template instead of flyteagent's.
```
Error: template: flyte-core/charts/flyteagent/templates/agent/deployment.yaml:17:17: executing "flyte-core/charts/flyteagent/templates/agent/deployment.yaml" at <include "flyteagent.podLabels" .>: error calling include: template: flyte-core/templates/_helpers.tpl:122:16: executing "flyteagent.podLabels" at <.Values.flyteagent.podLabels>: nil pointer evaluating interface {}.podLabels
```
There is also …
> fix rendering of flyte-core and flyteagent charts

- docs/concepts/admin.rst
- flyteadmin/pkg/common/filters.go
- flyteadmin/pkg/common/filters_test.go
We currently don't support value_not_in filter.
Add value_not_in filter support.
> Update repeated value filters with ValueNotIn support

- Dockerfile
- Dockerfile.datacatalog
- Dockerfile.flyteadmin
- Dockerfile.flytecopilot
- Dockerfile.flytepropeller
- Dockerfile.flytescheduler
The container images include a number of critical and high CVEs that should be addressed.
- go 1.21.5 was released on 12-5-2023 and go 1.21.8 was released on 3-5-2024. During that time a number of high and critical vulns have been addressed
- This PR changes the build process to float with the latest go release to automatically pick up remediated vulnerabilities rather than pin to a specific go release
- Ideally there would be a renovate or dependabot process that automatically puts up PRs to this repo to update the pinning, which is safer from a build / test perspective.  Without that process in place, it's probably better to float with the latest patch release of go 1.21
> Update container builds from go 1.21.5 to 1.21.latest

- docs/user_guide/data_types_and_io/index.md
Fixes broken link in this table: https://docs.flyte.org/en/latest/user_guide/data_types_and_io/index.html#mapping-python-to-flyte-types
Remove bold styling to fix link.
TK
> Fix broken link in "Mapping Python to Flyte types" table

- charts/flyte-core/README.md
- charts/flyte-core/templates/propeller/webhook.yaml
- charts/flyte-core/values.yaml
- All the other pods can have their priorityClassName set except for the webhook
- New config setting for webhook priorityClassName like other services
The updated chart is being used to deploy Flyte in our environment. There are tests that validate that priorityClassName propagates to the webhook pod properly
> Add flyte-core missing priorityClassName to webhook values

- docs/conf.py
- monodocs-environment.lock.yaml
- monodocs-environment.yaml
_https://github.com/flyteorg/flyte/issues/4909_
Resolves: flyteorg/flyte#4909
See the description in the corresponding issue.
Open all external links in new tab.
> [Docs] Open external links in new tab

- docs/community/contribute.rst
N/A
It's better to run `make go-tidy` because it also run `go mod tidy` for other components.
Change `go mod tidy` to `make go-tidy` in the contribution guide.
> docs(contribute): Change go mod tidy to make go-tidy

- flyteadmin/pkg/manager/impl/execution_manager.go
- flyteadmin/pkg/repositories/transformers/execution.go
- flyteadmin/pkg/repositories/transformers/execution_test.go
The execution phase should be FAILED because of the error in input pass to `CreateExecutionModel()`. However, we only update the phase in closure but not in `execution.phase`.
As a follow up, we don't even need `Phase` in the `CreateExecutionModelInput`
1. Fix the bug
2. Add assertion in test.
3. Clean up redundant phase in `CreateExecutionModelInput{`
> Fix execution phase

- Makefile
Closes https://github.com/flyteorg/flyte/issues/4639
Minor fix. I couldn't find anything about the guarantees for the `bin` directory, so adding a bit of defensive programming.
> Add trailing slash to compile make target

- docs/concepts/tasks.rst
- docs/flyte_fundamentals/optimizing_tasks.md
https://unionai.atlassian.net/browse/DOCS-385
It turns out that all user exceptions are considered non-recoverable unless the exception is a subclass of FlyteRecoverableException ([Tasks - Flyte](https://docs.flyte.org/en/latest/concepts/tasks.html#fault-tolerance)). 
This means that the RuntimeError in the retry example [here](https://docs.flyte.org/en/latest/flyte_fundamentals/optimizing_tasks.html#retries) will not actually retry. 
We want to change the error in the example to one which will trigger a retry of the task if the decorator is used.
Slack convo: https://unionai.slack.com/archives/C06RE4ZR5QQ/p1711576283580859
As only user exceptions that are subclasses of `FlyteRecoverableException` are compatible with retries, `FlyteRecoverableException` is used rather than a …
> Change retry error from RuntimeError to FlyteRecoverableException

- docs/deployment/agents/sagemaker_inference.rst
> update sagemaker agent setup doc as secrets aren't required anymore

- datacatalog/go.mod
- datacatalog/go.sum
- flyteadmin/go.mod
- flyteadmin/go.sum
- flytecopilot/go.mod
- flytecopilot/go.sum
- flyteidl/go.mod
- flyteidl/go.sum
- flyteplugins/go.mod
- flyteplugins/go.sum
- flytepropeller/go.mod
- flytepropeller/go.sum
- flytestdlib/go.mod
- flytestdlib/go.sum
- go.mod
- go.sum
logrus sets off some security scanners with a medium vuln
- Most flyte binaries are on v1.9.3 but some are still on an older v1.7.0 which contains PRISMA-2023-0056
Also run go mod tidy
> Upgrade logrus to v1.9.3 everywhere

- datacatalog/go.mod
- datacatalog/go.sum
- flyteadmin/go.mod
- flyteadmin/go.sum
- flytecopilot/go.mod
- flytecopilot/go.sum
- flyteidl/go.mod
- flyteidl/go.sum
- flyteplugins/go.mod
- flyteplugins/go.sum
- flytepropeller/go.mod
- flytepropeller/go.sum
- flytestdlib/go.mod
- flytestdlib/go.sum
- go.mod
- go.sum
- Resolves high vuln PRISMA-2022-0227 related to authentication bypass
- Upgrades v3.9.0 and v3.11.0 to use v3.12.0 consistently
> Upgrade go-restful to v3.12.0

- Makefile
- docs/_static/custom.js
- docs/conf.py
- monodocs-environment.lock.yaml
- monodocs-environment.yaml
This PR removes the `sphinx-new-tab-link` dependency for adding `target="_blank"` to external links in favor of using a simple custom javascript file to achieve the same effect.
The `sphinx-new-tab-link` dependency caused an unintended change in the html/css styling of the site (black border on table elements):
`sphinx-new-tab-link` depends on `sphinxcontrib-extdevhelper-kasane`, ([repo](https://github.com/ftnext/sphinxcontrib-extdevhelper-kasane)), which seems to modify the way the html docs are rendered in a non-obvious way.
Use sphinx's supported way of customizing docs with a `custom.js` file that achieves the same thing, but without the additional python dependency.
Docs built locally with `make docs`
> use javascript to open new tab for external links

- docs/deployment/plugins/k8s/index.rst
> Update K8s plugin config docs

- docs/concepts/component_architecture/flytepropeller_architecture.rst
This PR aims to expand details on how the different components of propeller play a role during a workflow execution, adding steps for users to verify on their own how the execution engine works. This work sets a baseline to further discuss performance optimization in other sections of the docs.
> Update Propeller architecture documentation

- Dockerfile.datacatalog
- Dockerfile.flyteadmin
- Should resolves vulnerability scans for the grpc health probe
https://github.com/grpc-ecosystem/grpc-health-probe/releases/tag/v0.4.25
https://github.com/grpc-ecosystem/grpc-health-probe/compare/v0.4.11...v0.4.25
Resolves
CVE-2023-39325
CVE-2022-41723
CVE-2022-41716
CVE-2022-27664
CVE-2023-44487
CVE-2023-44487
CVE-2022-41717
CVE-2022-29526
CVE-2024-28180
> Upgrade grpc health probe 0.4.11 -> 0.4.25

- docs/flyte_agents/developing_agents.md
- docs/flyte_agents/index.md
- docs/flyte_agents/testing_agents_locally.md
- Update the existing agent example 
- Add a sensor example
- Add a screenshot to show how to run BigQuery and Databricks tasks on your local machine
doc links:
- https://flyte--5130.org.readthedocs.build/en/5130/flyte_agents/developing_agents.html
- https://flyte--5130.org.readthedocs.build/en/5130/flyte_agents/testing_agents_locally.html
> docs: update agent development documentation

- script/release.sh
This reverts commit 68a34159b94ef4c82a5fa1199bbee142d04614e9.
NA
Schedules are [now](https://github.com/flyteorg/flyteconsole/pull/860) implemented in the revamped flyteconsole. Time to revert the pin.
Just revert the pin.
> Revert "Pin flyteconsole version in release process (#5037)"

- docs/community/contribute.rst
`link` doesn't seem like a valid target, perhaps it's a typo and it should be `make lint` instead. 
Change `make link` to `make lint`
> fix make link error

- flytepropeller/pkg/controller/nodes/subworkflow/launchplan/admin.go
- flytepropeller/pkg/controller/nodes/subworkflow/launchplan/admin_test.go
Closes: #5173 
For more uniform distribution of workflows across fltyepropeller shards. 
Specifically delete the `shard-key` label but copy all the other labels from parent to child as before. 
Added a unit test 
I've been using it in production.
> Stop admin launcher copying shard key from parent workflow

- flyteadmin/pkg/repositories/config/migrations.go
- flyteadmin/pkg/repositories/config/migrations_test.go
https://github.com/flyteorg/flyte/issues/3966
This commit fixes a bug with migrations. The previous code was modifying a table (`description_entities`) that does not exists yet when the migration is ran in order. 
Only modify id column of tables that exist already.
N/A
> Fix Id bigint conversation for not yet created table

- docs/deployment/configuration/auth_setup.rst
The authentication and authorization guides for `flyte-core` are slightly wrong and led to some confusion on our side.
This PR should fix missing keys and improve some formatting for the AzureAD guide.
> docs: add missing key in auth guide

- flytepropeller/pkg/controller/nodes/array/execution_context.go
fixes https://github.com/flyteorg/flyte/issues/5171
In ArrayNode executions where the execution context has environment variables each subNode evaluation will attempt to inject maptask specific variables into the same map. This is because golang passes all maps by reference.
In this PR we updated the arrayExecutionContext to shallow copy existing environment variables so each subNode evaluation maintains their own replica before injecting maptask specific environment variables. This ensures that there can not be concurrent map writes in the case of parallelized subNode evaluations.
Printed memory addresses of `EnvironmentVariables` map before and after change and viewed a change.
_NA_
_NA_
_NA_
_NA_
> Shallow copying EnvironmentVariables map before injecting ArrayNode env vars

- flytepropeller/pkg/controller/handler.go
Closes #5170
Accurate metrics are useful.
Fix the streak length metric reporting by avoiding use of `defer`. Included slightly simplifying the branching logic. 
I've been using it in production.
> Fix streak length metric reporting

- charts/flyte-binary/templates/_helpers.tpl
Closes https://github.com/flyteorg/flyte/issues/5186
We missed a start to this path in https://github.com/flyteorg/flyte/pull/4946/.
> Fix path to AuthMetadataService in flyte-binary chart

- flyteplugins/go/tasks/pluginmachinery/internal/webapi/monitor.go
log links are not shown up on FlyteConsole when the task status is running.
It will also fix other webAPI plugins.
propeller only sends the event when the current event is not equal to the previous event, so if `ResourceCache` sets the phase to running here without info, the log link will never show up on flyteconsole when the status is running.
The phase should be `PhaseQueue` when there is no resource in the [cacheItem](https://github.com/flyteorg/flyte/blob/328de82f2d81fb4b8fc848d2c178858b49f2c2db/flyteplugins/go/tasks/pluginmachinery/internal/webapi/monitor.go#L33).
The async ResourceCache is empty if the `Get` [request](https://github.com/flyteorg/flyte/blob/ea02a22134acb6e548ed034829a2b17361a65c86/flyteplugins/go/tasks/pluginmachinery/int …
> Change phase to queue on job submit for webapi plugins

- flyteplugins/go.mod
- flyteplugins/go/tasks/pluginmachinery/internal/webapi/cache.go
- flyteplugins/go/tasks/pluginmachinery/internal/webapi/cache_test.go
- flyteplugins/go/tasks/pluginmachinery/internal/webapi/core.go
Ratelimiter config was not used to configure the rate limiter for webapi plugins.
> Use ratelimiter config in webapi plugins

- docs/deployment/plugins/k8s/index.rst
- monodocs-environment.lock.yaml
N/A
The newest documentation for Ray Kubernetes plugin setup is not correct.
- The `kuberay-operator` version should be `1.1.0`
- Remove the rbac part because the `kuberay` helm chart already deals with them.
> docs(ray): Update kuberay documentation

- flyteplugins/go/tasks/pluginmachinery/internal/webapi/allocation_token.go
- flyteplugins/go/tasks/plugins/webapi/agent/config.go
- flytepropeller/pkg/controller/nodes/task/resourcemanager/config/config.go
- flytepropeller/pkg/controller/nodes/task/resourcemanager/config/config_flags.go
https://flyte-org.slack.com/archives/CP2HDHKE1/p1708818106936209
Tasks are stuck in the queue phase when the resource quota is exceeded since the propeller won't send the event to Flyteadmin if the current phase is equal to the [previous](https://github.com/flyteorg/flyte/blob/ea02a22134acb6e548ed034829a2b17361a65c86/flyteplugins/go/tasks/pluginmachinery/internal/webapi/allocation_token.go#L54) phase. Therefore, propeller won't update the state (`PhaseNotStarted` ->`PhaseAllocationTokenAcquired`) as well, and it will always assume that there is no resource available to execute the task.
Change phase to WaitingForResources when the quota is exceeded, so propeller will send the event to flyteadmin.
local sandbox and enable the resource manager
Before:
After:
NA
NA
> Change phase to WaitingForResources when quota exceeded

- docs/deployment/plugins/k8s/index.rst
The helm repository for the spark operator listed in the [Configure Kubernetes Plugins](https://docs.flyte.org/en/latest/deployment/plugins/k8s/index.html#deployment-plugin-setup-k8s) documentation is no longer active.
I'm updating the url as stated in the respective [issue](https://github.com/kubeflow/spark-operator/issues/1929) in the spark operator repository. I tested that this repository works.
> Fix: Update spark operator helm repository

- flytepropeller/pkg/controller/nodes/cache.go
> add cache client read and write otel tracing

- docs/index.md
Fixes incorrect link to FlyteIDL reference docs.
> Fix FlyteIDL docs link

- flyteplugins/go/tasks/plugins/webapi/agent/plugin.go
- flyteplugins/go/tasks/plugins/webapi/agent/plugin_test.go
We want to let users be able to set sync task's timeout, and it should be different apart from `CreateTask`.
Create a new context before executing `ExecuteTaskSync`.
We can set the timeout of `ExecuteTaskSync` function by adding 
`ExecuteTaskSync: 10s` in our flytepropeller config map.
for example.
```yaml
agent-service:
supportedTaskTypes:
- chatgpt
- sensor
defaultAgent:
endpoint: "localhost:8000"
insecure: true
timeouts:
ExecuteTaskSync: 10s
defaultTimeout: 10s
```
remote execution and unit tests.
single-binary-dev
https://github.com/flyteorg/flyte/pull/5208
> [easy] [flyteagent] Add `ExecuteTaskSync` function timeout setting

- docs/deployment/configuration/monitoring.rst
Similar to what's requested on https://github.com/flyteorg/flyte/issues/5205 and while this PR doesn't close that Issue, it adds recommendations on how to make use of the Grafana dashboards, connecting a Prometheus instance, the Service Monitors and the necessary Grafana config.
> Update Monitoring documentation

- flyteidl/buf.gen.yaml
- flyteidl/gen/pb_rust/datacatalog.rs
- flyteidl/gen/pb_rust/datacatalog.tonic.rs
- flyteidl/gen/pb_rust/flyteidl.cacheservice.rs
- flyteidl/gen/pb_rust/flyteidl.cacheservice.tonic.rs
- flyteidl/gen/pb_rust/flyteidl.service.rs
- flyteidl/gen/pb_rust/flyteidl.service.tonic.rs
NA
Just experimenting with ways of interacting with grpc in Rust.
> Generate rust grpc using tonic

- docs/getting_started_with_workflow_development/creating_a_flyte_project.md
- docs/getting_started_with_workflow_development/flyte_project_components.md
Updated "Creating a Flyte project" to reference the new [flytekit Dockerfile template](https://github.com/flyteorg/flytekit-python-template/tree/main/basic-template-dockerfile) in "Creating a Flyte project" for users who need to use a Dockerfile instead of ImageSpec. Also fixes link to the basic ImageSpec template.
TK
> Update "Creating a Flyte project" with link to new Dockerfile project template

- docs/getting_started_with_workflow_development/flyte_project_components.md
- docs/user_guide/data_types_and_io/dataclass.md
- docs/user_guide/data_types_and_io/index.md
The user guide docs have been moved to Flyte, so we need to re-apply changes from https://github.com/flyteorg/flytesnacks/pull/1553/.
https://github.com/flyteorg/flytesnacks/pull/1553/
TK
> Re-apply changes  to dataclass docs from flytesnacks#1553

- flytestdlib/cache/auto_refresh.go
- flytestdlib/cache/auto_refresh_test.go
https://flyte-org.slack.com/archives/C05BN3A92SE/p1712926168291449
closed https://github.com/flyteorg/flyte/issues/5202
`workqueue.Add` will add all the item in the async cache to the queue at the same time and cause propeller to send N (number of items in the async cache) requests to the external system and some tasks may run into rate limit issue.
Use `workqueue.AddRateLimited` instead of `workqueue.Add`. 
Local Sandbox
NA
NA
NA
> perf(cache): Use AddRateLimited for batch enqueue

- docs/_static/custom.js
Currently, the algolia search bar maintains the light theme even when dark mode is toggled:
This PR propogates the `data-theme="light/dark/auto"` setting that the furo sphinx theme handles from the `body` element to the root `html` element.
Built the docs locally with `make docs`
> propagate dark/light theme to algolia search bar

- charts/flyte-core/README.md
- charts/flyte-core/templates/admin/service.yaml
- charts/flyte-core/templates/datacatalog/service.yaml
- charts/flyte-core/templates/propeller/service.yaml
- charts/flyte-core/values.yaml
_NA_
Users may want to expose additional ports through k8s services for Flyte components.
This PR adds configuration for exposing additional ports through helm.
Updated the values file to include a port in the additional port and generated yaml files using:
```
helm template -n flyte --create-namespace flyte ~/Development/flyte/charts/flyte-core --values ~/Development/flyte/charts/flyte-core/values.yaml --debug > flyte.yaml
```
verified that the services included an additional port.
_NA_
_NA_
_NA_
_NA_
> Added additional port configuration for flyte services

- docs/deployment/plugins/k8s/index.rst
> [BUG] fix(doc): Wrong configuration in spark plugin with binary chart

- docs/concepts/workflow_lifecycle.rst
Advice is a noun while advise is a verb
> Fix grammatical error in workflow lifecycle docs

- flyteplugins/go/tasks/pluginmachinery/flytek8s/config/config.go
- flyteplugins/go/tasks/pluginmachinery/flytek8s/container_helper.go
Users should be able to configure the ImagePullPolicy they desire for created pods in k8s plugin. 
Added a field `ImagePullPolicy` in `flytek8s` plugin. 
make test_unit
setting different values for image-pull-policy, including not specifying the value (i.e. no `image-pull-policy` key)
```yaml=
plugins:
logs:
kubernetes-enabled: true
kubernetes-template-uri: http://localhost:30080/kubernetes-dashboard/#/log/{{.namespace }}/{{ .podName }}/pod?namespace={{ .namespace }}
cloudwatch-enabled: false
stackdriver-enabled: false
k8s:
image-pull-policy: Always
default-env-vars:
- FLYTE_AWS_ENDPOINT: http://flyte-sandbox-minio.flyte:9000
- FLYTE_AWS_ACCESS_KEY_ID: minio
- FLYTE_AWS_SECRET_ACCESS_KEY: miniostorage
k8s-array:
logs:
config: …
```
> add plugins support for k8s imagepullpolicy

- flyteidl/clients/go/admin/deviceflow/payload.go
- flyteidl/clients/go/admin/deviceflow/token_orchestrator.go
- flyteidl/clients/go/admin/deviceflow/token_orchestrator_test.go
Closes https://github.com/flyteorg/flyte/issues/3288
This is porting https://github.com/flyteorg/flyteidl/pull/362 to the monorepo.
> Added unmarshal attribute for expires_in for device flow auth token

- .github/PULL_REQUEST_TEMPLATE.md
This PR updates the PR template to properly link to issue in `flyteorg/flyte` to auto close the original issue.
REF: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
> Update template to link issue for closing

- docs/deployment/configuration/generated/flytepropeller_config.rst
- flytepropeller/events/admin_eventsink.go
- flytepropeller/events/config.go
- flytepropeller/events/config_flags.go
- flytepropeller/events/config_flags_test.go
- flytepropeller/pkg/controller/nodes/catalog/config.go
- flytepropeller/pkg/controller/nodes/catalog/config_flags.go
- flytepropeller/pkg/controller/nodes/catalog/config_flags_test.go
- flytepropeller/pkg/controller/nodes/catalog/datacatalog/datacatalog.go
Propeller does not have retries or backoffs for the eventsink adminclient (but does for datacatalog and cacheservice). Instead on failure it will consume a system retry and retry (near immediately) to process the workflow, continuing to hammer admin.
- add retries to sending events to admin from propeller + add exponential backoff
- add config to make this configurable
- ran locally w/ admin down to ensure backoffs were being respected.
> [Feature] add retries and backoffs for propeller sending events to admin

- flytepropeller/pkg/controller/nodes/task/k8s/plugin_collector.go
- flytepropeller/pkg/controller/nodes/task/k8s/plugin_collector_test.go
- flytepropeller/pkg/controller/nodes/task/k8s/plugin_manager.go
- flytepropeller/pkg/controller/nodes/task/k8s/plugin_manager_test.go
fixes https://github.com/flyteorg/flyte/issues/5087
Refer to issue ^^ for in-depth explanation of problem.
Instead of back-pedaling from the informer to retrieve the object cache for listing k8s objects, this PR updates the plugin object monitoring mechanism to issue queries directly to the cache using the k8s object kind and version.
locally with varying configuration.
_NA_
_NA_
_NA_
_NA_
> Fix support for limit-namespace in FlytePropeller

- docs/_ext/import_projects.py
- docs/conf.py
- flyteidl/conf.py
N/A
Replace `os.path` with `pathlib` to improve readability.
Replace `os.path` with `pathlib`.
> refactor(python): Replace os.path with pathlib

- docs/concepts/versioning.rst
https://github.com/flyteorg/flyte/issues/4616
> [Docs] add colon rule in version

- flyteplugins/go/tasks/pluginmachinery/internal/webapi/core.go
NA
Propeller keeps sending the requests to agents because propeller didn't remove the item from the async cache when users aborted the workflow.
Delete the item from the cache on abort.
local sandbox
remote cluster
NA
NA
> fix(webapi): Ensure cache deletion on abort workflow

- docs/_templates/base.html
N/A
This pull request adds the necessary scripts to add the RunLLM widget to the Flyte documentation.
Includes a script tag in the base template.
This code was tested on a Github Codespace. To test changes, I built the project and served it to myself with a simple http server to verify that the static site bundle works properly.
^ Once all the plumbing is hooked up on our backend this error should go away.
After configuring things on our end, here is a screenshot of the widget in action running against a staging deployment:
> RunLLM Widget Configuration

- docs/conf.py
- docs/deprecated_integrations/bigquery_plugin/bigquery_plugin_example.md
- docs/deprecated_integrations/bigquery_plugin/index.md
- docs/deprecated_integrations/databricks_plugin/databricks_plugin_example.md
- docs/deprecated_integrations/databricks_plugin/index.md
- docs/deprecated_integrations/index.md
- docs/deprecated_integrations/mmcloud_plugin/index.md
- docs/deprecated_integrations/mmcloud_plugin/mmcloud_plugin_example.md
- docs/deprecated_integrations/snowflake_plugin/index.md
- docs/deprecated_integrations/snowflake_plugin/snowflake_plugin_example.md
- docs/index.md
Moves deprecated integrations docs to flyte from flytesnacks and uses `rli` (remoteliteralinclude) directive to include code from code files in flytesnacks repo.
Merge this PR first, then merge https://github.com/flyteorg/flytesnacks/pull/1655
https://flyte--5283.org.readthedocs.build/en/5283/deprecated_integrations/index.html
> Move deprecated integrations docs to flyte

- docs/deprecated_integrations/snowflake_plugin/snowflake_plugin_example.md
Line number ranges are off by one in Snowflake plugin example doc.
Update line numbers in `rli` directive in Snowflake plugin example doc.
TK
> Fix rli number ranges in Snowflake plugin example doc

- flyteplugins/go/tasks/pluginmachinery/flytek8s/container_helper.go
- flyteplugins/go/tasks/pluginmachinery/flytek8s/container_helper_test.go
- flyteplugins/go/tasks/plugins/array/awsbatch/transformer.go
```py
@task(
requests=Resources(cpu="11", mem="11Gi", gpu="11"),
)
def foo():
...
@workflow
def test_wf():
foo().with_overrides(requests=Resources(cpu="13", mem="13Gi", gpu="13"), limits=Resources(cpu="13", mem="13Gi", gpu="13"))
```
The resulting task pod - as expected - uses the following resources:
```yaml
resources:
limits:
cpu: "13"
memory: 13Gi
nvidia.com/gpu: "13"
requests:
cpu: "13"
ephemeral-storage: 2Gi
memory: 13Gi
nvidia.com/gpu: "13"
```
If I now add `pod_template=PodTemplate(labels={"foo": "bar"})` to the task decorator, I would expect the same pod resources but the creation of the pod actually fails:
```
E0221 13:50:14.805583  427772 workers.go:103] error syncing 'development/f454d2131ec484221b70': failed at Node[n0]. RuntimeExecutionError: failed during plugin execution, …
```
> Fix broken gpu resource override when using pod templates

- flyteplugins/go/tasks/plugins/webapi/databricks/plugin.go
https://flyte-org.slack.com/archives/C05BN3A92SE/p1713794999621399
Flyte won't retry the Databricks job
Make Databricks task retryable
local sandbox
NA
NA
> fix(databricks): Handle FAILED state as retryable error

- .github/workflows/checks.yml
- .github/workflows/flyteidl-checks.yml
- .github/workflows/unit-tests.yml
- boilerplate/flyte/golang_test_targets/Makefile
The ingestion of code coverage data was happening in two places:
1. via the `test_unit_codecov` make target defined in [boilerplate](https://github.com/flyteorg/flyte/blob/master/boilerplate/flyte/golang_test_targets/Makefile#L57)
2. via the gh action defined in https://github.com/flyteorg/flyte/blob/master/.github/workflows/unit-tests.yml#L34-L41
As of a few days ago we started seeing the upload done in 1. timeout and block the execution of the remaining steps in the gh workflow, e.g. [[1]](https://github.com/flyteorg/flyte/actions/runs/8876065707/job/24366875281?pr=5126).
That said, 2. was never configured properly. For example, we were reusing the `flags` field, which essentially caused the code coverage data to be overwritten. Another problem was that we never used the correct name …
> Fix uploading of code coverage data

- flyteidl/pyproject.toml
flyteidl claims Python 3.12 support, as does flytekit, but protobuf<5.0.0 only supports up to Python 3.11.
Remove the upper bound on flyteidl's protobuf dependency to enable Python 3.12 support.
Existing/standard CI tests.
n/a
n/a
n/a
n/a
> Remove upper bound on flyteidl's protobuf dependency

- .run/single-binary.run.xml
Running single binary locally in GoLand is useful.
This PR just adds a file to configure single-binary to be run as a "go build" configuration in GoLand. This is useful for both running and debugging.
> Add GoLand single-binary configuration

- flytectl/Makefile
- flytectl/cmd/compile/compile_test.go
- flytectl/cmd/create/execution_test.go
- flytectl/cmd/create/execution_util_test.go
- flytectl/cmd/create/project_test.go
- flytectl/cmd/demo/exec_test.go
- flytectl/cmd/demo/status_test.go
- flytectl/cmd/demo/teardown_test.go
- flytectl/cmd/get/execution_test.go
- flytectl/cmd/get/launch_plan_test.go
- flytectl/cmd/get/matchable_cluster_resource_attribute_test.go
- flytectl/cmd/get/matchable_execution_cluster_label_test.go
- flytectl/cmd/get/matchable_execution_queue_attribute_test.go
- flytectl/cmd/get/matchable_plugin_override_test.go
- flytectl/cmd/get/matchable_task_resource_attribute_test.go
- flytectl/cmd/get/matchable_workflow_execution_config_test.go
- flytectl/cmd/get/node_execution_test.go
- flytectl/cmd/get/project_test.go
- flytectl/cmd/get/task_test.go
- flytectl/cmd/get/workflow_test.go
- flytectl/cmd/testutils/test_utils.go
- flytectl/cmd/update/execution_test.go
- flytectl/cmd/update/launch_plan_meta_test.go
- flytectl/cmd/update/launch_plan_test.go
- flytectl/cmd/update/matchable_cluster_resource_attribute_test.go
- flytectl/cmd/update/matchable_execution_queue_attribute_test.go
- flytectl/cmd/update/named_entity_test.go
- flytectl/cmd/update/task_meta_test.go
- flytectl/pkg/sandbox/status_test.go
https://github.com/flyteorg/flyte/issues/5316
We fixed a few of the flytectl issues in https://github.com/flyteorg/flyte/pull/5309, but decided to merge that PR with a few unit tests failing. This PR fixes them.
We have a few flytectl unit tests that rely on a [TestStruct](https://github.com/flyteorg/flyte/blob/master/flytectl/cmd/testutils/test_utils.go#L29-L43) to capture what's written to standard output and error, but if those file descriptors are not restored then the respective test suites would fail every now and then. In this PR we add a defer statement to ensure that the original file descriptors are restored to the os package.
Unit tests running in a loop locally (e.g. `seq 100 | xargs -n1 make test_unit`).
> Fix flytectlt tests

- docs/_templates/base.html
N/A - Happy to file an issue or update with an issue number if needed.
This PR updates the RunLLM chat widget to use the hot key Mod + j to activate the chat on the documentation site.
This means that users can use CMD + j on Mac and CTRL + j on Windows to view and interact with the docs chat.
I've created a Github codespace to set up the project and edit the code here.
If there are preview links available to view documentation I would appreciate some help getting that link so that I can whitelist the domain for our recaptcha based authentication to do a proper test of everything.
> Updates RunLLM chat widget to use Mod + j as shortcut

- flyteplugins/go/tasks/pluginmachinery/internal/webapi/core.go
- flyteplugins/go/tasks/pluginmachinery/internal/webapi/core_test.go
NA
Increase maxWorkers limit to 10000 to run more agent tasks in parallel.
Remote cluster
```python
from flytekit import workflow, task, LaunchPlan
from flytekitplugins.dummy_agent import Sleep
@task(task_config=Sleep(duration=0.5))
def sleep_task() -> str:
return "Hello World!"
@workflow()
def sleep_wf():
for i in range(100):
sleep_task()
@workflow
def load_test_wf():
sleep_lp = LaunchPlan.get_or_create(
name="fixed_inputs", workflow=sleep_wf, max_parallelism=100
)
for i in range(50):
sleep_lp()
```
NA
NA
> perf(webapi): Increase maxWorkers limit to 10000

- .github/workflows/generate_flyte_manifest.yml
- .github/workflows/go_generate.yml
- .github/workflows/integration.yml
- .github/workflows/lint.yml
- .github/workflows/single-binary.yml
- .github/workflows/tests.yml
- .github/workflows/unit-tests.yml
- flytectl/.github/workflows/checks.yml
NA
we didn't cache Go package in the CI
Upgrade `setup-go` to v4. V4 has enabled caching by default.
https://github.blog/changelog/2023-03-24-github-actions-the-setup-go-action-now-enables-caching-by-default/
CI
NA
NA
> ci: Reduce build times by 40%

- flyteadmin/auth/authzserver/provider.go
- flyteadmin/auth/authzserver/provider_test.go
Closes #4800 
So flyteadmin errors out nicely and with information about the error instead of with a stack trace, which is difficult to follow for people not used to code.
I'm adding some missing error handling.
Having both an empty and an invalid `PrivateKeyPEM` variable resulted in the stack trace below:
```
time="2024-01-31T13:19:12Z" level=info msg="Using config file: [/etc/flyte/config/flyteadmin_config.yaml]"
{"data":{"src":"service.go:71"},"message":"setting metrics keys to [project domain wf task phase tasktype runtime_type runtime_version app_name]","severity":"INFO","timestamp":"2024-01-31T13:19:12Z"}
{"data":{"src":"service.go:302"},"message":"Serving Flyte Admin Insecure","severity":"INFO","timestamp":"2024-01-31T13:19:12Z"}
panic: runtime error: invalid memory address or nil …
```
> chore: handle empty or invalid secrets nicely

- .github/workflows/checks.yml
Let's make sure the job used to build images during releases is exercised at PR time. Also, be explicit about the execution requirements for flyteadmin integration tests.
Bring back the `build_docker_images` job removed in https://github.com/flyteorg/flyte/pull/5327/ and also rename the jobs related to running flyteadmin integration tests.
> Bring back image build job and be explicit about flyteadmin int tests

- datacatalog/go.mod
- datacatalog/go.sum
- docker/sandbox-bundled/bootstrap/go.mod
- docker/sandbox-bundled/bootstrap/go.sum
- flyteadmin/go.mod
- flyteadmin/go.sum
- flytectl/go.mod
- flytectl/go.sum
- flyteidl/go.mod
- flyteidl/go.sum
- flyteplugins/go.mod
- flyteplugins/go.sum
- flytepropeller/go.mod
- flytepropeller/go.sum
- flytestdlib/go.mod
- flytestdlib/go.sum
A few dependabot alerts will be fixed by this.
> Bump golang.org/x/net to v0.23.0

- docs/user_guide/data_types_and_io/structureddataset.md
https://github.com/flyteorg/flyte/issues/4241
https://github.com/flyteorg/flytekit/pull/2252
https://github.com/flyteorg/flytesnacks/pull/1657
Add `structured_dataset_nested_type` examples in documentation.
https://github.com/flyteorg/flytekit/pull/2252
Demonstrate how to use `nested_types` in `structured_dataset`
https://github.com/flyteorg/flytekit/pull/2252/files#diff-e78d93a6e6cd2463cd5fc51973434c29ece29d05fe6b36691d6d19860386f938
`make dev-docs`
https://github.com/flyteorg/flytekit/pull/2252
https://github.com/flyteorg/flytesnacks/pull/1657
https://flyte--5269.org.readthedocs.build/en/5269/user_guide/data_types_and_io/structureddataset.html#structured-dataset
> docs: add `nested_type` example in `data_types_and_io/structured_dataset.py`

- flytectl/cmd/get/execution.go
- flytectl/go.mod
- flytectl/go.sum
- flytectl/pkg/bubbletea/bubbletea_pagination.go
- flytectl/pkg/bubbletea/bubbletea_pagination_util.go
The get function takes more time to fetch data from the remote server as the amount increases, hence we only fetch 100 rows initially, and prefetch 100 rows of data at once while the user scrolls through pages to enhance the user experience. 
For testing run:
```bash
make compile
./bin/flytectl get execution -p my-project -d development -i
```
We initially fetch the first 100 rows when the paginator is called and start to prefetch the next batch (next 100 rows).
Prefetch will be triggered when the current page exceeds a prefetch threshold.
The first or last batch will be discarded when it exceeds the cache limit (currently set to 1000 rows).
We added a loading animation to indicate the fetching process is ongoing.
Users can use --filter.page flag to specify their starting page, if not …
> Add prefetch functionality for paginator

- docs/user_guide/advanced_composition/map_tasks.md
Confusion regarding map task caching and regular task caching.
Docs change 
No tests for docs
> add maptask cache clarification

- docs/_templates/base.html
- docs/_templates/page.html
Instead of using scarf pixel directly, this adds Google GTM to allow us to experiment with different code snippets from the GTM side.
Used the deployed change from the PR.
Looked at the source code to confirm GTM is installed
Installed scarf through GTM and noticed it get injected.
> Add Google Tag Manager

- deployment/stats/prometheus/flyteadmin-dashboard.json
- deployment/stats/prometheus/flytepropeller-dashboard.json
- stats/flyteadmin.dashboard.py
- stats/flytepropeller.dashboard.py
There are a few issues with the dashboards as is. This includes some bugs and some outdated metric names. 
- This is a series of incremental changes I ended up making when trying to understand flyte propeller performance and debug a problem on our network. 
- Add a few extra graphs/shuffle some around a bit. 
- Fix some aggregation bugs e.g. missing `rate` funciton while the title says rate
- Fix some axis labels. 
- Correct some metrics names based on flyte-core 1.11
- Add a few descriptions. 
- Probably this is still a long way from perfect but I think its probably still worth contributing.
> Grafana dashboard updates

- .github/workflows/checks.yml
- .github/workflows/flytectl-release.yml
- .github/workflows/flyteidl-release.yml
- flytectl/.goreleaser.yml
We need to be able to release flytectl from the monorepo, this includes the CI checks used to validate the changes.
This PR adds the validation CI tests to run at regular PR time and also a specific gh workflow that will watch for tags of a specific format to run the actual flytectl release.
Notice that we moved to `goreleaser-pro` as the driver, this simplifies the process of [releasing from a monorepo](https://goreleaser.com/customization/monorepo/) immensely (you just have to look the changes needed in flytectl/.goreleaser.yml).
The release process for `flytectl` will involve creating a tag with a specific format, e.g. in order to release version 1.2.3 of the `flytectl` we should push a tag like `flytectl/v1.2.3`. Notice that `flytectl` is going to be versioned separately from the …
> [monorepo] Move flytectl gh workflows to monorepo

- script/release.sh
https://flyte-org.slack.com/archives/CP2HDHKE1/p1715374736546419
The version of the flyteagent tag is not aligned with other flyte components (flytepropeller, flyteadmin, etc)
NA
NA
> Update flytekit tag

- .github/workflows/end2end.yml
- .github/workflows/single-binary.yml
- .github/workflows/validate-helm-charts.yaml
Use monorepo-aware version of `unionai/flytectl-setup` 
https://github.com/flyteorg/flyte/actions/runs/9106232154/job/25033105789?pr=5377
> Bump version of unionai/flytectl-setup to 0.0.3

- docs/conf.py
flytectl is now built and released from the monorepo. Time to build the flytectl monodocs from the monorepo.
> Build flytectl monodocs from monorepo

- flytectl/cmd/upgrade/upgrade_test.go
Related to https://github.com/flyteorg/flyte/issues/5372
Unit tests in master shouldn't fail, so while we figure out how to fix `flytectl upgrade` we should skip those tests.
> Skip flytectl upgrade tests

- docs/user_guide/development_lifecycle/decks.md
Removes reference to source code renderer from Decks doc since it was removed from flytesnacks example code in https://github.com/flyteorg/flytesnacks/pull/1674
https://github.com/flyteorg/flytesnacks/pull/1674
TK
> Remove source code renderer section from Decks article

- docs/deployment/agents/index.md
- docs/deployment/agents/openai_batch.rst
- docs/user_guide/development_lifecycle/decks.md
Fixes https://github.com/flyteorg/flyte/issues/5274
To document the openai batch agent backend setup config.
Documentation updates.
> openai batch agent backend setup documentation

- flytectl/cmd/core/cmd.go
- flytectl/pkg/pkce/token_cache_keyring.go
- flyteidl/clients/go/admin/auth_interceptor.go
- flyteidl/clients/go/admin/auth_interceptor_test.go
- flyteidl/clients/go/admin/cache/mocks/token_cache.go
- flyteidl/clients/go/admin/cache/token_cache.go
- flyteidl/clients/go/admin/cache/token_cache_inmemory.go
- flyteidl/clients/go/admin/client_builder.go
- flyteidl/clients/go/admin/client_builder_test.go
- flyteidl/clients/go/admin/client_test.go
- flyteidl/clients/go/admin/deviceflow/token_orchestrator_test.go
- flyteidl/clients/go/admin/pkce/auth_flow_orchestrator_test.go
- flyteidl/clients/go/admin/token_source_provider.go
- flyteidl/clients/go/admin/token_source_provider_test.go
- flyteidl/clients/go/admin/tokenorchestrator/base_token_orchestrator.go
- flyteidl/clients/go/admin/tokenorchestrator/base_token_orchestrator_test.go
Reverts flyteorg/flyte#5388
as this is causing issues with headless linux.
> Revert "Ensure token is refreshed on Unauthenticated"

- docs/flyte_agents/developing_agents.md
Fix minor doc link issue found here: https://docs.flyte.org/en/latest/flyte_agents/developing_agents.html
> Fix doc link to testing agent on local cluster

- docs/flyte_agents/developing_agents.md
This pull request brings the example agent dockerfile up to date with what is [used on master](https://github.com/flyteorg/flytekit/blob/master/Dockerfile.agent) such that it will run on k8s without blowing up. 
The prometheus-client module is required by the agent code and the health checking service is required for k8s health checking it seems.
> Update the example Flyte agent Dockerfile

- docs/deployment/plugins/k8s/index.rst
N/A
When I tried to run a tensorflow task using `flytectl demo start --dev`, it throws the following exception
Install the stable release of kubeflow operator.
> docs(kubeflow): Fix kubeflow webhook error

- charts/flyte-core/README.md
- charts/flyte-core/values.yaml
The existing configuration for enabling the agent service was out of date and would result in unhandled tasks in propeller. This updates the helm chart to include default values for the agent service `supportedTaskTypes` which are required to be configured for tasks to be handled correctly by propeller.
> Update core helm chart for propeller configuration of agent service

- monodocs-environment.lock.yaml
- monodocs-environment.yaml
This PR updates the monodocs lock file.
> update lock file

- flyteidl/pyproject.toml
Moving `flytectl` to the monorepo caused flyteidl build script to match the wrong tags to calculate the next version.
Use a specific git command to match only the flyteidl tags.
Ran locally. 
Before the fix:
```
~/repos/flyte/flyteidl master
❯ python -m build 2>/dev/null | grep "Successfully built"
Successfully built flyteidl-0.8.22.dev11+g0583f7743.tar.gz and flyteidl-0.8.22.dev11+g0583f7743-py3-none-any.whl
```
After the fix:
```
~/repos/flyte/flyteidl fix-flyteidl-weird-version
❯ python -m build 2>/dev/null | grep "Successfully built"
Successfully built flyteidl-1.12.1.dev38+ga46890bb0.tar.gz and flyteidl-1.12.1.dev38+ga46890bb0-py3-none-any.whl
```
Notice how `flytectl/0.8.21` is the latest git tag in the repo: https://github.com/flyteorg/flyte/releases/tag/flytectl%2Fv0.8.21.
> Use a different git command to match the flyteidl tags

- docs/user_guide/data_types_and_io/flytedirectory.md
We're seeing build failures (e.g. ) caused by https://github.com/flyteorg/flytesnacks/pull/1660.
Update line numbers to match new lines.
> [monodocs] Fix build failure

- flytectl/docs/source/overview.rst
After we moved flytectl to the monorepo we require `jq` to be installed to be able to filter out unwanted [Flyte releases](https://github.com/flyteorg/flyte/releases).
This PR just adds a warning to the "Other Operating Systems" tab in the docs.
I tried generating the docs locally, but failed.
> Indicate that jq is now required to install flytectl via the script

- flytestdlib/cache/auto_refresh_test.go
NA
This test sometimes fail
Use `EventuallyWithT` in the test
https://pkg.go.dev/github.com/stretchr/testify/assert#Assertions.EventuallyWithT
```bash
cd flytestdlib
go test ./cache/... -count 10
```
NA
NA
> Fix flaky auto_refresh_test

- flyteplugins/go/tasks/plugins/k8s/dask/dask_test.go
- flyteplugins/go/tasks/plugins/k8s/kfoperators/mpi/mpi_test.go
- flyteplugins/go/tasks/plugins/k8s/kfoperators/pytorch/pytorch_test.go
- flyteplugins/go/tasks/plugins/k8s/kfoperators/tensorflow/tensorflow_test.go
- flyteplugins/go/tasks/plugins/k8s/ray/ray_test.go
- flyteplugins/go/tasks/plugins/k8s/spark/spark_test.go
Add tests for PR #4726. As a separate PR because the PR is getting too long already.
The added tests test the fixes explained in [this](https://github.com/flyteorg/flyte/pull/4726#discussion_r1555020189) comment.
> Add tests for PR #4726

- docs/deployment/deployment/multicluster.rst
- flyteadmin/pkg/flytek8s/client.go
- flyteadmin/pkg/runtime/config_provider_test.go
- flyteadmin/pkg/runtime/interfaces/cluster_configuration.go
- flyteadmin/pkg/runtime/testdata/clusters_config.yaml
When configuring a [Flyte multi-cluster deployment](https://docs.flyte.org/en/latest/deployment/deployment/multicluster.html), one might want to use the control plane cluster also to schedule workflows.
Currently, flyteadmin is not able to use in-cluster credentials for this use case. Instead, one has to go through the much more cumbersome credentials configuration process required for data plane clusters (see [here](https://docs.flyte.org/en/latest/deployment/deployment/multicluster.html#control-plane-configuration)).
This PR allows flyteadmin to just use in-cluster credentials instead.
---
As briefly discussed in the last contributors' sync @wild-endeavor.
* A flyteadmin image with this change has been in use in our multi-cluster deployment. 
* Adapted unit test.
> Feat: Allow using in-cluster creds in control plane cluster in a multi-cluster deployment

- flyteadmin/auth/handlers.go
- flyteadmin/auth/handlers_test.go
Example: Closes #5456
Fixes resolution of OpenID metadata URL redirect.
Without the change tests would fail:
```
expected: "https://login.microsoftonline.com/abc/v2.0/.well-known/openid-configuration"
actual  : "https://login.microsoftonline.com/abc/.well-known/openid-configuration"
```
Append a trailing slash to `BaseURL` before running `ResolveReference`
Unit tests only.
> Make BaseURL insensitive to trailing slashes for metadata endpoint redirect.

- flyteplugins/go/tasks/pluginmachinery/internal/webapi/state.go
- flyteplugins/go/tasks/pluginmachinery/webapi/plugin.go
This pull request just cleans up some confusing/unused field as well as a documentation fix for the Web API plugin contract.
> Minor cleanup for Web API plugins

- docker/sandbox-bundled/Dockerfile
A user on OSS slack mentioned that they were trying to use `RestartPolicy` to configure an init container, but that field was not behaving properly in the demo cluster. 
Bump the version of k3s to 1.29.0, which is the first version of k8s that supports that field in an init container.
I built the demo cluster locally (`make -C docker/sandbox-bundled build` from the root) and used that to kick off the following workflow (notice the use of `restart_policy` in the init container):
```python
from flytekit import task, workflow, PodTemplate
from kubernetes.client import V1PodSpec, V1Container
@task(
pod_template=PodTemplate(
pod_spec=V1PodSpec(
containers=[
V1Container(
name="primary",
)
],
init_containers=[
V1Container(
image="alpine",
name="init",
command=["/bin/sh"],
args=["-c", 'echo "I\'m …
```
> Bump k3s version to 1.29.0

- flyteplugins/go/tasks/plugins/webapi/agent/client.go
- flyteplugins/go/tasks/plugins/webapi/agent/plugin.go
Comment in the description below.
single binary.
> [flyteagent] Remove redundant code in Agent

- flytepropeller/pkg/controller/nodes/array/node_execution_context.go
_NA_
ArrayNode strips the collection from the output type because it currently relies on registering a separate task with a wrapped collection to satisfy node output validators. The bug is that this stripped did no deep copy, so if multiple nodes stripped the outer collection, we would end up stripping mutliple layers if they existed.
In this PR we deep copy the interface of the TaskTemplate to ensure that multiple subNode executions do not strip mutliple `List` from the output variable type.
The following workflow is a minimal repro:
```
@task(cache=True, cache_version="1.0")
def bAr(a: int) -> List[int]:
return [a + 1, a + 2]
@task(cache=True, cache_version="1.0")
def bAr2(a: int) -> List[int]:
return [a + 1, a + 2]
@workflow
def my_wf_2(a: int) -> List[List[int]]:
x = bAr(a=a)
return …
```
> deep copying arraynode tasktemplate interface

- .github/workflows/single-binary.yml
- flyteadmin/pkg/repositories/config/migrations.go
NA
`value` is a primary key in the execution_tag table, so we can't insert a NULL value into that column. 
Insert an empty string instead.
local sandbox 
NA
NA
> fix(migrations): Correct NULL to empty string in SQL insert

- flytepropeller/pkg/controller/nodes/task/k8s/plugin_collector.go
Closes #5429
Correctly sets apiVersion to include group; fixes the `failed to list objects for ...` warning in `collect`
`ResourceLevelMonitor` includes `schema.GroupVersionKind` (gvk). The changes here correctly set the `apiVersion` in `collect` by utilizing `gvk.GroupVersion().String()`, which puts "group" and "version" into a single "group/version" string 
https://github.com/kubernetes/apimachinery/blob/703232ea6da48aed7ac22260dabc6eac01aab896/pkg/runtime/schema/group_version.go#L178-L182
Built flytepropeller image with this change, deployed, ensured resources were correctly listed and ensured the aforementioned warning didn't appear.
> Include group in apiVersion in plugin_collector

- flyteadmin/pkg/manager/impl/execution_manager.go
- flyteadmin/pkg/manager/impl/execution_manager_test.go
Today if a user creates an execution with the `execution-cluster-label`, then the execution launches in the specified cluster. However, if the workflow has a reference workflow in the workflow, that reference workflow launches in the default cluster since this information isn't passed along. This change fixes that issue by inheriting the cluster label from the source.
Without this change, part of the workflow will run in cluster 1 and part in cluster 2.
In a local cluster, a workflow was launched with a reference workflow and the reference workflow launched in the correct cluster.
> Inherit execution cluster label from source execution

- docs/conf.py
Closes https://github.com/flyteorg/flyte/issues/4864
Update the `mermaid_init_js` configuration to initialize mermaid on page load.
> fix broken mermaid diagrams

- flytectl/cmd/update/project.go
- flytectl/docs/source/gen/flytectl_update_project.rst
OSS docs mention `uctl` ([cli for Union.ai](https://github.com/unionai/uctl)) instead of `flytectl` in two locations.
> Fix: replace `uctl` with  `flytectl` in OSS docs

- .github/workflows/single-binary.yml
NA
We spend between 1 and 2 minutes installing python packages to run single-binary tests. Let's cut that to 1 second.
Use uv to install flytekit and other dependencies necessary to run functional tests in single-binary.
> Use uv in single-binary CI

- flyteplugins/go/tasks/plugins/k8s/ray/ray.go
- flyteplugins/go/tasks/plugins/k8s/ray/ray_test.go
NA
The default service account is not being used if autoscale is enabled in the ray task.
Use default service account in the config if it's not being set.
sandbox
```python
config = RayJobConfig(
worker_node_config=[WorkerNodeConfig(group_name="test_group", replicas=3, min_replicas=0, max_replicas=10)],
runtime_env={"pip": ["numpy"]},
enable_autoscaling=True,
shutdown_after_job_finishes=True,
ttl_seconds_after_finished=20,
)
```
NA
NA
> fix(ray): Use default svc account if not set in task metadata

- charts/flyte-core/README.md
- charts/flyte-core/templates/_helpers.tpl
- charts/flyte-core/templates/clusterresourcesync/deployment.yaml
- charts/flyte-core/templates/console/deployment.yaml
- charts/flyte-core/templates/console/service-monitor.yaml
- charts/flyte-core/templates/console/service.yaml
- charts/flyte-core/templates/propeller/deployment.yaml
- charts/flyte-core/templates/propeller/webhook-hpa.yaml
- charts/flyte-core/templates/propeller/webhook.yaml
- charts/flyte-core/values.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_controlplane_generated.yaml
- deployment/eks/flyte_helm_dataplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_controlplane_generated.yaml
- deployment/gcp/flyte_helm_dataplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
- docker/sandbox-bundled/manifests/complete-agent.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
- flyteadmin/cmd/entrypoints/clusterresource.go
- flyteadmin/pkg/clusterresource/controller.go
Various Helm chart updates deemed appropriate to upstream from Union internal usage.
* Add flyteconsole livenessProbe and readinesProbe to mitigate downtime during releases or updates. Default to no probes to preserve backward-compatible behavior.
* Add flyte-console prometheus port and service monitor 
* Add flyte-pod-webhook HPA
* Add Prometheus annotations to propeller, webhook, and syncresources
All three patches (commits) were tested individually within Union internal flyte deployment
> Helm chart updates related to Prometheus, Webhook HPA, and Flyteconsole probes

- docs/user_guide/productionizing/configuring_logging_links_in_the_ui.md
In https://github.com/flyteorg/flyte/pull/4726 I added config options to log links to allow showing certain log links during the queueing/initializing phase or to hide them once the task terminates.
This PR documents these configuration options.
> Doc: Explain how lifetime of logging links is configured

- flyteadmin/pkg/errors/errors.go
- flyteadmin/pkg/errors/errors_test.go
- flyteadmin/pkg/manager/impl/workflow_manager_test.go
NA
To improve the error message
Add name to ExistsDifferentStructureError message
Unit test
NA
NA
> Add name to ExistsDifferentStructureError message

- .github/workflows/create_release.yml
In https://github.com/flyteorg/flyte/pull/5509/ we added a case to extract the version of the flyteagent image, but the `yq` expression was incorrect.
This PR modifies the path used to extract the flyteagent image tag from the values file.
Ran from root:
```
❯ yq eval '.image.tag' charts/flyteagent/values.yaml
1.12.3
```
> Fix flyteagent version extraction from helm chart in create_release.yml

- .github/workflows/flyteidl-release.yml
https://linear.app/unionai/issue/DX-842/fix-flyteidl-pypi-release
flyteidl releases to pypi are currently broken since https://github.com/flyteorg/flyte/pull/5419. This is due to the fact that the flyteidl build process expects git tags to be formatted a certain way, but we use the Flyte release tag to kick off the flyteidl push to pypi process. 
This causes an issue in CI where we can't find the correct tag to build the flyteidl wheel, e.g. for the 1.13.0-rc0 beta release we saw [this error](https://github.com/flyteorg/flyte/actions/runs/9685664227/job/26726254035#step:5:1018):
```
Successfully built flyteidl-0.1.dev1+gce5eb03.tar.gz and flyteidl-0.1.dev1+gce5eb03-py3-none-any.whl
Uploading distributions to https://upload.pypi.org/legacy/
Uploading …
```
> Push flyteidl to pypi and npm on `flyteidl/v*.*.*` tags instead of on Flyte releases

- docs/user_guide/data_types_and_io/dataclass.md
It should be `from dataclasses_json import dataclass_json`.
> Fix Dataclass Doc about `dataclass_json` import problem

- flytectl/RELEASE.md
We moved [flytectl to the monorepo ](https://github.com/flyteorg/flyte/pull/5301)but never documented how that affected the release process.
Document how to release flytectl from the monorepo.
> Document how to release flytectl

- docs/_templates/base.html
This PR updates the RunLLM widget configuration to use our new widget.runllm.com url. 
Tested by adding URL to the docs site and making sure that the docs widget renders.
If you would like to test in a staging domain, please let me know so I can add to our ReCAPTCHA validation.
This change is really just updating where you get the latest bits of the runllm widget from.
> chore: update runllm widget configuration

- flyteadmin/pkg/repositories/gormimpl/named_entity_repo.go
- flyteadmin/pkg/repositories/gormimpl/signal_repo.go
- flyteadmin/pkg/repositories/gormimpl/task_execution_repo.go
I have been working in the DB code to implement some RBAC and I noticed some TODOs about using `db.WithContext`. I audited the code and added `db.WithContext` for any missing DB methods. This should ensure that all DB calls support distributed tracing.
> [flyteadmin] Use WithContext in all DB calls

- charts/flyteagent/README.md
- charts/flyteagent/values.yaml
- deployment/agent/flyte_agent_helm_generated.yaml
- docker/sandbox-bundled/manifests/complete-agent.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
I got OOM killed When I started the flyte sandbox with the agent pod.
It is not a good user experience for agent users when we run lots os agent tasks concurrently. 
As we support more agents in flytekit, we will get OOM killed.
Add more memory limits for `flyteagent` pod.
build an image of flyte sandbox.
```zsh
cd docker/sandbox-bundled
make build
```
> Increase more memory limits in flyteagent

- docs/user_guide/advanced_composition/map_tasks.md
Updated docs to be in line with current array node map task functionality
> Updated map task information to indicate array node is now the default and optional return type

- script/prepare_artifacts.sh
I am currently attempting to get our fork of Flyte to push helm charts to our artifact store and I ran into some issues. This pull request fixes two issues.
1. Updates the script to find/replace the version of the flyteagent helm chart such that `flyte-core` is able to find a matching version of the relative helm chart reference when doing `helm dependency update`. This should publish an actual updated version of the `flyteagent` helm chart instead of overwriting it (and potentially breaking peoples deployments) : https://artifacthub.io/packages/helm/flyte/flyteagent
3. Updates the script to patch each respective README instead of continuously overwriting the `flyte-core` README. This should fix the broken README that is currently live for `flyte-core`: …
> Fix issues with helm chart release process

- docs/_templates/file_types.rst
https://linear.app/unionai/issue/DOC-480/fix-rendering-of-flytedirectory-api-doc-page-in-flyte-docs
[FlyteDirectory API docs page](https://docs.flyte.org/en/latest/api/flytekit/generated/flytekit.types.directory.FlyteDirectory.html) is rendering incorrectly
Adding FlyteDirectory to the if then logic of the template that produces the rendered page
Local build
Equivalent in flytekit repo:
https://github.com/flyteorg/flytekit/pull/2584
> Add FlyteDirectory to file_types.rst template

- charts/flyte-core/README.md
- charts/flyte-core/templates/propeller/deployment.yaml
- charts/flyte-core/templates/propeller/service.yaml
- charts/flyte-core/templates/propeller/webhook.yaml
- charts/flyte-core/values.yaml
- docker/sandbox-bundled/manifests/complete-agent.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
We ran into an issue where we lost metrics when we configured propeller's `prof-port` to be different than the default value. There's a couple issues here. 
1. The service monitor is hardcoded to 10254
2. The prometheus configuration gives the illusion that the prometheus server port is configured independently from the `prof-port`, but the prometheus server is always mounted on the `prof-port`. 
So this change simplifies the configuration and makes it less fragile in the event the the `prof-port` changes.
The rendered helm chart values have no diff.
> Remove confusing prometheus configuration options in helm charts 

- flyteadmin/pkg/manager/impl/util/single_task_execution.go
- flyteadmin/pkg/manager/impl/util/single_task_execution_test.go
It's counter-intuitive that a single task execution doesn't respect a task spec when creating the system-generated workflow but workflow compilation ordinarily does
See PR title.
Unit test
> Respect original task definition retry strategy for single task executions

- docs/index.md
Support for flytekit-java is driven by the community, so let's reflect that in the documentation.
Remove the `first-class` support from the docs, instead mention that flytekit-java is community-driven.
> Clarify the support for the Java/Scala SDK in the docs

- CHANGELOG/CHANGELOG-v0.14.0.md
- CHANGELOG/CHANGELOG-v0.17.0.md
- CHANGELOG/CHANGELOG-v0.19.4.md
- CHANGELOG/CHANGELOG-v1.0.0.md
Hello
I found some spelling issues in your docs.
Glad I could help.
> Fix spelling issues

- charts/flyte-binary/templates/clusterrole.yaml
1. Flyte was failing to create service accounts on EKS since it didn't have permissions to do so
2. The service account template in the Single Cluster Simple Cloud Deployment [`eks-starter.yaml`](https://github.com/flyteorg/flyte/blob/master/charts/flyte-binary/eks-starter.yaml) file was failing for the above reason
Give the flyte binary cluster role permissions to create new service accounts.
Tested on an internal kubernetes cluster.
Before:
After:
> Give flyte binary cluster role permission to create service accounts

- flyteadmin/pkg/manager/impl/util/single_task_execution.go
Make the intent of single task retry check more clear
Remove unnecessary checks. Since `core.RetryStrategy` is a protobuf message we assume that calls to `Get*` are guarded against `nil`.
> Simplify single task retry strategy check

- deployment/sandbox-binary/flyte_sandbox_binary_helm_generated.yaml
- docker/sandbox-bundled/manifests/complete-agent.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
The `generate_helm` CI check was not marked as required, so it failed in https://github.com/flyteorg/flyte/pull/5579 but the PR was merged nonetheless.
I marked the `generate_helm` CI check as required and regenerated helm charts via `make helm`.
> Fix failures in `generate_helm` CI check

- docs/user_guide/productionizing/configuring_access_to_gpus.md
The purpose is to bring the information contained in the original flytekit accelerators PR (https://github.com/flyteorg/flyte/pull/4172) and complement with learnings from testing the feature on a live environment with access to GPU devices.
The "How it works" section for each use case, should speak to the platform engineers tasked with preparing the infrastructure so Flyte users can request accelerators from Python decorators.
Tested on AKS using both V100 and A100 GPUs.
> Update GPU docs

- flyteadmin/pkg/manager/impl/execution_manager.go
- flyteadmin/pkg/runtime/interfaces/application_configuration.go
- flyteadmin/pkg/workflowengine/impl/k8s_executor.go
- flyteadmin/pkg/workflowengine/impl/k8s_executor_test.go
- flyteadmin/pkg/workflowengine/interfaces/executor.go
- flytepropeller/pkg/apis/flyteworkflow/v1alpha1/workflow.go
- flytepropeller/pkg/controller/workflow/executor.go
Flyte allows configuring grpc message sizes, so in theory a workflow could be created with excessively large inputs that get stored inline in the CRD. Unfortunately etcd limits object sizes to 1.5Mb which we could potentially run afoul of.
Much in the same vein as the offloaded workflow closure, this change supports triggering a flyte execution with offloaded execution inputs, to reduce the CRD size.
See PR title
Ran single binary with the offloadInputs config set to `true` and ran an execution E2E. Verified the Flyte CRD had
```
offloadedInputs: s3://my-s3-bucket/metadata/flytesnacks/development/f87f46599099e4a9d9f8/inputs
```
and it succeeded
> Support offloading workflow CRD inputs

- docs/deployment/agents/index.md
- docs/deployment/agents/snowflake.rst
- docs/deprecated_integrations/snowflake_plugin/snowflake_plugin_example.md
> Snowflake agent Doc

- flytepropeller/pkg/controller/nodes/task/handler.go
- flytepropeller/pkg/controller/nodes/task/handler_test.go
I accidentally misconfigured one of my plugins and the result was a nil pointer because `pluginCore.LoadPlugin` errored and returned a nil `cp`. 
This pull request updates the logic such that it checks the error before operating on `cp`.
> Fix nil pointer when task plugin load returns error

- flytestdlib/cache/auto_refresh.go
- flytestdlib/cache/auto_refresh_test.go
This pull request improves the auto refresh cache's `sync` panic recovery logic such that it logs the stack trace for the panic that occurred. This makes it much easier to understand what exactly failed in the cache sync logic (ie. instead of  just something like "invalid memory address or nil pointer dereference")
> Log stack trace when refresh cache sync recovers from panic

- docs/flyte_agents/how_secret_works_in_agent.md
- docs/flyte_agents/index.md
> Explain how Agent Secret Works

- flyteadmin/auth/handlers.go
- flyteadmin/pkg/server/service.go
- flyteadmin/plugins/registry.go
By default most headers are dropped when invoking grpc, including `X-Request-Id` used for tracing and logging
Adds a grpc gateway CustomHeaderMatcher and optional override via plugin registry. This allows passing through additional request headers as grpc metadata. By default `X-Request-Id` is passed along.
Deployed to a cluster and verified the request id recorded in ingress is the same used by admin (previously was generated dynamically in admin middleware)
> Add CustomHeaderMatcher to pass additional headers

- .github/workflows/create_release.yml
- .github/workflows/flytectl-release.yml
- .github/workflows/flyteidl-release.yml
- flytectl/RELEASE.md
- flyteidl/RELEASE.md
Since the move to the monorepo we release flyteidl and flytectl by pushing git tags to the flyte repository, e.g. https://github.com/flyteorg/flyte/releases/tag/flyteidl%2Fv1.13.1b0 and https://github.com/flyteorg/flyte/releases/tag/flytectl%2Fv0.9.0. Pushing a git tag to a remote is essentially an untraceable action which is getting fixed in this PR.
We turn the github workflows used to release flyteidl and flytectl into manual workflows that take the version as an input.
> Turn flyteidl and flytectl releases into manual gh workflows

- CHANGELOG/CHANGELOG-v0.2.0.md
- CHANGELOG/CHANGELOG-v1.0.2-b1.md
- CHANGELOG/CHANGELOG-v1.1.0.md
- CHANGELOG/CHANGELOG-v1.3.0.md
Hello
I found and fixed some minor typos.
Br, Christina.
> docs: fix typo

- docs/core_use_cases/analytics.md
- docs/core_use_cases/machine_learning.md
- docs/flyte_fundamentals/visualizing_task_input_and_output.md
Related to https://github.com/flyteorg/flyte/issues/5618
`disable_deck` is deprecated.
Fixes docs to use `enable_deck=True`.
> Use enable_deck=True in docs

- .github/workflows/flyteidl-release.yml
We moved to a manual gh workflow in https://github.com/flyteorg/flyte/pull/5635, but the downstream gh jobs to the job that creates the git tag do not have access to it. This PR adds it.
Beta release `v1.13.1b1` tested in https://github.com/flyteorg/flyte/actions/runs/10309586794.
> Fix flyteidl release  checkout all tags

- docs/deployment/configuration/notifications.rst
This adds documentation for existing functionality for notifications in GCP.
`make docs` succeeds.
https://flyte--5545.org.readthedocs.build/en/5545/deployment/configuration/notifications.html#gcp-config
`GCP Config` section added.
> docs: add documentation for configuring notifications in GCP

- flyteadmin/pkg/clusterresource/controller.go
- flyteadmin/pkg/clusterresource/controller_test.go
- flyteadmin/pkg/clusterresource/testdata/imagepullsecrets_templatized.yaml
Previously the domain-specific defaults were applies first, such that any templatized string
e.g. 
```
imagePullSecrets
- name: {{ imagePullSecrets }}
```
got rendered with the _domain_ specific default, e.g.
```
imagePullSecrets
- name: default
```
and string substitution therefore found no eligible candidates for replacement in the subsequent custom template values loop.
Fixes ordering of custom template value substitution.
Tested on flyte sandbox and flyte deployment
> Fix ordering for custom template values in cluster resource controller

- flyteadmin/pkg/manager/impl/validation/execution_validator.go
- flyteadmin/pkg/manager/impl/validation/execution_validator_test.go
NA
Admin created the flyte CRD three times when using invalid labels in the execution and showed the error in flyteconsole.
We should validate labels before creating a CRD and return the error message to the client side (flytekit).
Validate labels before creating flyte CRD.
```bash
pyflyte run --labels flyte=gwllo:123 --remote flyte-example/getting_started.py wf
```
Before:
After:
NA
NA
> Validate labels before creating flyte CRD

- flytepropeller/pkg/controller/controller.go
This is an upstream of a fix that caused a panic in our fork.  The source of the panic is the `nil` value set for `tokenCache` when propeller is making the auth interceptor.
Something misleading is happening here though... this panic'ing auth interceptor is not actually being used.  These dial options are being returned up to the `authOpts` [variable here](https://github.com/flyteorg/flyte/blob/ff12f36d385cdcc0ad2acc86803940cd3812ea23/flytepropeller/pkg/controller/controller.go#L324).  These `authOpts` are then only used when talking to data catalog.  Data catalog is typically not authenticated, so this panic doesn't happen.
The actual auth interceptor that is being used by propeller is [here](https://github.com/flyteorg/flyte/blob/ff12f36d385cdcc0ad2acc86803940cd3812ea23/flyteidl/clients/ …
> Upstream Using InMemory token cache for admin clientset in propeller

- flytepropeller/events/admin_eventsink.go
- flytepropeller/events/admin_eventsink_test.go
- flytepropeller/events/errors/errors.go
- flytepropeller/pkg/controller/config/config.go
- flytepropeller/pkg/controller/config/config_flags.go
- flytepropeller/pkg/controller/config/config_flags_test.go
- flytepropeller/pkg/controller/nodes/array/handler.go
- flytepropeller/pkg/controller/nodes/array/handler_test.go
- flytepropeller/pkg/controller/nodes/node_exec_context.go
Upstreamed from https://github.com/unionai/flyte/pull/421
If there is an error updating a [FlyteWorkflow CRD](https://github.com/unionai/flyte/blob/6a7207c5345604a28a9d4e3699becff767f520f5/flytepropeller/pkg/controller/handler.go#L378), then the propeller streak ends without the CRD getting updated and the in-memory copy of the FlyteWorkflow is not utilized on the next loop.
[TaskPhaseVersion](https://github.com/flyteorg/flyte/blob/37b4e13ac4a3594ac63b7a35058f4b2220e51282/flytepropeller/pkg/apis/flyteworkflow/v1alpha1/node_status.go#L239) is stored in the FlyteWorkflow. This is incremented when there is an update to node/subnode state to ensure that events are unique. If the events stay in the same state and have the same TaskPhaseVersion, then they [get short-circuited and don't get …
> [BUG] array node eventing bump version

- flyteplugins/go/tasks/plugins/webapi/agent/plugin.go
- flyteplugins/go/tasks/plugins/webapi/agent/plugin_test.go
https://github.com/flyteorg/flyte/issues/5603
Agents may use the Resource object to pass some data back to flyte, but the `CustomInfo` field is not being passed on in Flyte.
Pass on the `CustomInfo` field in Flyte when receiving a response from agents.
Check that `custom_info` is correctly passed when calling `ListTaskExecutions`:
```
{
"taskExecutions": [
{
"id": {
"taskId": {
"resourceType": "TASK",
...
},
...
},
"closure": {
"phase": "SUCCEEDED",
"createdAt": "2024-07-29T15:55:54.386882596Z",
"updatedAt": "2024-07-29T15:58:43.680469958Z",
"customInfo": {
"foo": 100
},
...
},
...
}
],
...
}
```
https://github.com/flyteorg/flytekit/pull/2426
> Add custominfo to agents

- docs/flyte_fundamentals/tasks_workflows_and_launch_plans.md
This section in the docs is the only explanation of what launchplans are and its current version is not clear. This PR proposes a rephrasing of that definition.
> More concise definition of launchplan

- flytectl/cmd/register/register_util.go
Slack reported issue.
When hydrating the taskspec, the DataLoadingConfig is missing for K8s pod.
Add the field.
tested by packaging and registering against [development](https://flyte.com/console/projects/flytesnacks/domains/development/task/calculate_ellipse_area_python_template_style/version/dataloadingconfig_ctl2) cluster.
> [flytectl] DataConfig missing from TaskSpec

- cmd/single/start.go
- flytestdlib/contextutils/context.go
Closes https://github.com/flyteorg/flyte/issues/3991
Single binary emits execution-id labels to a bunch of flytepropeller and flyteadmin metrics, but since the golang prometheus golang client is setup in such a way that no metric is ever dropped (as described in https://github.com/prometheus/client_golang/discussions/920#discussioncomment-1448783), this ends up causing an apparent memory leak due to how these high cardinality metrics are stored in-memory.
This PR removes the execution-id label from the single binary metrics and adds a comment to hint at the potential problems caused by that setting.
I confirmed that the metric is not enabled by default in any component, nor is set in any of the shipped helm charts, while being left as a last resort debugging tool.
One could argue that we …
> Do not emit execution id label by default in single binary

- flyteplugins/go/tasks/plugins/testing/echo.go
NA
If `IsDefault` is True, the unknown task will always be handled by the echo plugin and always succeed.
```
{"json":{"exec_id":"fd2ed7347cfdb4e338f2","node":"n0","ns":"kk-flyte-dev3","res_ver":"9901776719","routine":"worker-
0","src":"handler.go:340","tasktype":"gnn","wf":"shuliang-
projects:development:gnn_agent_test.wf"},"level":"warning","msg":"No plugin found for Handler-type [gnn], defaulting to 
[echo]","ts":"2024-08-31T05:51:07Z"}
```
Set IsDefault to false
single binary
> Set IsDefault to False for echo plugin

- flytectl/cmd/create/execution_util.go
- flytectl/go.mod
- This PR follows up on [PR #5637](https://github.com/flyteorg/flyte/pull/5637) and migrates the default name generation functionality from `flytectl` to `flyteadmin`
- Remove default name generation in flytectl
https://github.com/flyteorg/flyte/pull/5637
> Move default execution name generation to flyteadmin

- flyteplugins/go/tasks/plugins/webapi/agent/client.go
We want to know whether the propeller received the expected `Supported Task Types` from each `Agent Deployment` and all `Supported Task Types`.
https://flyte-org.slack.com/archives/C06SYN9QJ5N/p1724970466413009
Add logs to track the `Supported Task Types` for each deployment and across all deployments.
Use `map[string]struct{}` to store supported task types because current flytekit will return `SupportedTaskTypes` and `supportedTaskCategories` with same metadata, which will make us get duplicate data
- single binary
- setup 2 endpoints, localhost:8000 and localhost:8001.
```yaml
agent-service:
defaultAgent:
endpoint: "localhost:8000"    
insecure: true
timeouts:
CreateTask: 100s
GetTask: 100s
defaultTimeout: 100s
agents:
custom_agent: …
```
> [flyteagent] Add Logging for Agent Supported Task Types

- flyteplugins/go/tasks/pluginmachinery/flytek8s/pod_helper.go
- flyteplugins/go/tasks/plugins/k8s/pod/container_test.go
Extends pod configuration to include init containers, ensuring that all containers in the pod, including init containers, receive the necessary customizations.
This will be especially useful for the ollama plugin to materialize `{{.input}}` in the pod template's init container command.
Adds a dedicated loop to handle init containers, ensuring that template values are properly materialized for all containers in the pod specification.
> extend pod customization to include init containers

- charts/flyte-binary/gke-starter.yaml
- deployment/test/flyte_generated.yaml
- docker/sandbox-bundled/manifests/complete-agent.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
- flyte-single-binary-local.yaml
- flytepropeller/propeller-config.yaml
I found that [gke-starter.yaml](https://github.com/flyteorg/flyte/pull/5730/files#diff-0e473e4042fb88a97366ad70c9698cd5e1f65db3c02ce9d8d3fdddd64581ed25) doesn't enable `agent-service` in it's helm chart, since `agent watcher` is merged and well-tested, we can enable `agent-service` whether agent is deployed or not.
add `agent-service` in every config that has `enabled-plugins` section.
```zsh
cd docker/sandbox-bundled
make build
flytectl demo start --force --disable-agent --image flyte-sandbox:latest
```
I will update the documentation in the follow-up PR.
> [flyteagent] Enable `agent-service` in every configuration 

- docs/flyte_agents/developing_agents.md
- docs/flyte_agents/testing_agents_in_a_local_development_cluster.md
https://flyte--5731.org.readthedocs.build/en/5731/flyte_agents/developing_agents.html#deploy-your-flyte-agent
https://flyte--5731.org.readthedocs.build/en/5731/flyte_agents/testing_agents_in_a_local_development_cluster.html#configuring-the-agent-service-in-development-mode
Since Agent Watcher is merged and released,  we don't need to configure by ourselves.
Remove configuration about `agent-service`.
> [Docs][flyteagent] Remove `agent-service` config in flyte agent documentation

- flytectl/cmd/get/launch_plan.go
- flytectl/cmd/get/launch_plan_test.go
- flytectl/cmd/get/workflow.go
- flytectl/cmd/get/workflow_test.go
- flytectl/pkg/ext/fetcher.go
- flytectl/pkg/ext/launch_plan_fetcher.go
- flytectl/pkg/ext/launch_plan_fetcher_test.go
- flytectl/pkg/ext/mocks/admin_fetcher_ext_interface.go
- flytectl/pkg/ext/workflow_fetcher.go
- flytectl/pkg/ext/workflow_fetcher_test.go
Closes https://github.com/flyteorg/flyte/issues/3972
Passing the --latest flag in when getting Workflows are not returning the latest but the opposite. 
We set a default filter for the get `FetchWorkflowLatestVersion` and also `FetchLaunchPlanLatestVersion`.
> Fix flytectl returning the oldest workflow when using --latest flag

- datacatalog/go.mod
- flytectl/go.mod
- https://github.com/flyteorg/flyte/pull/5032 updated builds to use Go 1.22 -- but in practice it looks like flytectl is being built with an outdated toolchain based on Go 1.22.0 instead of Go 1.22.5 or 1.22.6 (i.e. latest)
For instance, flytectl v0.9.0 reports being built with Go 1.22.0
>   ❯ go version -m -v 
>   flytectl flytectl: go1.22.0
Ensure the proper Go environment for security reasons
> Remove explict go toolchain versions

- .github/workflows/single-binary.yml
Version 2 of the `upload-artifact` GitHub action has been deprecated for a while and recently updated to [fail builds](https://github.com/flyteorg/flyte/actions/runs/10831312784/job/30053063184#step:1:36).
This updates it to the latest version so that the build no longer fails.
> Use latest upload/download-artifact action version

- flyteadmin/go.mod
- flyteadmin/go.sum
- flyteadmin/pkg/manager/impl/testutils/mock_requests.go
- flyteadmin/pkg/manager/impl/validation/execution_validator.go
- flyteadmin/pkg/manager/impl/validation/execution_validator_test.go
- flyteadmin/pkg/manager/impl/validation/validation.go
- flytepropeller/go.mod
- flytepropeller/go.sum
- flytepropeller/pkg/apis/flyteworkflow/v1alpha1/iface.go
- flytepropeller/pkg/compiler/transformers/k8s/inputs.go
- flytepropeller/pkg/controller/config/config.go
- flytepropeller/pkg/controller/config/config_flags.go
- flytepropeller/pkg/controller/config/config_flags_test.go
- flytepropeller/pkg/controller/config/config_test.go
- flytepropeller/pkg/controller/controller.go
- flytepropeller/pkg/controller/nodes/array/handler.go
- flytepropeller/pkg/controller/nodes/array/handler_test.go
- flytepropeller/pkg/controller/nodes/common/utils.go
- flytepropeller/pkg/controller/nodes/common/utils_test.go
- flytepropeller/pkg/controller/nodes/executor.go
- flytepropeller/pkg/controller/nodes/executor_test.go
- flytepropeller/pkg/controller/nodes/factory/handler_factory.go
- flytepropeller/pkg/controller/workflow/executor_test.go
- go.mod
- go.sum
RFC https://github.com/flyteorg/flyte/pull/5103
This PR tackles the mapped o/p results exceeeding the offloaded min size 
Without these changes we hit grpc limit when propeller tries to create an execution by passing inputs inline which it got from output of large map task 
Here you can see the failure where we are hitting the default 4MB grpc message size limit
This is the line where it  fails
https://github.com/flyteorg/flyte/blob/7136919f271ec1a5b0fa0ccd29175191d5ceffee/flytepropeller/pkg/controller/nodes/subworkflow/launchplan/admin.go#L151
```
[UserError] failed to launch workflow, caused by: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (26624663 vs. 4194304)
```
See the testing details for the workflow used. In particular this section 
```
def …
```
> Added literal offloading for array node map tasks

- flyte-single-binary-local.yaml
- flytepropeller/pkg/controller/config/config.go
- flytepropeller/pkg/controller/config/config_flags.go
- flytepropeller/pkg/controller/config/config_flags_test.go
Linking to RFC: https://github.com/flyteorg/flyte/pull/5103
All the other flags use the format proposed in this PR.
Rename pflags for the new literal offloading feature. Also, enable it by default in the default dev config.
A lot of local testing in combination with https://github.com/flyteorg/flytekit/pull/2685.
> Rename literal offloading flags and enable offloading in local config

- flytepropeller/pkg/controller/config/config.go
> Add comments for semver regex

- flyteidl/clients/go/assets/admin.swagger.json
- flyteidl/gen/pb-es/flyteidl/core/literals_pb.ts
- flyteidl/gen/pb-go/flyteidl/core/literals.pb.go
- flyteidl/gen/pb-go/gateway/flyteidl/cacheservice/cacheservice.swagger.json
- flyteidl/gen/pb-go/gateway/flyteidl/datacatalog/datacatalog.swagger.json
- flyteidl/gen/pb-go/gateway/flyteidl/service/admin.swagger.json
- flyteidl/gen/pb-go/gateway/flyteidl/service/agent.swagger.json
- flyteidl/gen/pb-go/gateway/flyteidl/service/dataproxy.swagger.json
- flyteidl/gen/pb-go/gateway/flyteidl/service/external_plugin_service.swagger.json
- flyteidl/gen/pb-go/gateway/flyteidl/service/signal.swagger.json
- flyteidl/gen/pb_rust/flyteidl.core.rs
- flyteidl/protos/flyteidl/core/literals.proto
- flytepropeller/pkg/compiler/validators/bindings.go
Tell others how to `Bianry IDL`, `MessagePack` as an example.
Add comments.
flyte backend: https://github.com/flyteorg/flyte/pull/5744
flytekit:  https://github.com/flyteorg/flytekit/pull/2751
> [Flyte][1][IDL] Binary IDL With MessagePack

- flytepropeller/pkg/controller/nodes/task/backoff/handler.go
fixes https://github.com/flyteorg/flyte/issues/5770
Propeller should backoff to avoid thrashing struggling etcserver even further.
Account for etcdserver errors when checking whether we should backoff or not.
> Backoff on etcd errors

- docs/deployment/agents/databricks.rst
- databricks agent: https://flyte--5766.org.readthedocs.build/en/5766/deployment/agents/databricks.html
- flytekit change
https://github.com/flyteorg/flytekit/pull/2574
- flytesnacks change
https://github.com/flyteorg/flytesnacks/pull/1733
We want to let users run k8s spark and databricks agent together in the same workflow.
update `default-for-task-types` for `databricks`.
In this PR by Kevin.
https://github.com/flyteorg/flytekit/pull/2574
> [Docs][flyteagent] Update Databricks Agent Setup to V2

- docs/deployment/agents/chatgpt.rst
- docs/deployment/agents/databricks.rst
- docs/deployment/agents/openai_batch.rst
- docs/flyte_agents/deploying_agents_to_the_flyte_sandbox.md
- chatgpt agent: https://flyte--5765.org.readthedocs.build/en/5765/deployment/agents/chatgpt.html
- databricks agent: https://flyte--5765.org.readthedocs.build/en/5765/deployment/agents/databricks.html
- openai batch agent: https://flyte--5765.org.readthedocs.build/en/5765/deployment/agents/openai_batch.html
- deploy to the flyte sandbox: https://flyte--5765.org.readthedocs.build/en/5765/flyte_agents/deploying_agents_to_the_flyte_sandbox.html
1. use `kubectl patch secret` to set the secret value in the agent deployment.
2. add `kubectl rollout restart deployment flyteagent -n flyte` after the secret is set
ChatGPT Agent.
```python
from flytekit import workflow
from flytekitplugins.openai import ChatGPTTask
chatgpt_small_job = ChatGPTTask( …
```
> [Docs][flyteagent] Improve Agent Secret Setup

- flytestdlib/.golangci.yml
- flytestdlib/cache/auto_refresh.go
- flytestdlib/cache/auto_refresh_test.go
Closes #5711 
Previously this unit test was relying on a real clock which makes unit tests slow and flaky due to nondeterministic execution duration. If code takes a dependency on time it should use a pluggable clock. 
Before 
```
ok      github.com/flyteorg/flyte/flytestdlib/cache     8.828s
```
After
```
ok      github.com/flyteorg/flyte/flytestdlib/cache     0.277s
```
`autoRefresh` and the work queue it relies were updated to use a pluggable clock. A fake clock is used for unit tests while a real clock is used under all other circumstances.
> Use pluggable clock for auto refresh cache and make unit tests fast

- docs/user_guide/development_lifecycle/decks.md
flyte deck: https://flyte--5777.org.readthedocs.build/en/5777/user_guide/development_lifecycle/decks.html
> [Docs] Flyte Deck example

- docs/user_guide/customizing_dependencies/imagespec.md
Update doc and add more examples
Preview: https://flyte--5748.org.readthedocs.build/en/5748/user_guide/customizing_dependencies/imagespec.html
> Update ImageSpec documentation

- docs/_static/custom.css
- docs/_static/custom.js
- docs/_templates/layout.html
- docs/api/index.md
- docs/conf.py
- docs/index.md
- docs/user_guide/index.md
This ports over a bunch of styles from docs.union.ai so that the appearance is more similar
> add css styling

- datacatalog/go.mod
- datacatalog/go.sum
- flyteadmin/go.mod
- flyteadmin/go.sum
- flytecopilot/go.mod
- flytecopilot/go.sum
- flytectl/go.mod
- flytectl/go.sum
- flyteidl/go.mod
- flyteidl/go.sum
- flyteplugins/go.mod
- flyteplugins/go.sum
- flytepropeller/go.mod
- flytepropeller/go.sum
- flytestdlib/go.mod
- flytestdlib/go.sum
- go.mod
- go.sum
Closes #5794 
Updates the AWS Go SDK to support EKS Pod Identity, a newer, more convenient way of authenticating service accounts to IAM roles.
To bring the AWS Go SDK up to the minimum required to support the feature.
I tried to test the various modules however I kept getting the same error, so I then checked out the latest release (v1.13.1), reran everything and it failed at the same place, which makes me think it's something wrong with my setup. I did have to edit the PostgreSQL and Minio deployments because they aren't compatible with arm64, so it might be due to that. I'd very much appreciate it if anyone with a working environment could give this a quick test.
N/A
None added, but can look to add documentation if desired.
> Update aws-go-sdk to v1.47.11 to support EKS Pod Identity

- flyteadmin/pkg/workflowengine/impl/prepare_execution.go
- flyteadmin/pkg/workflowengine/impl/prepare_execution_test.go
Closes https://github.com/flyteorg/flyte/issues/5786
To make sure Workflows aren't prematurely deleted by Flyteadmin and FlytePropeller can properly transitions the states to `Aborted`
Unit Tested
Tested in a staging environment manually.
> Add finalizer to avoid premature CRD Deletion

- docs/user_guide/data_types_and_io/dataclass.md
flyte dataclass: https://flyte--5829.org.readthedocs.build/en/5829/user_guide/data_types_and_io/dataclass.html
> [Docs] Use Pure Dataclass In Example

- docs/conf.py
With this PR, the flytekit API docs will point to Github.
This PR adds a custom `linkcode_resolve` to link back to flytekit code.
> Link to github for flytekit docs

- docs/user_guide/concepts/main_concepts/executions.rst
Closing #4684
The [executions](https://docs.flyte.org/en/latest/user_guide/concepts/main_concepts/executions.html) has documentation about Execution and their Typical Flow. As suggested in issue #4684, there should be information about the execution IDs as well.
The PR simply adds an additional line in the documentation about execution IDs.
This was a simple and straightforward Doc change, so right syntax is kept in mind and checked.
> Added the documentation about uniqueness of execution IDs

- monodocs-environment.lock.yaml
- monodocs-environment.yaml
These dependencies are needed to get the flytekit docs to build with the added neptune and wandb plugins.
This is one of three PRs we need to merge in the following order to get the neptune and wandb flytekit plugin docs onto the docs site:
1. [flytesnacks PR](https://github.com/flyteorg/flytesnacks/pull/1748) to fix refs in neptune and wandb plugin docs
1. flyte PR (this one) to update monodocs dependencies
1. [flytekit PR](https://github.com/flyteorg/flytekit/pull/2803) to add new flytekit plugin docs for neptune and wandb plugins (after re-running monodocs build)
Updated monodocs-environment.yaml and monodocs-environment.lock.yaml with neptune and wandb dependencies.
Recreated my `monodocs-env` conda environment with the new lockfile, then ran `make docs` with`FLYTEKIT_LOCAL_PATH` set …
> DOC-648 Add wandb and neptune dependencies

- flyteadmin/go.mod
- flytecopilot/go.mod
- flytecopilot/go.sum
- flyteidl/clients/go/coreutils/extract_literal_test.go
- flyteidl/clients/go/coreutils/literals.go
- flyteidl/clients/go/coreutils/literals_test.go
- flyteidl/go.mod
- flyteidl/go.sum
- flyteplugins/go.mod
- flyteplugins/go.sum
https://github.com/flyteorg/flyte/pull/5763
If an old flytekit image receives BINARY MSGPACK Inputs, it will fail, since it can't interpret it.
Note: for the upcoming flytekit, we can use protobuf struct as input and still make dataclass/pydantic basemodel works well.
Generate JSON String instead of MSGPACK BYTES when using yaml dictionary as input to create dataclass.
execute a pydantic workflow by using flytectl (yaml dictionary as input).
```python
from pydantic import BaseModel, Field
from typing import Dict, List
from flytekit.types.file import FlyteFile
from flytekit.types.directory import FlyteDirectory
from flytekit import task, workflow, ImageSpec
from enum import Enum
import os
flytekit_hash = "35312016dfcd305b6969933895f719e6f202e744"
flytekit = …
```
> [flytectl] Use Protobuf Struct as dataclass Input for backward compatibility

- CODEOWNERS
Adds @davidmirror-ops as codeowner of deployment guide docs so he is added as a reviewer on PRs for them.
> Add David as codeowner of deployment docs

- flyteplugins/go/tasks/pluginmachinery/ioutils/remote_file_output_reader.go
- flyteplugins/go/tasks/pluginmachinery/ioutils/remote_file_output_reader_test.go
- flytepropeller/pkg/controller/nodes/task/handler.go
- flytepropeller/pkg/controller/nodes/task/handler_test.go
See the original [slack thread](https://flyte-org.slack.com/archives/CP2HDHKE1/p1724409985371659).
Even when upload of a file fails because the file is too large, we retry many times.  This is not needed.
* Add a new error type and test for it, returning a not IsRecoverable error.
Tested locally with the following workflow
```python
from flytekit import task, workflow
@task
def print_arrays(arr1: str) -> None:
print(f"Array 1: {arr1}")
@task  # (container_image=normal_image)
def increase_size_of_of_arrays(n: int) -> str:
arr1 = "a" * n * 1024
return arr1
@workflow
def simple_pipeline(n: int) -> int:
arr1 = increase_size_of_of_arrays(n=n)
print_arrays(arr1)
return 2
```
Before
After
Tangentially related to this PR: https://github.com/flyteorg/flytekit/pull/2700, which solves a similar …
> Add an error for file size exceeded to prevent system retries

- monodocs-environment.lock.yaml
- monodocs-environment.yaml
The perian plugin depends on the `perian` package; in order to build flytekit docs about the perian plugin, we need to include that package in the docs requirements.
Adds `perian` package to `monodocs-requirements.yaml` and updates `monodocs-requirements.lock.yaml` with new dependency.
Tested building docs locally with updated monodocs environment and `FLYTEKIT_LOCAL_PATH` set to @otarabai fork of flytekit that includes perian plugin docs updates.
Local docs build:
https://github.com/flyteorg/flytekit/pull/2816
https://flyte--5848.org.readthedocs.build/en/5848/ (Note: this is just to demonstrate that the docs build with the new dependency -- the perian flytekit docs won't be in this build because they're currently in a fork.)
> Add perian dependency for PERIAN plugin

- flyteadmin/go.mod
- flyteplugins/go.mod
- flyteplugins/go.sum
- flyteplugins/go/tasks/pluginmachinery/core/template/template.go
- flyteplugins/go/tasks/pluginmachinery/core/template/template_test.go
We need to support attribute access for `dataclass` when it is a msgpack binary IDL object to a raw container task.
Example:
```python
@workflow
def wf(dc: DC) -> Tuple[int, bool, float, str]:
return python_return_same_values(a=dc.a, b=dc.b, c=dc.c, d=dc.d)
python_return_same_values = ContainerTask(
name="python_return_same_values",
inputs=kwtypes(a=int, b=bool, c=float, d=str),
outputs=kwtypes(a=int, b=bool, c=float, d=str),
image="futureoutlier/rawcontainer:0320",
command=[
"python", "return_same_value.py",
"{{.inputs.a}}", "{{.inputs.b}}", "{{.inputs.c}}", "{{.inputs.d}}",
"/var/outputs",
],
)
```
It adds logic to deserialize the msgpack binary IDL object and convert it into a string for the container task input, similar to how we handle …
> [FlyteCopilot] Binary IDL Attribute Access Primitive Input

- docs/user_guide/concepts/main_concepts/data_management.rst
Related to #4456 
Based on user feedback, some users understand the basics of data management in Flyte but are unsure how to implement it, so I’ve added examples to help them follow along more easily.
https://flyte--5844.org.readthedocs.build/en/5844/user_guide/concepts/main_concepts/data_management.html
> [Docs] add practical example to improve data management doc

- flyteadmin/pkg/server/service.go
https://github.com/flyteorg/flyte/issues/5790
CORS options were never enabled in the case of tls servers.
> Handle CORS in secure connections

- rfc/system/0008-community-plugins.md
> RFC: Community plugins

- docs/user_guide/data_types_and_io/flytedirectory.md
- docs/user_guide/data_types_and_io/flytefile.md
Related to #4460 
Example PR: https://github.com/flyteorg/flytesnacks/pull/1759
This PR introduces file streaming support for both `FlyteFile` and `FlyteDirectory` in our document.
https://github.com/flyteorg/flytekit/pull/1512
https://flyte--5879.org.readthedocs.build/en/5879/user_guide/data_types_and_io/flytefile.html
https://flyte--5879.org.readthedocs.build/en/5879/user_guide/data_types_and_io/flytedirectory.html
> [Docs] add streaming support example for file and directory

- docs/user_guide/data_types_and_io/structureddataset.md
The code lines of [StructuredDataset](https://docs.flyte.org/en/latest/user_guide/data_types_and_io/structureddataset.html) are out of sync of the [Flytesnacks example](https://raw.githubusercontent.com/flyteorg/flytesnacks/69dbe4840031a85d79d9ded25f80397c6834752d/examples/data_types_and_io/data_types_and_io/structured_dataset.py).
Fix code lines to align code snippets.
For example, the following import is missed:
```python
from typing_extensions import Annotated
```
* [StructuredDataset](https://docs.flyte.org/en/latest/user_guide/data_types_and_io/structureddataset.html)
* [Flytesnacks example](https://raw.githubusercontent.com/flyteorg/flytesnacks/69dbe4840031a85d79d9ded25f80397c6834752d/examples/data_types_and_io/data_types_and_io/structured_dataset.py) …
> [Docs] Align Code lines of StructuredDataset with Flytesnacks Example

- flyteplugins/go/tasks/plugins/webapi/agent/plugin.go
Closes #5885
The Grpc client never closes send so the server is unable to move forward in the grpc streaming onComplete method. This change will inform the server that is done sending so it can properly move to the next step.
Move the `closeSend` after sending all the necessary things.
Unit test
> Sync client should call CloseSend when done sending

- flyteadmin/pkg/server/service.go
While working on an RFC I noticed that there is a duplicate recovery interceptor installed inside the Flyte Admin server. We ideally want to use the custom one which ties into metrics.
> Remove duplicate recovery interceptor

- flyteadmin/Makefile
None
Fails to execute "make scheduler" under flyteadmin
Fix Makefile
Test locally
> fix: failed to make scheduler under flyteadmin

- docs/user_guide/advanced_composition/conditionals.md
1. The import statement of `Echo` is missing.
2. The demonstration of the workflow `shape_properties_accept_conditional_output` is ignored in the main function right below it.
3. The descriptions of expected outputs of the workflow `consume_task_output` are inverted. 
Reassign the example code url with the new gitsha and align code lines.
The modified version of the example code in Flytesnacks can be found in [this PR](https://github.com/flyteorg/flytesnacks/pull/1760)
https://flyte--5880.org.readthedocs.build/en/5880/user_guide/advanced_composition/conditionals.html
> [Docs] Recover the expected behaviors of example workflows

- flyteplugins/go/tasks/plugins/webapi/agent/plugin.go
NA
Rebuilding gRPC connections in Agents leaks goroutines
As part of the investigation for [this issue](https://linear.app/unionai/issue/PE-1326/flytepropeller-oomkilled-for-high-workload-customers) we discovered [Agents is periodically rebuilding gRPC connections](https://github.com/unionai/flyte/blob/master/flyteplugins/go/tasks/plugins/webapi/agent/plugin.go#L386-L391) and [not closing them because the context used](https://github.com/unionai/flyte/blob/master/flyteplugins/go/tasks/plugins/webapi/agent/client.go#L67-L72) is that of the overall flyte binary. This results in very long-lived, unused gRPC connections and a goroutine leak that steadily increases memory utilization until crash.
Use child context in the watcher and cancel the child context every time. Canceling this context …
> Use child context in watchAgents

- docs/user_guide/customizing_dependencies/raw_containers.md
Closes #4461 
In document user_guide/customizing_dependencies/raw_containers.html lacks information about cache configuration in Flyte's ContainerTask.
1. Add information about cache configuration in Flyte's doc user_guide/customizing_dependencies/raw_containers.html.
2. Add example code in flytesnacks, please refer to this [PR](https://github.com/flyteorg/flytesnacks/pull/1758).
[flytesnacks PR](https://github.com/flyteorg/flytesnacks/pull/1758)
[Raw containers](https://docs.flyte.org/en/latest/user_guide/customizing_dependencies/raw_containers.html)
> [docs]add cache information in raw containers doc

- docs/user_guide/development_lifecycle/caching.md
Reference #3249 
The changes are needed to enhance the Flyte documentation by providing a comprehensive overview of caching mechanisms. As per User feedback, these changes aim to simplify the caching documentation for better user understanding.
Short Video Demo: (If required) I can also create a short 1-2 minute video that provides a brief overview of caching and shows how to enable/disable it in Flyte. This would help users quickly grasp the concept. 
- [X ] I updated the documentation accordingly.
- [X ] All commits are signed-off.
[Docs Link](https://flyte--5878.org.readthedocs.build/en/5878/user_guide/development_lifecycle/caching.html)
> [Docs] Simplifying for better user understanding

- flyteplugins/go/tasks/plugins/k8s/ray/ray.go
- flyteplugins/go/tasks/plugins/k8s/ray/ray_test.go
We have a Queue to schedule our ray jobs, so we need it to wait in Suspended state of k8s
Now workflow fails, exactly when job state goes to 'Suspended'
> Update ray.go not to fail when going suspend state.

- .github/workflows/checks.yml
- .github/workflows/flytectl-install.yml
- .github/workflows/flyteidl-buf-publish.yml
- .github/workflows/flyteidl-checks.yml
- .github/workflows/helm-charts.yaml
- .github/workflows/single-binary.yml
- .github/workflows/tests.yml
- .github/workflows/validate-helm-charts.yaml
Similar to https://github.com/flyteorg/flytekit/pull/2827, this PR ensures that CI checks run as part of the merges to release branches.
> Run CI in release branches

- docs/community/contribute/contribute_docs.md
Related to #5783
Since Hacktoberfest is underway, I've updated the developer documentation to help them contribute easier.
https://flyte--5862.org.readthedocs.build/en/5862/community/contribute/contribute_docs.html
> [Docs] improve contribute docs

- docs/deployment/configuration/monitoring.rst
The Grafana dashboards hadn't been updated in a long time and we lost access to the original Grafana marketplace account where those were hosted. Also, the user dashboard required several updates completed in #5703 but also required additional instructions and documented dependencies to make it work.
This PR updates references to the Grafana dashboards under an updated marketplace account. It also adds instructions to prepare the Flyte cluster so Prometheus can scrap metrics to feed the dashboards, including mentions to the dependencies of the user dashboard.
> Update monitoring docs

- charts/flyte-binary/README.md
- charts/flyte-binary/values.yaml
- cmd/single/config.go
- cmd/single/start.go
- deployment/sandbox-binary/flyte_sandbox_binary_helm_generated.yaml
- flyteadmin/cmd/entrypoints/migrate.go
- flyteadmin/pkg/repositories/config/seed_data.go
- flyteadmin/pkg/repositories/config/seed_data_test.go
- flyteadmin/pkg/server/initialize.go
Closes https://github.com/flyteorg/flyte/issues/3742
The changes introduce the ability to specify both a name and a description for seed projects using `seedProjectsWithDetails`. This enhancement improves flexibility by allowing users to provide additional context when defining seed projects, making managing and tracking seed projects in Flyte easier.
This pull request adds support for defining seed projects with descriptions through a new field, seedProjectsWithDetails.
- Introduces seedProjectsWithDetails, allowing users to provide both a name and a description for each seed project.
- Ensures that if a project exists in both seedProjects and seedProjectsWithDetails, the description from seedProjectsWithDetails will take precedence.
- Automatically generates a default description for …
> feat: add support for seedProjects with descriptions via seedProjectsWithDetails

- docs/deployment/configuration/monitoring.rst
Fixes a couple of indented lines that shouldn't be part of the code block
> Quick fix for monitoring docs YAML

- docs/user_guide/concepts/control_plane/domains.rst
Closes #4392 
The information is needed so that new users do not get confused as why they are not able to create domains. As the domains are fixed.
It was a simple documentation change.
Page where the changes should be visible once the PR is merged : [link](https://docs.flyte.org/en/latest/user_guide/concepts/control_plane/domains.html)
> Added documentation about Fixed and unique domains

- flyteadmin/pkg/async/cloudevent/implementations/cloudevent_publisher.go
- flyteadmin/pkg/common/filters.go
- flyteadmin/pkg/manager/impl/node_execution_manager.go
- flyteadmin/pkg/manager/impl/node_execution_manager_test.go
- flyteadmin/pkg/manager/impl/signal_manager.go
- flyteadmin/pkg/manager/impl/task_execution_manager.go
- flyteadmin/pkg/manager/impl/task_execution_manager_test.go
- flyteadmin/pkg/manager/impl/util/filters.go
- flyteadmin/pkg/manager/impl/util/filters_test.go
- flyteadmin/pkg/repositories/gormimpl/common.go
- flyteadmin/pkg/repositories/gormimpl/node_execution_repo.go
- flyteadmin/pkg/repositories/gormimpl/node_execution_repo_test.go
- flyteadmin/pkg/repositories/gormimpl/task_execution_repo.go
- flyteadmin/pkg/repositories/gormimpl/task_execution_repo_test.go
for ListNodeExecutions and ListTaskExecutions queries we always force a join on executions, and for the latter, node executions. This is inefficient and unnecessary when we don't reference cross table entities in request filters.
Furthermore, this change updates how we query on execution identifier filters to avoid forcing an unnecessary join there too.
See description. This only forces joins when they are necessitated by the presence of request filters.
Tested with single binary and verified I could launch executions and interact with the console. I forced cross table joins with request filters and saw SQL logs reflect that.
> Remove unnecessary joins for list node and task execution entities in flyteadmin db queries

- flytepropeller/pkg/controller/nodes/attr_path_resolver.go
- flytepropeller/pkg/controller/nodes/attr_path_resolver_test.go
[Flyte Issue #5318](https://github.com/flyteorg/flyte/issues/5318)
This update ensures that the following example workflow functions as expected:
```python
@dataclass
class MyDataClass:
my_ints: list[int]
@flytekit.task
def print_int(my_int: int):
print(f"my_int: {my_int}")
@flytekit.workflow
def my_workflow(my_data_class: MyDataClass = MyDataClass(my_ints=[1, 2, 5, 10])):
flytekit.map_task(print_int)(my_int=my_data_class.my_ints)
```
The primary change is to ensure that a `collection literal` is created when the resolved value is a `list`, allowing map tasks to function properly with collections.
**Non-Map Task (List handling)**:
1. **Before**:  
`Python value -> binary IDL -> resolved value -> binary IDL -> list transformer -> Python value`
2. **After**:  
`Python value -> binary IDL -> …
> Binary IDL Attribute Access for Map Task

- docs/user_guide/flyte_fundamentals/registering_workflows.md
These changes are necessary to enhance the clarity for first-time users, ensuring they understand how to register workflows without confusion.
Updated note section to remove "Like `pyflyte register`" in registering_workflows.md file.
> Improve Documentation for Registering Workflows to avoid confusion 

- docs/user_guide/concepts/main_concepts/data_management.rst
Closes #4683 
1. The [Understand How Flyte Handles Data doc](https://docs.flyte.org/en/latest/user_guide/concepts/main_concepts/data_management.html#understand-how-flyte-handles-data) is lacking information about deleting raw data in storage service such as s3 and gcs.
2. Some [example code](https://docs.flyte.org/en/latest/user_guide/concepts/main_concepts/data_management.html#practical-example) in the doc is incorrect. The workflow called a function 'task_read_and_shuffle_file', but the function is not defined in example code.
1. Add information about  raw data deletion in the doc.
2. Fix example code. 
[https://flyte--5922.org.readthedocs.build/en/5922/user_guide/concepts/main_concepts/data_management.html](https://flyte--5922.org.readthedocs.build/en/5922/user_guide/concepts/main_conce …
> [Docs]Document clarifying notes about the data lifecycle

- docs/user_guide/concepts/main_concepts/tasks.rst
- docs/user_guide/flyte_fundamentals/optimizing_tasks.md
… retry budget #3956
This PR clarifies the documentation regarding retry behavior for interruptible tasks in Flyte. It updates sections to emphasize that retries for spot/interruptible instances utilize the system retry budget rather than the user-specified retry budget. Changes are made in the user guide and related documentation files to ensure accurate guidance for users managing task retries on preemptible compute resources.
> fixed [Docs] Spot/interruptible docs imply retries come from the user… Closes #3956

- docs/deployment/configuration/performance.rst
- flytepropeller/manager/doc.go
Using the lowercase version of e.g. `project` the following error is raised by flytepropeller-manager
```
level=error msg="\n\n1 error(s) decoding:\n\n* cannot parse 'shard.type' as int: strconv.ParseInt: parsing \"project\": invalid syntax"
```
Tested uppercase `Project` in our Flyte deployment. I did not test the uppercase `Domain` option. That one is just an assumption based on the need to uppercase `Hash` and `Project`.
> Update propeller sharding docs - types needs to be capitalized

- flytectl/pkg/configutil/configutil.go
- flytectl/pkg/configutil/configutil_test.go
- flytectl/pkg/sandbox/start.go
Closes https://github.com/flyteorg/flyte/issues/3186
1. Removing Unused Fields: Remove `storage.connection`. This reduces clutter, making the config cleaner and easier to understand.
2. Aligning Configurations: Ensures `flytectl config init` and `flytectl demo start` produce consistent configs, simplifying setup and usage. Align the `admin.endpoint: dns:///localhost:30080`.
unit test
> fix: align the default config output

- docs/user_guide/data_types_and_io/flytefile.md
The doc links to blob literal and type are outdated, so an update is needed for correct references.
Fix the doc links based on the new `flyte` project structure, instead of pointing to the [old one](https://github.com/flyteorg/flyteidl/blob/master/protos/flyteidl/core/literals.proto#L33).
* Fixed link to blob literal
* Fixed link to blob type
https://flyte--5952.org.readthedocs.build/en/5952/user_guide/data_types_and_io/flytefile.html
> [Docs] Fix doc links to blob literal and type

- flyteadmin/pkg/repositories/gormimpl/common.go
- flyteadmin/pkg/repositories/gormimpl/execution_repo.go
- flyteadmin/pkg/repositories/gormimpl/execution_repo_test.go
- flyteadmin/pkg/repositories/gormimpl/node_execution_repo.go
- flyteadmin/pkg/repositories/gormimpl/node_execution_repo_test.go
- flyteadmin/pkg/repositories/gormimpl/task_execution_repo.go
- flyteadmin/pkg/repositories/gormimpl/task_execution_repo_test.go
In the executions path, performant updates are important since propeller sends executions events and doesn't proceed with the execution until the event is properly acked.
We've observed a performance increase (3x) for updating task executions in particular (which have 9!! primary keys) so that generated gorm adds a where clause for each primary key and this results in noticeably slower queries compared to updating on the unique BaseModel indexed [Id](https://github.com/flyteorg/flyte/blob/732b42e291baac16e82c2c1a110fe0a9a908bb42/flyteadmin/pkg/repositories/models/base_model.go#L15) field.
I'm only updating executions tables here (workflow, node and task) because they're in the hot path. Inventory like tasks and workflows can't be updated, launch plan state can but the perf requirements …
> Reduce where clause fanout when updating workflow, node & task executions

- Makefile
- flyteadmin/Makefile
- flytestdlib/version/version.go
provide version api for users.
add a method `get_control_plane_version` in `class SynchronousFlyteClient(_RawSynchronousFlyteClient)`.
local and integration test.
```python
from flytekit.configuration import PlatformConfig
from flytekit.clients.friendly import SynchronousFlyteClient as _SynchronousFlyteClient
config = PlatformConfig(endpoint="localhost:30080", insecure=True)
client = _SynchronousFlyteClient(config)
print("Control Plane Version:", client.get_control_plane_version())
```
Unknown version
Know Version
> [flyteadmin][API] get control plane version

- flyteplugins/go/tasks/logs/logging_utils.go
In https://github.com/flyteorg/flyte/pull/4726 I introduced the option to configure the lifecycle of log links as is documented [here](https://docs.flyte.org/en/latest/user_guide/productionizing/configuring_logging_links_in_the_ui.html#configure-lifetime-of-logging-links). In particular, log links can be configured to be already shown before a task starts running or be configured to disappear after a task stops.
@Tom-Newton [noted](https://github.com/flyteorg/flyte/pull/4726/files#r1819110678) that their flytepropeller logs are spammed with error messages because the log link generation logic for pod tasks checks whether container statuses exist and if not logs this as an error. Prior to https://github.com/flyteorg/flyte/pull/4726 it made sense to always log this as an error because log …
> Fix: avoid log spam for log links generated during the pod's pending phase

- docs/user_guide/basics/tasks.md
To better align the note in the [tasks page](https://docs.flyte.org/en/latest/user_guide/basics/tasks.html) with the actual naming convention of output variables.
Change the default name of output variables from `outx` to `ox`, where `x` is an ordinal number starting from `0`.
https://docs.flyte.org/en/latest/user_guide/basics/named_outputs.html
https://flyte--5919.org.readthedocs.build/en/5919/user_guide/basics/tasks.html
> [Docs] Align Note with the Output Naming Convention

- docs/user_guide/customizing_dependencies/imagespec.md
https://github.com/flyteorg/flytekit/pull/2715
Update the documents for users to understand the copy commands behaviors and usages.
1. Added a simple workflow example of using imageSpec with copy commands.
2. Describe the expected behavior and usages.
1. The examples are tested through remote execution.
```
pyflyte run --remote build_image.py my_wf
```
TODO
> [DOC] add copy command examples and description

- flyteadmin/pkg/common/filters.go
- flyteadmin/pkg/common/filters_test.go
- flyteadmin/pkg/manager/impl/execution_manager.go
- flyteadmin/pkg/manager/impl/named_entity_manager.go
- flyteadmin/pkg/manager/impl/named_entity_manager_test.go
- flyteadmin/pkg/manager/impl/util/single_task_execution.go
- flyteadmin/pkg/manager/impl/util/single_task_execution_test.go
- flyteadmin/pkg/manager/impl/validation/named_entity_validator.go
- flyteadmin/pkg/manager/impl/validation/named_entity_validator_test.go
Currently, the launch plan page will show generated launch plans, which make users hard to find their launch plan. We should hide them like we do for workflows. 
1. In ListNamedEntities, if no filter provided, filter by name starting with `.flytegen`. I did this instead of filtering by resource state since I would like to avoid a db migration.
2. Allow launchplan type entities being updated.
1. unit tests
2. integration tests with sandbox
> Hide generated launch plans starting with .flytegen in the UI

- docs/deployment/configuration/auth_setup.rst
I believe `security` belongs under `server`.
Without making this change, the auth didn't work for me. 
I further checked this by noting that 
1. https://github.com/unionai-oss/deploy-flyte/blob/main/environments/gcp/flyte-core/values-gcp-core.yaml#L228 has `security` under `server`
2. the example helm file listed on https://artifacthub.io/packages/helm/flyte/flyte-core also places `security` under `server`: `configmap.adminServer.server.security.useAuth`
Wan't able to get auth working without it
put `security` underneath `server`
Tested it with an on prem deploy.
> Fix indentation for security block in auth_setup.rst

- flytepropeller/pkg/apis/flyteworkflow/v1alpha1/error_test.go
- flytepropeller/pkg/apis/flyteworkflow/v1alpha1/gate_test.go
- flytepropeller/pkg/apis/flyteworkflow/v1alpha1/identifier_test.go
- flytepropeller/pkg/apis/flyteworkflow/v1alpha1/register.go
- flytepropeller/pkg/apis/flyteworkflow/v1alpha1/register_test.go
- flytepropeller/pkg/apis/flyteworkflow/v1alpha1/subworkflow_test.go
Example: Related to #4209 
Improve code tests coverage.
#4234
> [flytepropeller] Add tests in v1alpha

- flytecopilot/go.mod
- flytecopilot/go.sum
- flyteidl/clients/go/coreutils/extract_literal_test.go
- flyteidl/clients/go/coreutils/literals.go
- flyteidl/clients/go/coreutils/literals_test.go
- flyteidl/go.mod
- flyteidl/go.sum
We want to ease the pain of generic IDL -> msgpack IDL when the user upgrades to flyte 1.14.
1. if `os.environ["FLYTE_USE_OLD_DC_FORMAT"] = "true"`, then use old behavior to generate protobuf struct in the generic IDL.
else generate msgpack IDL.
2. add back unit tests deleted in this PR:
https://github.com/flyteorg/flyte/pull/5840
note: use `envs` is passed to flyteadmin to inform that the first task pod need to inject `envs` in this file, but not be used to command line create `protobuf struct`.
```yaml
iamRoleARN: ""
inputs:
dc:
a: 1
b: 3.14
c: example_string
envs:
FLYTE_USE_OLD_DC_FORMAT: true  # Here doesn't work to produce protobuf struct
kubeServiceAcct: ""
targetDomain: ""
targetProject: ""
task: …
```
> [flytectl][MSGPACK IDL] Gate feature by setting ENV

- docs/deployment/configuration/monitoring.rst
- flyteplugins/go/tasks/plugins/k8s/ray/config.go
- flyteplugins/go/tasks/plugins/k8s/ray/config_test.go
- flyteplugins/go/tasks/plugins/k8s/ray/ray.go
Closes #5821
These changes are necessary because the SA is pulled from the k8s context regardless of what's set in the config.
> Ray Plugin - Use serviceAccount from Config if set

- docs/user_guide/data_types_and_io/accessing_attributes.md
DOC-666
Minor clarification suggested by @Thomas here: https://unionai.slack.com/archives/C02CMUNT4PQ/p1729211883670849
Change in wording. Additional explanation
> DOC-666 Change "Accessing attributes" to "Accessing attributes in workflows"

- docs/user_guide/data_types_and_io/tensorflow_type.md
The code lines of [Tensorflow types](https://docs.flyte.org/en/latest/user_guide/data_types_and_io/tensorflow_type.html) are out of sync of the [Flytesnacks example](https://raw.githubusercontent.com/flyteorg/flytesnacks/9aadec205a6e208c62e29f52873fb3d675965a51/examples/data_types_and_io/data_types_and_io/tensorflow_type.py).
Fix code lines to align with the code example in flytesnacks.
https://flyte--5983.org.readthedocs.build/en/5983/user_guide/data_types_and_io/tensorflow_type.html
> [Docs] Align code lines of TensorFlow types with flytesnacks

- flytepropeller/pkg/compiler/validators/utils.go
- flytepropeller/pkg/compiler/validators/utils_test.go
The following workflow works when we are not offloading  literals in flytekit
```
import logging
from typing import List
from flytekit import map_task, task, workflow,LaunchPlan
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("flytekit")
logger.setLevel(logging.DEBUG)
@task(cache=True, cache_version="1.1")
def my_30mb_task(i: str) -> str:
return f"Hello world {i}" * 30 * 100 * 1024
@task(cache=True, cache_version="1.1")
def generate_strs(count: int) -> List[str]:
return ["a"] * count
@workflow
def my_30mb_wf(mbs: int) -> List[str]:
strs = generate_strs(count=mbs)
return map_task(my_30mb_task)(i=strs)
@workflow
def big_inputs_wf(input: List[str]):
noop()
@task(cache=True, cache_version="1.1")
def noop():
...
big_inputs_wf_lp = …
```
> [Upstream] [COR-2297/] Fix nested offloaded type validation (#552)

- .github/workflows/checks.yml
- flytecopilot/data/download_test.go
https://github.com/flyteorg/flyte/issues/6002
With recent adjustments to the monorepo structure, the copilot lint check has been temporarily disabled in the CI pipeline. To maintain code quality and consistency, we need to re-enable and verify the copilot linting as part of the CI process.
Enable copilot lint check.
> [Housekeeping] Enable lint flytecopilot

- script/prepare_artifacts.sh
- script/release.sh
Discussed in [slack](https://flyte-org.slack.com/archives/C01P3B761A6/p1725713256883779).
flyte-binary image in helm chart is not versioned, which complicates the reproducibility.
This PR follows the pattern used by other images in helm charts, where at release time we point to images containing the `-release` suffix (e.g. https://artifacthub.io/packages/helm/flyte/flyte-core?modal=values).
Ran scripts locally and validated the new versions in the `flyte-binary` values files.
> Version flyte-binary helm chart and use flyte-binary-release docker images in releases

- flyteplugins/go/tasks/pluginmachinery/ioutils/remote_file_output_reader_test.go
- flytestdlib/storage/stow_store.go
- flytestdlib/storage/stow_store_test.go
The listing function added for stow container as part of RFC https://github.com/flyteorg/flyte/pull/5598 has a bug, which we hit when doing E2E testing. The Items() stow container function behavior implemented in the listing test mock container differed from the actual behavior. Thus the test was asserting against incorrect behavior.
Correct listing function to return full URIs.
Corrected unit test (in repo)
Also tested against minio
https://github.com/flyteorg/flyte/pull/5795
> Correct stow listing function

- docs/user_guide/advanced_composition/chaining_flyte_entities.md
- docs/user_guide/advanced_composition/conditionals.md
- docs/user_guide/advanced_composition/decorating_tasks.md
- docs/user_guide/advanced_composition/dynamic_workflows.md
- docs/user_guide/getting_started_with_workflow_development/flyte_project_components.md
Similar to https://github.com/flyteorg/flyte/pull/6008, this PR deletes the remaining instances of `{rli}`.
Note that in one case I replaced the `rli` with a code-block, since that's supposed to be a file. I'm not sure if that's the appropriate way of displaying these simple files.
> Replace other instances of rli

- flyteadmin/auth/cookie.go
- flyteadmin/auth/cookie_manager.go
- flyteadmin/auth/cookie_manager_test.go
- flyteadmin/auth/cookie_test.go
- flyteadmin/pkg/config/config.go
- flyteadmin/pkg/config/serverconfig_flags.go
- flyteadmin/pkg/config/serverconfig_flags_test.go
Setting these 2 fields is standard practice. All modern browsers implement them. 
We set `HttpOnly` and `Secure` flags in all cookies produced by Flyte. Notice that those are generated only if auth is enabled.
More information about those flags:
- https://owasp.org/www-community/HttpOnly: The HttpOnly option prevents JavaScript code from accessing the cookie. This can provide some protection from cookie theft if an attacker successfully exploits a Cross-Site Scripting (XSS) vulnerability.
- https://cwe.mitre.org/data/definitions/614.html: The Secure cookie flag is an option that can be used to prevent the browser from sending the cookie over a plaintext connection. This can prevent an attacker from attempting session hijacking through Man-in-the-Middle (MitM) attacks.
~Currently we [allow …
> Set HttpOnly and Secure flags in session cookies

- flyteplugins/go/tasks/logs/logging_utils.go
- flyteplugins/go/tasks/pluginmachinery/tasklog/template.go
- flyteplugins/go/tasks/pluginmachinery/tasklog/template_test.go
NA
`HideOnceFinished` config doesn't work with dynamic log links
Add `ShowWhilePending` and `HideOnceFinished` to the dynamic log links when creating the list of TaskLogs
flytepropeller config
```
plugins:
logs:
kubernetes-enabled: true
kubernetes-template-uri: http://localhost:30080/kubernetes-dashboard/#/log/{{.namespace }}/{{ .podName }
}/pod?namespace={{ .namespace }}
cloudwatch-enabled: false
stackdriver-enabled: false
templates:
- displayName: ShowPending
hideOnceFinished: true
templateUris: 456
dynamic-log-links:
- vscode:
displayName: VSCode
hideOnceFinished: true
templateUris: 123
```
https://github.com/flyteorg/flyte/pull/4726
NA
> Add visibility control to dynamic log links

- docs/community/contribute/contribute_code.rst
Following the instruction of [setting up environment](https://docs.flyte.org/en/latest/community/contribute/contribute_code.html#how-to-setup-dev-environment-for-flyteidl-flyteadmin-flyteplugins-flytepropeller-datacatalog-and-flytestdlib), the command `POD_NAMESPACE=flyte ./flyte start --config flyte-single-binary-local.yaml` gives error `no such file or directory: ./flyte`
It turns out that `make compile` command move `./flyte` file to `$GOPATH/bin`. Hence, directly run `flyte` instead of `./flyte` works.
change `./flyte` in command to `flyte`
> docs: update command for running the single binary

- docs/community/troubleshoot.rst
Closes #3163 
In this [discussion](https://discuss.flyte.org/t/8152768/Hi-Community-is-there-any-simple-approach-to-verify-the-GRPC), a user encountered a TLS certificate issue while registering a workflow to the Flyte-core k8s cluster. The root cause was TLS not being enabled in the Kubernetes cluster’s Ingress controller. It is recommended to add this debug information to the troubleshooting guide documentation.
Add information about flyte-core k8s ingress TLS config in the trouble shooting DOC.
https://flyte--5958.org.readthedocs.build/en/5958/community/troubleshoot.html
> How to verify that the grpc service of flyteadmin works as expected

- docs/user_guide/data_types_and_io/accessing_attributes.md
- docs/user_guide/data_types_and_io/dataclass.md
- docs/user_guide/data_types_and_io/index.md
- docs/user_guide/data_types_and_io/pydantic.md
- docs/user_guide/data_types_and_io/pydantic_basemodel.md
- dataclass: https://flyte--6022.org.readthedocs.build/en/6022/user_guide/data_types_and_io/dataclass.html
- pydantic basemodel: https://flyte--6022.org.readthedocs.build/en/6022/user_guide/data_types_and_io/pydantic_basemodel.html
- attribute access: https://flyte--6022.org.readthedocs.build/en/6022/user_guide/data_types_and_io/accessing_attributes.html
> [Docs] MessagePack IDL, Pydantic Support, and Attribute Access

- flytepropeller/pkg/compiler/validators/utils.go
- flytepropeller/pkg/compiler/validators/utils_test.go
This reverts commit f20b8aa082820c56c0c721670b54148afa7d36a4.
Related to https://github.com/flyteorg/flyte/pull/5103
In https://github.com/flyteorg/flytekit/pull/2872 we're handling the case of offloading literals in map tasks single executions explicitly. The impact of this is that we can simplify the handling of this case in the backend, invalidating https://github.com/flyteorg/flyte/pull/5996.
Revert https://github.com/flyteorg/flyte/pull/5996.
Confirmed that the original test workflow works:
```
import logging
from typing import List
from flytekit import map_task, task, workflow,LaunchPlan
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("flytekit")
logger.setLevel(logging.DEBUG)
@task(cache=True, cache_version="1.1")
def my_30mb_task(i: str) -> str:
return f"Hello …
```
> Revert "[COR-2297/] Fix nested offloaded type validation (#552) (#5996)"

- .github/workflows/publish.yml
- .github/workflows/sandbox.yml
- .github/workflows/single-binary.yml
- Dockerfile
- Dockerfile.datacatalog
- Dockerfile.flyteadmin
- Dockerfile.flytecopilot
- Dockerfile.flytepropeller
- Dockerfile.flytescheduler
- docker/sandbox/Dockerfile
N/A
1. Generate a job summary in GHA for your build that outlines the execution and materials used. It improves the visibility & readability for build information. (By default, it will generate summary and upload the build record archive to GitHub. We can disable them via "DOCKER_BUILD_SUMMARY" and "DOCKER_BUILD_RECORD_UPLOAD" env variables.)
2. Remove the warning "The following actions use a deprecated Node.js version and will be forced to run on node20"
3. refs:
https://www.docker.com/blog/new-beta-feature-deep-dive-into-github-actions-docker-builds-with-docker-desktop/
https://docs.docker.com/build/ci/github-actions/build-summary
Use the latest docker/build-push-action
test in ci
> Bump docker/build-push-action to v6

- charts/flyte-core/README.md
- charts/flyte-core/templates/admin/service.yaml
- charts/flyte-core/templates/console/service.yaml
- charts/flyte-core/values.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_controlplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_controlplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
- docker/sandbox-bundled/manifests/complete-agent.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
https://github.com/flyteorg/flyte/pull/5240, among other things, set `appProtocol` values of `TCP` for the ports of the flyteadmin and flyteconsole services in the flyte-core helm chart.
[This](https://github.com/flyteorg/flyte/pull/5240#issuecomment-2400342871) comment by @ddl-ebrown explains why this was necessary in their deployment which uses an ingress in combination with the istio service mesh:
> [...] the ingress may be configured in a way that
it sends TLS traffic to internal Flyte services. Istio will use port
names to determine traffic - and may therefore assume the appProtocol
of http, even though traffic from ingress -> flyteadmin is actually
https. This misconfiguration prevents any traffic from flowing
through the ingress to the service.
Flyteadmin http and grcp ports are …
> Fix: Make appProtocols optional in flyteadmin and flyteconsole services in helm chart

- flytectl/cmd/config/subcommand/sandbox/config_flags.go
- flytectl/cmd/config/subcommand/sandbox/config_flags_test.go
- flytectl/cmd/config/subcommand/sandbox/sandbox_config.go
- flytectl/cmd/demo/demo.go
- flytectl/cmd/demo/reload.go
- flytectl/cmd/demo/start.go
- flytectl/pkg/docker/docker_util.go
- flytectl/pkg/docker/docker_util_test.go
- flytectl/pkg/sandbox/reload.go
- flytectl/pkg/sandbox/start.go
Closes #3792 
- As stated in #3792, when a developer uses Docker Desktop with Kubernetes running on port 6443, they must shut it down before running the demo cluster
- Allow users to configure the demo cluster port if needed
1. Add a new parameter `port`, e.g., `flytectl demo start --port 6443`
2. Dynamically retrieve k8sEndpoint from `sandbox_config.go` instead of using fixed ones
3. Refactor `reload.go` to retrieve sandbox config (follow other file structure under `flyte/flytectl/cmd/demo`)
Tested that parameters were automatically generated with `make generate`
1. Run a k8s cluster that uses port 6443 (docker desktop k8s for testing)
2. Start the demo cluster without specifying port, which defaults to :6443 (expected to fail)
3. Start the demo cluster with port 6444
4. `kubectl …
> Fix: customize demo cluster port

- flyteplugins/go/tasks/pluginmachinery/flytek8s/config/config.go
- flyteplugins/go/tasks/pluginmachinery/flytek8s/config/k8spluginconfig_flags.go
- flyteplugins/go/tasks/pluginmachinery/flytek8s/config/k8spluginconfig_flags_test.go
- flyteplugins/go/tasks/pluginmachinery/flytek8s/pod_helper.go
- flyteplugins/go/tasks/pluginmachinery/flytek8s/pod_helper_test.go
- flyteplugins/go/tasks/plugins/k8s/dask/dask_test.go
- flyteplugins/go/tasks/plugins/k8s/kfoperators/mpi/mpi_test.go
- flyteplugins/go/tasks/plugins/k8s/kfoperators/pytorch/pytorch_test.go
- flyteplugins/go/tasks/plugins/k8s/ray/ray.go
- flyteplugins/go/tasks/plugins/k8s/ray/ray_test.go
Provide a way to add tolerations for extended resources so that users don't have to add it by themselves.
Users can specify what extended resources they would like flyte to add tolerations for them.
- unit tests
- end-to-end tested
> Add tolerations for extended resources

- docs/user_guide/data_types_and_io/structureddataset.md
Code snippets on this [page](https://docs.flyte.org/en/latest/user_guide/data_types_and_io/structureddataset.html#structureddataset) are out of sync of this [Flytesnacks example](https://github.com/flyteorg/flytesnacks/blob/783a180903c22d61c4b93700866f9921353db800/examples/data_types_and_io/data_types_and_io/structured_dataset.py) after recent transition from `rli` to `literalinclude`.
Align code snippets on the doc page with the corresponding example.
https://github.com/flyteorg/flyte/pull/6008
https://flyte--6063.org.readthedocs.build/en/6063/user_guide/data_types_and_io/structureddataset.html
> [Docs] Align sd code lines with Flytesnacks example 

- charts/flyte-sandbox/README.md
- charts/flyte-sandbox/values.yaml
- docker/sandbox-bundled/manifests/complete-agent.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
This adds two environment variables to the sandbox config `FLYTE_PLATFORM_URL` and `FLYTE_PLATFORM_INSECURE` so that these are injected into pods launched by propeller.  These env vars indicate to flytekit that the system is running internally within a sandbox, and how to reach out to the demo sandbox control plane.
Locally by building a sandbox, and registering/running eager tasks against it.
> [demo sandbox] Add env vars to plugin config

- docs/user_guide/development_lifecycle/caching.md
The code block examples in the [Caching documentation](https://docs.flyte.org/en/latest/user_guide/development_lifecycle/caching.html#) look misaligned. This might be due to new code being added to the original file in flytesnacks, which would shift the line numbers. I'm adjusting the line references to match the current code.
Please refer to the changed file down below.
[First code block](https://github.com/flyteorg/flytesnacks/blob/3e92ef9af7245254fbccb9d7b63c6a542b71cef1/examples/development_lifecycle/development_lifecycle/task_cache.py#L44C1-L59C33)
[Second code block](https://github.com/flyteorg/flytesnacks/blob/3e92ef9af7245254fbccb9d7b63c6a542b71cef1/examples/development_lifecycle/development_lifecycle/task_cache.py#L69C1-L91C33)
[Third code …
> Fix inconsistent code examples in caching.md documentation

- flytepropeller/pkg/apis/flyteworkflow/v1alpha1/iface.go
- flytepropeller/pkg/apis/flyteworkflow/v1alpha1/mocks/ExecutableArrayNodeStatus.go
- flytepropeller/pkg/apis/flyteworkflow/v1alpha1/mocks/MutableArrayNodeStatus.go
- flytepropeller/pkg/apis/flyteworkflow/v1alpha1/node_status.go
- flytepropeller/pkg/compiler/transformers/k8s/node.go
- flytepropeller/pkg/controller/nodes/array/handler.go
- flytepropeller/pkg/controller/nodes/array/handler_test.go
- flytepropeller/pkg/controller/nodes/handler/state.go
- flytepropeller/pkg/controller/nodes/node_state_manager.go
- flytepropeller/pkg/controller/nodes/transformers.go
N/A
Currently, timeouts are not supported on ArryaNode subNodes. If there is a timeout set in the task decorator, that is applied only to the overall ArrayNode and not individual subNodes. This change ensures subNodes are executed with timeouts as a standalone execution would be.
We store a `deltaTimestamp` to track `startedAt` for subNode executions. This delta is computed from the overall ArrayNode start time. This is stored using a `bitarray` (just like other ArrayNode subNode metadata), with a preset 18 bits of precision. This means for 5k subNodes there will be approximately 90kb added to the FlyteWorkflow CR - reducing scalability by a small amount. The 18 bits gives us around 3 days of delta time, meaning subNodes start times can be tracked up to 3 days after the overall ArrayNode …
> Support ArrayNode subNode timeouts

- docs/user_guide/customizing_dependencies/raw_containers.md
#6083
Error handling method is unclear for raw container.
Add a short description of how to trigger flyte user error and enable retries in raw containers example.
> [WIP] docs: add raise user error section

- flytepropeller/pkg/compiler/transformers/k8s/utils.go
- flytepropeller/pkg/compiler/transformers/k8s/utils_test.go
https://linear.app/unionai/issue/DX-1202/add-cacke-key-attributes-to-typeannotation
In order to  help the transition to the new version of flytekit, we special-case type annotations that contain a certain key, namely `cache-key-metadata`. The presence of this key will indicate that we should *not* nil out the type annotation field in the CRD.
A change in flytekit will accompany this.
Special-case `TypeAnnotation` objects that contain a key called `cache-key-metadata`, which, as the name suggests, will contain information used to generate unique cache keys.
Unit tests and sandbox.
> Special-case type annotations to force cache invalidations for msgpack-binary literals

- flyteplugins/go/tasks/plugins/k8s/ray/ray.go
- flyteplugins/go/tasks/plugins/k8s/ray/ray_test.go
All functions in `pluginmachinery/utils/marshal_utils.go` are marked as deprecated and should be changed. See:
https://github.com/flyteorg/flyte/blob/be4d009c014d8a514bd60f3b02c270e04d19ac41/flyteplugins/go/tasks/pluginmachinery/utils/marshal_utils.go#L18-L92
Above function is deprecated and suggested using following function instead:
https://github.com/flyteorg/flyte/blob/554b9e9f0929a0cb7bb476dac974bc1b8acc4f3d/flytestdlib/utils/marshal_utils.go#L20-L123
Based on the suggestion of the deprecated function's docstring, we should use functions in `flytestdlib/utils.marshal_utils.go` instead of `pluginmachinery/utils/marshal_utils.go`. Therefor, I rename the original `utils` import to `pluginsUtils`, and add `flytestdlib/utils` as new utils import. See below: …
> fix: modify deprecated functions

- .gitignore
- script/generate_config_docs.sh
NA
After https://github.com/flyteorg/flyte/pull/5972/ we require a config file in order to run the `docs` subcommand in all components. 
We use the `docs` subcommand to produce the rst files under the `docs` directory, e.g. https://github.com/flyteorg/flyte/blob/master/docs/deployment/configuration/generated/flyteadmin_config.rst.
This PR introduces an empty config file to be passed to each of the invocations of the components `docs` subcommands in https://github.com/flyteorg/flyte/blob/master/script/generate_config_docs.sh#L46-L49.
Ran `make release_automation` locally and confirmed that the command succeeds and docs are generated.
> Use an empty config file to produce docs

- docs/user_guide/advanced_composition/dynamic_workflows.md
Since I recently added the merge sort code to `advanced_composition/dynamic_workflow.py`, it makes sense to just reference it using literalinclude instead of copying the code into the docs.
Please refer to the Files changed.
**Before**: Raw Python code included directly in docs
**After**: Using literalinclude to reference code from flytesnacks
https://github.com/flyteorg/flytesnacks/pull/1771
https://docs.flyte.org/en/latest/user_guide/advanced_composition/dynamic_workflows.html#merge-sort
> docs: Refactor merge sort code example to use literalinclude

- docs/user_guide/customizing_dependencies/raw_containers.md
Couple with this [PR](https://github.com/flyteorg/flytesnacks/pull/1773) in flytesnacks, which provides the example code of using ImageSpec in the ContainerTask.
Using ImageSpec in ContainerTask is not documented, and is important if we want to run the files that are not in the image.
> [DOCS] Using ImageSpec in ContainerTask

- .github/workflows/single-binary.yml
- flytestdlib/config/tests/accessor_test.go
- flytestdlib/config/tests/config_cmd_test.go
- flytestdlib/config/viper/testdata/viper_test_config.yaml
- flytestdlib/config/viper/viper.go
- flytestdlib/config/viper/viper_test.go
Reverts flyteorg/flyte#5972
This change forced a config file to be defined for all invocations of the flyte binaries (flytectl, flyteadmin, flytepropeller, etc). The blast radius of missing a config file is a lot bigger than simply flytectl, so reverting this change for now while we consider other options for the original issue.
> Revert "fix: return the config file not found error"

- flyteplugins/go/tasks/pluginmachinery/flytek8s/config/config.go
- flyteplugins/go/tasks/plugins/k8s/kfoperators/pytorch/pytorch.go
- flyteplugins/go/tasks/plugins/k8s/kfoperators/pytorch/pytorch_test.go
For RFC https://github.com/flyteorg/flyte/pull/5598, flytepropeller was given the ability to list error files in the so-called raw output prefix bucket of an execution with the goal of identifying which worker pod in a failed distributed task experienced the first error.
In GCP, listing the error files requires the `"storage.objects.list"` permission which so far wasn't given to propeller. I added this permission to the Flyte propeller custom role [here](https://github.com/unionai-oss/deploy-flyte/pull/40).
That being said, because this feature is therefore not backwards compatible, I propose to make it opt-in.
If you agree with this, I'll make another PR to document this feature and how to activate it [here](https://docs.flyte.org/en/latest/flytesnacks/examples/kfpytorch_plugin/pytorch_mn …
> Fix: Make distributed error aggregation opt-in

- flyteplugins/go/tasks/plugins/k8s/ray/ray.go
We already do this for the head node and submitter pod
See PR title
Tested on an internal deployment, verified labels got added.
> Add default labels and annotations to Ray worker pods too.

- docs/_static/custom.js
- Hitting CMD + K pops up two search dialogs (the `docsearch` and the default one)
This PR adds a script block that gracefully removes the default search dialog from the tree.
1. Build
2. Serve
3. Hit CMD + K
> Fix: Remove the default search dialog if it exists (on CMD + K)

- docs/user_guide/data_types_and_io/index.md
People using polars instead of pandas are afraid that their workflow will not work with Flyte when the documentation does not mention Polars at all.
Adding polars.DataFrame and polars.LazyFrame to the data type mapping documentation to show that these are supported.
https://docs.flyte.org/en/latest/user_guide/data_types_and_io/index.html
https://github.com/flyteorg/flytekit/pull/2695#issuecomment-2546013449
> docs: Update datatype mapping for polars Dataframe and LazyFrame

- flyteplugins/go/tasks/plugins/webapi/agent/config.go
- flyteplugins/go/tasks/plugins/webapi/agent/plugin.go
NA
Improve the error message
Update error message
> improve error message in the agent plugin

- flytepropeller/pkg/controller/nodes/array/event_recorder.go
N/A
Passes `CustomInfo` from `ExternalResourceInfo` through ArrayNode subNode executions.
^^^
Tested locally.
N/A
N/A
> Pass CustomInfo metadata through ArrayNode ExternalResourceInfo (#591)

- flytepropeller/pkg/controller/nodes/branch/handler.go
- flytepropeller/pkg/controller/nodes/branch/handler_test.go
We reuse the same data directory for the branch node and the branch taken (child).
This change adds an additional set of directories to decouple these. It makes sure to copy the child output up to the branch node output like we do in subworkflow
Example
```
from dataclasses import dataclass
from flytekit import conditional, task, workflow
@dataclass
class MyData:
foo: str
@workflow
def root_wf(data: MyData) -> str:
return sub_wf(data=data)
@workflow
def sub_wf(data: MyData) -> str:
check = always_true()
return conditional("decision").if_(check.is_true()).then(conditional_wf(data=data)).else_().fail("not done")
@task
def always_true() -> bool:
return True
@workflow
def conditional_wf(data: MyData) -> str:
return done(data)
@task
def done(data: MyData) -> str:
return f"done ({data.foo})" …
```
> Use child dir for branch taken

- flyteplugins/go/tasks/pluginmachinery/k8s/plugin.go
fix some function names in comment
> chore: fix some function names in comment

- flyteadmin/pkg/manager/impl/task_manager.go
- flyteadmin/pkg/manager/impl/task_manager_test.go
- flyteadmin/pkg/repositories/gormimpl/task_repo.go
Closes #4780 
In current TaskManager CreateTask [code](https://github.com/flyteorg/flyte/blob/8f516e839074d0c1013ab58650a1a0fec575d990/flyteadmin/pkg/manager/impl/task_manager.go#L91-L120), FlyteAdmin checks if a task with the same ID already exists in the database. If it does, FlyteAdmin verifies whether the registered task has a different digest compared to the existing task. If no task with the same ID is found in the database, FlyteAdmin proceeds to create the task in the database.
However, the current approach may lead to a race condition that prevents the digest comparison for two identical tasks from occurring. For example, consider two identical tasks (tasks with the same ID and digest), A and B, being registered to FlyteAdmin simultaneously. It is likely that the digest check …
> Flyteadmin digest comparison should rely on database semantics

- docs/user_guide/data_types_and_io/flytedirectory.md
NA
Due to the transition from `rli` to `literalinclude`, two code snippets on [FlyteDirectory page](https://flyte--6135.org.readthedocs.build/en/6135/user_guide/data_types_and_io/flytedirectory.html) are out of sync of the following two Flytesnacks examples, [folder.py](https://github.com/flyteorg/flytesnacks/blob/master/examples/data_types_and_io/data_types_and_io/folder.py) and [file_streaming.py](https://github.com/flyteorg/flytesnacks/blob/master/examples/data_types_and_io/data_types_and_io/file_streaming.py).
Align code snippets on the doc page with two corresponding examples.
https://github.com/flyteorg/flyte/pull/6008
https://flyte--6149.org.readthedocs.build/en/6149/user_guide/data_types_and_io/flytedirectory.html
> [Docs] Align fd code lines with Flytesnacks examples

- flytestdlib/resolver/k8s_resolver.go
k8s resolver might fail if we set the wrong deployment endpoint for `agent service`, print what error happened will be super helpful.
print service namespace, service name, and response event.
build a propeller image and tested in private cluster.
```zsh
alias dbxt="docker buildx build --platform linux/amd64 -t ";  # --platform linux/amd64
alias dp="docker push"
dbxt futureoutlier/flytepropeller:k8s-resolver-2025-0108-1147 -f Dockerfile.flytepropeller .
dp futureoutlier/flytepropeller:k8s-resolver-2025-0108-1147
use kubectl to edit the image
```
Enhanced Kubernetes resolver logging in Flyte standard library by implementing detailed error logging for watcher creation failures and adding …
> Print K8s Resolver Event for Agent Grpc request debugging

- charts/flyte-binary/README.md
- charts/flyte-binary/templates/deployment.yaml
- charts/flyte-binary/values.yaml
- docker/sandbox-bundled/manifests/complete-agent.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
Some k8s clusters (including the one I work with) have strict requirements when it comes to `securityContext` for pods and containers, enforced by tools like `Gatekeeper.sh`.
These changes introduce the ability to configure `securityContext` at container level (init containers and the main container) within `flyte-binary` Helm Chart.
Specifying a `securityContext` is a Kubernetes best practice, as it allows you to configure various security-related settings (e.g., running as a non-root user, setting read-only file systems, etc.). This helps ensure that deployments adhere to stricter security guidelines and can comply with organizational or regulatory requirements.
- Added optional `securityContext` fields under:
1. `deployment.waitForDB.securityContext` for the `wait-for-db` init …
> Add securityContext for individual containers in flyte-binary Deployment

- flytepropeller/pkg/compiler/transformers/k8s/utils.go
- flytepropeller/pkg/compiler/transformers/k8s/utils_test.go
N/A
Metadata is stripped from all other places in the interface(s). It is unnecessary for type checking and only attributes to bloating the CRD.
Stripping metadata from dataclass types.
Tested under a variety of workflows and 
N/A
N/A
N/A
N/A 
Implementation of metadata stripping functionality for dataclass types in Flyte compiler, modifying StripTypeMetadata function to handle dataclass types and replacing direct struct field access with getter methods. The changes focus on removing unnecessary metadata and reducing CRD bloat while maintaining type safety, with updates to test coverage to verify the functionality.
<br>
<br>
<br>
<br>
<b>Estimated effort to …
> stripping metadata from dataclass types (#626)

- charts/flyte-binary/README.md
- charts/flyte-binary/values.yaml
- charts/flyte-core/README.md
- charts/flyte-core/values.yaml
- docker/sandbox-bundled/manifests/complete-agent.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
- docs/user_guide/flyte_agents/developing_agents.md
- flyteplugins/go/tasks/plugins/webapi/agent/config.go
- flyteplugins/go/tasks/plugins/webapi/agent/config_test.go
This PR adds a default gRPC service configuration to the agent plugin that enables round-robin load balancing.
This ensures consistent and fair distribution of requests across multiple agent instances.
- Added `DefaultServiceConfig` in the default agent configuration with round-robin load balancing policy
- Default value set to: `{"loadBalancingConfig": [{"round_robin":{}}]}`
- change agent endpoint from `dns:///flyteagent.flyte.svc.cluster.local:8000` to `k8s://flyteagent.flyte:8000`
(`"Resolver"."Service Name"."Service Namespace"."Port")`
https://github.com/flyteorg/flyte/pull/6179/files#diff-98835a3d321cfb860916a188ca66ea98efe6c9f3a8314ea89ec2cfdf8ad50066R42-R47
unit test and sandbox.
```python
from flytekit import task, workflow
from …
```
> [flyteagent] Default Service Config Using Round Robin Mechanism

- flytectl/RELEASE.md
We had an incident yesterday (explained in https://github.com/flyteorg/flyte/pull/6100) caused by a bad version of flytectl, but we didn't have explicit instructions on how to yank the faulty flytectl version.
Add instructions on how to yank flytectl from homebrew and from the install.sh script.
> Add instructions on how to yank a flytectl release

- flytestdlib/database/postgres.go
fix function name and comment
Documentation update in postgres.go to clarify the readonly nature of a database connection function. The change improves code clarity by making the documentation more accurate and aligned with the function's actual behavior.
<br>
<br>
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: …
> chore: fix function name and comment

- docs/deployment/agents/index.md
- docs/deployment/agents/k8sservice.rst
Related to https://github.com/flyteorg/flytekit/pull/3004
Adding the documentation for the flyte K8s service agent
docs
local sandbox
In the doc
https://github.com/flyteorg/flytekit/pull/3004 
Added comprehensive documentation for K8s Data Service Agent setup in Flyte deployments, including detailed configuration guides, RBAC setup instructions, and deployment procedures. Documentation covers both Flyte binary and core installation methods with specific instructions for each deployment scenario.
<br>
<br>
<br>
<br>
<b>Estimated effort to review (1-5, …
> [Docs] Add the K8s agent set up document

- flyteplugins/go/tasks/plugins/k8s/ray/ray.go
- flyteplugins/go/tasks/plugins/k8s/ray/ray_test.go
Closes #6198 
When you run GPU workloads on a ray cluster you need to configure the runtime class for GPU pods. Folks need a way to do this without also configuring the runtime class (and associated GPUs) for the submitter pod, which never needs GPUs.
Runtime class names are pulled out of the custom head/worker pod specs and injected into the pod templates set on the kuberay CR.
Unit tests
This PR implements runtime class name configuration support for Ray pod specifications, focusing on GPU workload requirements. The changes enable separate runtime class settings for head and worker pods while maintaining submitter pod independence. The implementation includes custom pod spec handling and kuberay CR pod template integration.
<br>
<br> …
> Configure ray pod runtime class based on custom pod specs

- script/local_build_docs.sh
We need the env var to be present, otherwise `make dev-docs` fails with:
```
...
You must provide your Algolia search API key for DocSearch to work.
...
```
Pipe an env var called `DOCSEARCH_API_KEY` to the command used to build dev docs.
set the env var and ran `make dev-docs` successfully.
This pull request introduces a feature improvement by adding an …
> Define env var for docsearch API key in dev-docs build script

- flytepropeller/pkg/controller/executors/failure_node_lookup.go
- flytepropeller/pkg/controller/executors/failure_node_lookup_test.go
- flytepropeller/pkg/controller/nodes/executor.go
- flytepropeller/pkg/controller/nodes/resolve.go
- flytepropeller/pkg/controller/nodes/resolve_test.go
- flytepropeller/pkg/controller/nodes/subworkflow/subworkflow.go
- flytepropeller/pkg/controller/workflow/executor.go
- flytepropeller/pkg/utils/assert/literals.go
Closes #4574 
In flytekit, we add err promise to the failure node [input interface](https://github.com/flyteorg/flytekit/pull/840/files#diff-b1a8538044c80e14d7998344a528dccb59cf54c9735de724f39d345e5f8dfcf5R290-R293). This err message explains why the workflow failed. However, propeller doesn't pass an error message as an input to the failure node. Therefore, current error message in the failure node is always None.
1. In `FailureNodeLookup`, we added a new attribute `OriginalError` to store runtime execution error.
2. In `NodeExecutor`, `preExecute` func will call a new func `ResolveOnFailureNodeInput` if current execution node is an on failure node, and the new func will inject execution error if `err` input existed in the workflow.
3. Update flytepropeller/pkg/utils/assert/literals.go …
> Pass an error message to the failure node

- flyteplugins/go/tasks/plugins/k8s/kfoperators/pytorch/pytorch.go
- flyteplugins/go/tasks/plugins/k8s/kfoperators/pytorch/pytorch_test.go
Currently, PyTorchJob allows not to specify Worker in case only one worker (Master) is needed for the job. Current functionality of the plugin doesn't allow to do so, however, in some cases we still want to achieve a Master-only PyTorchJob.
Made a change so `pytorch` plugin is no longer complains about a 0-replica worker, but instead - if replicas=0 is passed, plugin just doesn't render it. 
I understand this isn't a best design for the moment, but that is a least-invasive approach to achieve it without changing e.g `pyflyte` validation behavior (if e.g we accept that worker=None could be passed to the PyTorch `task_config`. 
We are running the fork code in our production environment
Enhanced PyTorch operator plugin to support master-only …
> Enable 0 workers replicaSpec for pytorchjob

- flytepropeller/pkg/controller/nodes/task/handler.go
https://github.com/flyteorg/flyte/issues/5574
if the reader is `nil`, we should remove the deck URI.
we should only check if the reader exists, then the deck will exist.
Note: it's possible to render deck in agent's any task and now it's only possible when executing `databricks agent`.
related code snippet: https://github.com/flyteorg/flyte/blob/1f533ab556d670fd6254318114fcc0437377890c/flyteplugins/go/tasks/plugins/webapi/agent/plugin.go#L365-L385
if the reader is `nil`, remove the deck URI.
remote execution with a sensor agent task.
single binary.
This PR enhances the task handler by improving Deck URI removal logic when deck files are absent. The changes include adding null checks for …
> Remove Deck URI in when `OutputReader` is nil

- flyteplugins/go/tasks/pluginmachinery/flytek8s/pod_helper.go
An error occurs when running a workflow because of this error.
Workflow[flytesnacks:development:dynamic.dynamic_wf] failed. RuntimeExecutionError: max number of system retry attempts [11/10] exhausted. Last known status message: failed at Node[n0]. RuntimeExecutionError: failed during plugin execution, caused by: failed to execute handle for plugin [container]: nil Struct Object passed
Accessing PodTemplate correctly.
This is important to improve the readability of …
> fix pod template override error 

- flyteplugins/go/tasks/pluginmachinery/flytek8s/pod_helper.go
https://github.com/flyteorg/flyte/issues/5683
Implementation of additional null pointer checks in pod_helper.go to prevent potential nil pointer dereferences when accessing podTemplate.GetPodSpec(). This defensive programming enhancement improves system stability by preventing runtime crashes from null pointer exceptions.
<br>
<br> …
> Prevent nil pointer in pod helper

- flyteadmin/pkg/manager/impl/execution_manager.go
closes: https://github.com/flyteorg/flyte/issues/6038
Error with concurrent map writes and reads when emitting workflow metrics shown in https://github.com/flyteorg/flyte/issues/6038 due to this [map](https://github.com/flyteorg/flyte/blob/ea00864d3731be95f893f2211b8176ed313d7dbb/flyteadmin/pkg/manager/impl/execution_manager.go#L1882) 
Utilize sync map instead of map
- tested locally
```
➜  ~ curl -s http://localhost:10254/metrics | grep -i scheduled_execution_delay  
flyte:admin:admin:execution_manager:flytesnacks:development:scheduled_execution_delay_ns{quantile="0.5"} 4.9674e+07
flyte:admin:admin:execution_manager:flytesnacks:development:scheduled_execution_delay_ns{quantile="0.9"} 4.9674e+07
flyte:admin:admin:execution_manager:flytesnacks:development:scheduled_execution_delay_ns{quanti …
```
> utilize sync maps to map project mappings of prom watches

- flyteadmin/dataproxy/service.go
- flyteadmin/dataproxy/service_test.go
A deck url not found in node closure shouldn't result in an internal error and instead should return NotFound grpc code
Changing the returned grpc code for the API
Tested by verifying the UI calls are no longer returning 500 and instead returning 404 
The PR implements improved error handling in the data proxy service, changing error codes from Internal to NotFound for missing deck URLs. The test suite underwent significant refactoring with the introduction of CreateDownloadLinkDependencies struct and setup function. Additional test cases were implemented to validate error code behavior for empty deck URLs.
<br>
<br>
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 2
</div>
> Return NotFound error when decks uri is empty (#642)

- flyteplugins/go/tasks/plugins/array/k8s/config_flags_test.go
- flyteplugins/go/tasks/plugins/presto/config/config_flags_test.go
- flytestdlib/logger/config_flags_test.go
Fixed a consistent typo in variable naming across multiple test files, changing 'dereferencableKindsConfig' to 'dereferenceableKindsConfig'. This change enhances code readability and maintains consistent spelling conventions throughout the project's test suite.
<br>
<br>
<br>
<br>
</div>
> fix: typos in documentation files

- docs/user_guide/development_lifecycle/failure_node.md
Related to #6181 
In this [PR](https://github.com/flyteorg/flyte/pull/6181), the error message will be passed to the on_failure node if an error occurs during workflow execution. We have added the relevant documentation in this PR.
Added a note explaining how to pass the error message to the on_failure node.
[PR](https://github.com/flyteorg/flytesnacks/pull/1778)
[https://flyte--6209.org.readthedocs.build/en/6209/user_guide/development_lifecycle/failure_node.html](https://flyte--6209.org.readthedocs.build/en/6209/user_guide/development_lifecycle/failure_node.html)
> Add on failure node passing err message doc

- .github/workflows/checks.yml
- .github/workflows/component_docker_build.yml
- .github/workflows/integration.yml
- .github/workflows/single-binary.yml
NA
As per https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down, all uses of the `actions/cache` gh action prior to v4 are being discontinued. Just this morning we got [hit](https://github.com/flyteorg/flyte/actions/runs/13392379138/job/37402935899) by it.
Update all uses of the gh action to v4.
This is important to improve the readability of release …
> Upgrade gh actions/cache to v4

- flyteplugins/go/tasks/pluginmachinery/flytek8s/utils.go
- flyteplugins/go/tasks/plugins/k8s/dask/dask.go
- flyteplugins/go/tasks/plugins/k8s/dask/dask_test.go
- flyteplugins/go/tasks/plugins/k8s/kfoperators/common/common_operator.go
When a user specifies dask scheduler or worker requests, but not limits, k8s pod scheduling fails with
```
95s         Warning   FailedCreate                        replicaset/a2bjwpn2f5h8666jxmv4-fofhakuy-0-default-worker-944f52ccec-6d86b47fff   Error creating: pods "a2bjwpn2f5h8666jxmv4-fofhakuy-0-default-worker-944f52ccec-k6p94" is forbidden: failed quota: project-quota: must specify limits.cpu for: dask-worker; limits.memory for: dask-worker
85s         Warning   FailedCreate                        replicaset/a2bjwpn2f5h8666jxmv4-fofhakuy-0-default-worker-c20eb58c04-686775db55   (combined from similar events): Error creating: pods "a2bjwpn2f5h8666jxmv4-fofhakuy-0-default-worker-c20eb58c04-2kgxq" is forbidden: failed quota: project-quota: must specify limits.cpu for: dask-worker; …
```
> Upstream: Ensure that k8s plugins (dask, kfoperator) have resource requests and limits set

- docs/deployment/agents/databricks.rst
- docs/deployment/agents/index.md
- docs/deployment/agents/slurm.rst
Issue: https://github.com/flyteorg/flyte/issues/3936
Related to https://github.com/flyteorg/flytekit/pull/3005
Provide users with a step-by-step guide to setting up the Slurm agent from scratch.
Add documentation on setting up the Slurm agent for both local testing and deployment. The documentation includes following sections:
1. Spin up a Slurm cluster
2. Test your Slurm agent locally
https://github.com/flyteorg/flytekit/pull/3005
https://flyte--6231.org.readthedocs.build/en/6231/deployment/agents/slurm.html 
Documentation enhancement PR focused on Slurm agent setup and configuration in Flyte. Provides detailed instructions for cluster setup, SSH configuration, AWS S3 integration, and deployment scenarios. …
> [Docs] Add Slurm agent setup

- flyteplugins/go/tasks/plugins/webapi/agent/plugin.go
NA
Failed to delete the task since we always return err on delete 
check if the error is nil first
Run an agent task and terminate it
NA
NA
Fixed a critical bug in the agent plugin's Delete function by correcting error handling logic. The function now properly returns nil for successful deletions and only returns errors when actual error conditions occur, …
> fix: Correct error handling in delete function

- flyteadmin/pkg/manager/impl/execution_manager.go
- flyteadmin/pkg/manager/impl/execution_manager_test.go
Example: Closes #4568
Our team spent a lot of time debugging why it seemed like max parallelism configuration from launch plans was not translating into workflows kicked off from the launch plan. After digging into the code it turns out the max parallelism is set on the CR but not the execution model stored in the DB so the max parallelism is never reflected in the UI.
Updates the execution model to have the max parallelism value from the execution config which is calculated based on the launch plan parallelism or platform/project defaults. 
Unit tests and tested in our production environment.
Displaying platform defaults 
This PR addresses a critical issue in max parallelism configuration propagation from launch plans to the execution …
> Set the max parallelism on the execution model correctly when triggered by launch plan

- flyteplugins/go/tasks/plugins/k8s/kfoperators/common/common_operator.go
- flyteplugins/go/tasks/plugins/k8s/kfoperators/common/common_operator_test.go
- flyteplugins/go/tasks/plugins/k8s/kfoperators/mpi/mpi.go
- flyteplugins/go/tasks/plugins/k8s/kfoperators/mpi/mpi_test.go
- flyteplugins/go/tasks/plugins/k8s/kfoperators/pytorch/pytorch.go
- flyteplugins/go/tasks/plugins/k8s/kfoperators/pytorch/pytorch_test.go
- flyteplugins/go/tasks/plugins/k8s/kfoperators/tensorflow/tensorflow.go
- flyteplugins/go/tasks/plugins/k8s/kfoperators/tensorflow/tensorflow_test.go
So-called dynamic log links are log links which are not activated by default for all tasks but need to be activated for specific tasks. This is done setting a respective "log link type" in the so-called task config, see e.g. [here](https://github.com/flyteorg/flytekit/blob/43a940fee25d40603dae83d74113571c7a571127/plugins/flytekit-wandb/flytekitplugins/wandb/tracking.py#L124) in the wandb plugin.
These dynamic log links currently don't work for the kubeflow plugins (pytorch, tensorflow, mpi tasks). The reason is that the so-called "task template" in flytepropeller - which contains the task-specific log link config - is not made available to the log link templating engine. This PR fixes this.
Added unit test.
This PR addresses a bug in …
> Fix: Enable kubeflow plugins to use dynamic log links

- docs/user_guide/productionizing/configuring_logging_links_in_the_ui.md
Allowing to configure custom log links for specific tasks has been a widely requested feature, see e.g. [here](https://github.com/flyteorg/flyte/discussions/3666) or [here](https://github.com/flyteorg/flyte/issues/3696#issuecomment-1557992297).
So-called "dynamic log links" which were introduced for this purpose are now used for instance by the wandb or vscode plugins.
How these dynamic log links can be used is not yet documented in the [Configuring logging links in the UI](https://docs.flyte.org/en/latest/user_guide/productionizing/configuring_logging_links_in_the_ui.html) page, this PR adds an explanation.
> Doc: Document usage of dynamic log links

- flyteadmin/pkg/manager/impl/metrics_manager.go
Currently if we get the metrics of an execution containing array nodes, we'll get 504 because we haven't implemented the functionality for array node. However, users may still want to get the metrics of other nodes.
Don't error out for getting metrics of array node
Tested with sandbox
Before:
After:
This PR fixes an issue with array node metrics in Flyte admin by replacing error throwing with warning logs, allowing the system to continue processing other node metrics. The changes improve system resilience and ensure metrics availability even when encountering unimplemented node types.
<br>
<br>
<br>
<br>
</div>
> Don't error out for getting metrics of array node

- docs/deployment/configuration/auth_setup.rst
This adds documentation to the auth config for flyte-core deployments with Okta.  In the case where flyteadmin is running in the same cluster as flytepropeller/flytescheduler, the authentication request from flytescheduler to flyteadmin is made using `http://flyteadmin:80`.  flyteadmin uses the domain in the request to validate the audience in the JWT returned by okta ([code reference](https://github.com/flyteorg/flyte/blob/cf7c638497224aa60912967df529182b4c41b5d5/flyteadmin/auth/handler_utils.go#L114)).   This causes a mismatch between the JWT audience and the expectedAudience when the auth request originates from flytescheduler within the same cluster.  The `allowedAudience` setting takes precedence over the URL extracted from the request, so setting this property in the values file …
> Add allowedAudience to flyte-core external auth deployment documentation

- flytepropeller/pkg/controller/nodes/task/taskexec_context.go
- flytepropeller/pkg/webhook/aws_secret_manager.go
- flytepropeller/pkg/webhook/aws_secret_manager_test.go
Closes https://github.com/flyteorg/flyte/issues/6304
The `env_var` was not supported with the AWS secret manager.
This PR adds `env_var` support to AWS.
Unit tests were added. 
This pull request adds support for an env_var option in the AWS secret manager integration. The production code now injects an extra environment variable when a secret has a non-empty env_var value. Test files have been updated comprehensively to check for correct container configurations and volume mounts.
<br>
<br>
<br>
<br>
</div>
> Add aws secret mamager support to env_var

- flytepropeller/pkg/controller/nodes/executor.go
See [here](https://github.com/flyteorg/flyte/pull/4524#issuecomment-2633583071) for bug description.
> Looking at [this line](https://github.com/flyteorg/flyte/blob/master/flytepropeller/pkg/controller/nodes/executor.go#L980-L980) (the check you linked), the easy fix is to add && p.GetPhase() != handler.EPhaseFailed as you suggest. I'm wondering if we can consolidate these to p.GetPhase() == EPhaseQueued"? because the preExecute` function returns Queued whenever the inputs correctly resolve. Anything else would not require a cache lookup. ([source](https://github.com/flyteorg/flyte/pull/4524#issuecomment-2638104081))
@hamersaw let's go for the `p.GetPhase() != handler.EPhaseFailed` because I'm convinced this is a correct fix and I'm not 100% sure consolidating to ` p.GetPhase() == …
> Fix: fastcache should not cache lookup on failed node

- flytepropeller/pkg/apis/flyteworkflow/v1alpha1/array.go
- flytepropeller/pkg/apis/flyteworkflow/v1alpha1/iface.go
- flytepropeller/pkg/apis/flyteworkflow/v1alpha1/mocks/ExecutableArrayNode.go
- flytepropeller/pkg/compiler/transformers/k8s/node.go
- flytepropeller/pkg/controller/nodes/array/handler.go
- flytepropeller/pkg/controller/nodes/array/handler_test.go
- flytepropeller/pkg/controller/nodes/array/node_execution_context.go
- flytepropeller/pkg/controller/nodes/array/node_execution_context_test.go
fixes: https://linear.app/unionai/issue/BB-3499/cannot-pass-arguments-of-type-list-to-a-partial-function-that-will-be
fixes: https://github.com/flyteorg/flyte/issues/4325
Related: https://github.com/flyteorg/flytekit/pull/3185 + https://github.com/flyteorg/flytekit/pull/3187
Add list support for mapping over partials
Upstream some of the bound inputs support for private fork. ArrayNode handler now has context to determine which inputs are bound.
```
from flytekit import map_task, task, workflow
import functools
import typing
@task
def demo_task(strings: typing.List[str], num: int) -> str:
return f"{num}".join(strings)
@workflow
def demo_wf(strings: typing.List[str] = ["a", "b", "c"], nums: typing.List[int] = [1, 2]) -> None:
map_task(functools.partial(demo_task, …
```
> upstream bound inputs support

- docs/deployment/configuration/cloud_event.rst
- docs/deployment/configuration/eventing.rst
Closes  #3663 
Documentation was incorrect. For GCP you need projectId instead of region.
Setup correct Helm values for GCP.
Tested in CI. Updated a few lines in docs.
**changed**
N/A
N/A
N/A
N/A 
This PR updates event documentation by fixing configuration parameters and enhancing clarity. It removes outdated AWS examples, introduces a tabbed layout for AWS SNS and GCP Pub/Sub, and correctly uses projectId for GCP instead of region. These changes improve documentation accuracy and usability.
<br>
<br>
<br>
<br>
</div>
> Update Event Docs

- flyteadmin/auth/authzserver/claims_verifier.go
- flyteadmin/auth/authzserver/claims_verifier_test.go
because before this change string formatted claims were ignored.
I did run it against keycloak, which was forced to send `scp` claim as string. I.e. `"scp": "all"`
- **fixed**: String formatted scp claim now works 
This PR fixes a critical bug in the authentication module where string formatted scp claims were incorrectly handled. The fix corrects assignment logic in the claims verifier and updates test cases to verify proper scope value processing. The implementation was verified against keycloak to ensure robustness.
<br>
<br>
<br>
<br>
</div>
> fix: really assign string scp claim

- docs/user_guide/customizing_dependencies/imagespec.md
Just fixing a grammatical error in the docs. Text said "in a specify imageSpec environment" instead of "in a _specific_ imageSpec environment"
> fix typo: specify -> specific

- docs/deployment/deployment/multicluster.rst
Related #6369 
Fixs the broken link to Architecture Overview in Deployment Guide.
Updating the link to Architecture Overview with index of Component Architecture
following the "Contributing doc" steps and run the "make html" in the docs folder
- **fixed**
https://flyte--6373.org.readthedocs.build/en/6373/index.html
This pull request fixes a broken link in the Deployment Guide by updating the reference to the Architecture Overview using a Sphinx directive. The change improves documentation navigability and consistency without introducing broader changes, directly addressing the documentation link error.
<br>
<br>
<br>
<br>
<b>Estimated effort to …
> [Docs] Fixing the broken link to Architecture Overview in Deployment Guide

- flytepropeller/pkg/controller/config/config.go
- flytepropeller/pkg/controller/config/config_flags.go
- flytepropeller/pkg/controller/config/config_flags_test.go
- flytepropeller/pkg/controller/nodes/array/handler.go
N/A
This PR makes the ArrayNode `taskPhaseVersion` increment retries configurable. This value is used to resend `TaskExecutionEvents` in the case of ArrayNode eventing failures. It is necessary because ArrayNode uses the `ExternalResourceInfo` fields to populate subNode execution metadata, all of these are included in a singular event. So the `TaskPhaseVersion` is not necessarily correlated to a single phase (as subNode phases can change). To ensure these are populated we need to increment.
^^^
The default value is the current value (ie. 3) so there should be no concerns about merging. …
> Making ArrayNode taskPhaseVersion increment retries configurable (#698)

- flyteplugins/go/tasks/pluginmachinery/internal/webapi/core.go
- flyteplugins/go/tasks/pluginmachinery/webapi/example/config_flags.go
- flyteplugins/go/tasks/pluginmachinery/webapi/example/config_flags_test.go
- flyteplugins/go/tasks/pluginmachinery/webapi/pluginconfig.go
- flyteplugins/go/tasks/pluginmachinery/webapi/pluginconfig_flags.go
- flyteplugins/go/tasks/pluginmachinery/webapi/pluginconfig_flags_test.go
- flyteplugins/go/tasks/plugins/webapi/athena/config_flags.go
- flyteplugins/go/tasks/plugins/webapi/athena/config_flags_test.go
- flyteplugins/go/tasks/plugins/webapi/bigquery/config_flags.go
- flyteplugins/go/tasks/plugins/webapi/bigquery/config_flags_test.go
NA
it will allow people to set the qps to 0~1.
change the type to float64
This PR updates the QPS configuration type from int to float64, enabling fractional values for more precise rate limiting. The changes span core validation logic, command flag definitions, and web API configuration for consistent handling throughout the system. This enhancement allows …
> Change QPS type to float64

- flyteplugins/go/tasks/pluginmachinery/tasklog/template.go
- flyteplugins/go/tasks/pluginmachinery/tasklog/template_test.go
When user specifying log like below, we have to replace the `agentID` to a real name.
```yaml
logs:
kubernetes-enabled: false
cloudwatch-enabled: false
templates:
- displayName: "{{.agentID}}"
templateUris:
- "/console/projects/{{.executionProject}}/domains/{{.executionDomain}}/apps/{{.agentID}}/details/logs"
```
add `replaceAll` in the `Name` section.
This PR …
> [propeller] tasklog bug fix

- flyteadmin/pkg/async/cloudevent/factory.go
- flyteadmin/pkg/async/cloudevent/implementations/sender.go
Closes: https://github.com/flyteorg/flyte/issues/6402
Normalizes cloud event type configuration to lowercase to avoid misconfiguration and match the documentation (specifically regarding Kafka).
Existing unit tests.
This PR normalizes cloud event configuration types to lowercase to prevent misconfigurations and align with documentation standards. Changes include adding the 'strings' package import, modifying switch logic for lowercase conversion, and updating the Kafka receiver constant to match the new standard.
<br>
<br>
<br>
<br>
</div>
> Make cloud events config type lowercase

- flyteadmin/auth/auth_context.go
- flyteadmin/auth/config/config.go
- flyteadmin/auth/config/config_flags.go
- flyteadmin/auth/config/config_flags_test.go
- flyteadmin/auth/config/config_test.go
- There are a number of cases where the OIDC discovery url returns one issuer, but its desirable to use a separately configured / named issuer for validation instead.
There are cases in Azure where this is necessary due to their non-standard OIDC configuration -- which is why this was originally added: https://github.com/coreos/go-oidc/pull/315
There are also cases where it's necessary to use an in-cluster service address, but browser clients are using the external ingress address. Due to cluster DNS configuration, it's possible that flyteadmin may be unable to resolve or use the public ingress address for an Idp, but the internal service address is available. This configuration change allows for that.
- Regenerated flyteadmin code through mise with:
> mise x go@1.22 -- make generate
> OIDC config to allow mismatched discovery / issuer

- charts/flyte-core/README.md
- charts/flyte-core/templates/admin/deployment.yaml
- charts/flyte-core/templates/clusterresourcesync/deployment.yaml
- charts/flyte-core/templates/console/deployment.yaml
- charts/flyte-core/templates/datacatalog/deployment.yaml
- charts/flyte-core/templates/flytescheduler/deployment.yaml
- charts/flyte-core/templates/propeller/deployment.yaml
- charts/flyte-core/templates/propeller/webhook.yaml
- charts/flyte-core/values.yaml
- docker/sandbox-bundled/manifests/complete-connector.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
There is no feasible way to manage Flyte database secret rotation from **external secret source** when installing Flyte through Helm charts in AWS EKS (I doubt it's possible in other clouds either). This is a common approach taken with AWS RDS, where AWS manages the database secret rotation automatically through secrets manager. While [external secrets operator](https://external-secrets.io/latest/) is able to update Kubernetes native secrets based on changes in an external source (e.g. AWS Secrets Manager), it doesn't restart pods mounting those secrets, leaving the rotation incomplete in this case.
Add ability to annotate Kubernetes deployments created by the flyte-core Helm chart. This makes it possible to use external operators, such as [Reloader](https://github.com/stakater/Reloader), …
> Allow configuring deployment annotations in Helm chart

- charts/flyte-core/README.md
- charts/flyte-core/templates/propeller/webhook.yaml
- charts/flyte-core/values.yaml
- docker/sandbox-bundled/manifests/complete-connector.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
Example: Relates to #6430 
In order to support highly available, production ready deployments of Flyte it can be useful to spread replicas of pods across nodes and failure domains. 
Allows for plumbing of pod affinity & topology spread constraints
Tested in our production environment. 
This PR enhances the webhook component with affinity and topologySpreadConstraints support, improving pod scheduling for production deployments. The chart templates and values files now include these configurations for better pod placement control. Docker manifests have been updated with proper secret values and checksum annotations to ensure configuration consistency.
<br>
<br>
<br>
<br>
<b>Estimated effort to review (1-5, lower …
> Add support for affinity & topologySpreadConstraints to webhook component

- docs/user_guide/customizing_dependencies/imagespec.md
- docs/user_guide/customizing_dependencies/multiple_images_in_a_workflow.md
- docs/user_guide/flyte_fundamentals/optimizing_tasks.md
NA
To enhance the user experience, the concept of `container` should be abstracted from flytekit users.
Rename `container_image` to `image` for `flytekit.task()` decorator.
https://github.com/flyteorg/flytekit/pull/3094
* https://flyte--6211.org.readthedocs.build/en/6211/user_guide/flyte_fundamentals/optimizing_tasks.html
* https://flyte--6211.org.readthedocs.build/en/6211/user_guide/customizing_dependencies/multiple_images_in_a_workflow.html
* https://flyte--6211.org.readthedocs.build/en/6211/user_guide/customizing_dependencies/imagespec.html
> [Docs] Rename container_image to image for improved UX

- flyteadmin/pkg/config/config.go
- flyteadmin/pkg/config/serverconfig_flags.go
- flyteadmin/pkg/config/serverconfig_flags_test.go
- flyteadmin/pkg/server/service.go
N/A (internal stability enhancement)
Under high load, FlyteAdmin currently accepts all gRPC requests without constraint due to the lack of a MaxConcurrentStreams configuration. This can lead to unbounded in-flight requests, resulting in excessive memory usage, DB connection exhaustion, increased latency, and eventual cancellations or INTERNAL errors.
Adding a MaxConcurrentStreams limit allows the gRPC server to enforce backpressure at the transport layer, ensuring that only a bounded number of requests are actively processed at a time. This helps stabilize system behavior under bursty or sustained traffic conditions, particularly for high-volume APIs coming from propeller
Introduced MaxConcurrentStreams as a configurable field in the FlyteAdmin gRPC server configuration.
Updated the …
> Set MaxConcurrentStreams for flyteadmin grpc server

- flyteplugins/go/tasks/pluginmachinery/flytek8s/pod_helper.go
- flyteplugins/go/tasks/pluginmachinery/flytek8s/pod_helper_test.go
N/A
`NodeShutdown` observed in more rare cases where GCP preempts nodes. Update `DemystifyFailure` to respect `NodeShutdown` reason and count it as retryable system error.
^^^
local and cloud deployment
This pull request enhances node preemption handling in the Flyte plugin by adding 'NodeShutdown' as a retryable system error. It updates the logic in the `DemystifyFailure` function and includes test cases to validate the new behavior, improving robustness against GCP node preemptions.
<br>
<br>
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 2 - The changes are straightforward and well-documented, making the review process relatively quick.
</div>
> Update `DemystifyFailure` to respect `NodeShutdown` (#724)

- charts/flyte-core/README.md
- charts/flyte-core/templates/admin/deployment.yaml
- charts/flyte-core/templates/clusterresourcesync/deployment.yaml
- charts/flyte-core/templates/console/deployment.yaml
- charts/flyte-core/templates/datacatalog/deployment.yaml
- charts/flyte-core/templates/flytescheduler/deployment.yaml
- charts/flyte-core/templates/propeller/deployment.yaml
- charts/flyte-core/templates/propeller/webhook.yaml
- charts/flyte-core/values.yaml
- docker/sandbox-bundled/manifests/complete-connector.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
Closes #6446
This allows users to customize the rollout strategy of different flyte components.
Makes the rollout strategy configurable for different flyte components.
It was not tested.
This pull request enhances Flyte deployment flexibility by introducing configurable rollout strategies for various components, including updates to deployment YAML files and adjustments to secrets and checksums. These modifications aim to improve customization and streamline the deployment process.
<br>
<br>
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 2 - The changes are straightforward and well-documented, making the review process relatively quick.
</div>
> Allow rollout strategy to be configured in Helm charts

- flyteplugins/go/tasks/pluginmachinery/flytek8s/pod_helper.go
- flyteplugins/go/tasks/pluginmachinery/flytek8s/pod_helper_test.go
Identified a unique, fairly rare, edge case in certain cloud providers (e.g GKE) where the kubelet rejects the pod due to lacking NodeAffinity requirements prior the underlying controller manager applying the appropriate labels.
We would see workflows failing with 
```
[...]: [...] currentAttempt done. Last Error: USER::Pod was rejected: Predicate NodeAffinity failed: node(s) didn't match Pod's node affinity/selector
``` 
Treat Pod failures with `status.reason` of `NodeAffinity` as a retryable system error.
Unit tests.
This pull request enhances the handling of pod failures in cloud environments by treating 'NodeAffinity' status as a retryable error, improving workflow …
> Treat kubelet NodeAffinity status.reason as retryable system error

- flyteplugins/go/tasks/plugins/webapi/agent/client.go
- flyteplugins/go/tasks/plugins/webapi/agent/client_test.go
- flyteplugins/go/tasks/plugins/webapi/connector/client.go
- flyteplugins/go/tasks/plugins/webapi/connector/client_test.go
Closes #6349 
The current propeller agent/connector task_type auto-discovery in combination with ignoring the explicit mapping will cause problems while 2 agent/connector deployments has different config but has the same support task type. On the other hand, it also complicates agent development. Developers have to be mindful of which agents are installed on the image and cannot simply rely on the mapping in the configuration.
Respect the explicit task_type mapping over the implicit (auto-discovery) mapping. The agent/connector registry will always inline with the `agentForTaskTypes` settings in the config file.
The unit test in this PR can test the expected behavior.
- **changed**: For changes in existing …
> Agent auto discovery conflicts with explicit task type mapping

- charts/flyte-core/README.md
- charts/flyte-core/templates/admin/deployment.yaml
- charts/flyte-core/values.yaml
- docker/sandbox-bundled/manifests/complete-connector.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
Certain flyte images may not have access to curl binaries which may cause readiness and liveness probes to fail for flyteadmin.
This PR adds readiness and liveness probe of flyteadmin to be overridable but keeping the original ones as defaults in the values file.
This makes sure there are no differences in the generated file
Introduce value overrides for both readiness and livesProbe for flyteadmin deployment
No diff between the original generated helm manifest
This pull request enhances the Flyteadmin deployment by making readiness and liveness probes configurable via the values file, while preserving original defaults. It also updates checksums for several secrets to ensure security integrity. …
> Provide overrides for flyteadmin readiness and liveness probes

- .github/ISSUE_TEMPLATE/bug_report.yaml
It is helpful to understand which version of Flyte a user is running when they are reporting a bug in the event that the bug is fixed in later versions of Flyte.  
This pull request enhances the bug report template by adding a new field for users to specify the version of Flyte and Flytekit. This improvement aims to provide essential context for diagnosing issues, thereby streamlining the resolution of version-specific bugs.
</div>
> Add version details to bug report template

- script/prepare_artifacts.sh
Releasing beta release charts fail https://github.com/flyteorg/flyte/actions/runs/15454959519/job/43505569848
When the released version is beta then format the semver for release to be compatible with helm
Independently tested the changed portion
```
cat a.sh                                                                                                 .venv-new-2
if [[ "$VERSION" =~ b[0-9]+ ]]; then
VERSION=$(echo "${VERSION}" | sed -E 's/b([0-9]+)/-beta.\1/')
fi
echo $VERSION
```
```
VERSION=v1.15.3 sh a.sh                                                                               
v1.15.3
```
```
VERSION=v1.16.0b0 sh a.sh                                                                                .venv-new-2
v1.16.0-beta.0
```
<div …
> Fix release script for beta versions

- docs/deployment/configuration/cloud_event.rst
- flyteadmin/go.mod
- flyteadmin/go.sum
- flyteadmin/pkg/async/cloudevent/factory.go
- flyteadmin/pkg/async/cloudevent/factory_test.go
- flyteadmin/pkg/async/cloudevent/implementations/cloudevent_publisher_test.go
- flyteadmin/pkg/async/cloudevent/implementations/sender.go
- flyteadmin/pkg/async/cloudevent/implementations/sender_test.go
- flyteadmin/pkg/async/cloudevent/interfaces/publisher.go
- flyteadmin/pkg/async/cloudevent/interfaces/sender.go
- flyteadmin/pkg/runtime/interfaces/application_configuration.go
- go.mod
- go.sum
To add a new cloud events egress.
To support NATS as **cloud events sender** other than the existing ones.
- Added proper unit tests
- Install Flyte
- Create NATS Docker container
- Check the `NATS` tab at docs page`flyte/deployment/flyte-configuration/cloud_events/#configuration` to properly configure  Flyte to send cloud-events via Nats
- [*] I updated the documentation accordingly.
- [*] All new and existing tests passed.
- [*] All commits are signed-off.
This pull request introduces NATS as a new cloud events sender, enhancing the Flyte system's capabilities beyond Kafka. It includes updates to the publisher and sender interfaces, new configuration options, and comprehensive documentation. Unit …
> add: nats as cloud events sender

- flyteplugins/go/tasks/pluginmachinery/flytek8s/copilot.go
- flyteplugins/go/tasks/pluginmachinery/flytek8s/copilot_test.go
We remove the shared namespace process watcher in the PR #6501 and use the new signal watcher instead. Therefor, the config related to shared namespace process watcher can be removed.
- Remove `SYS_PTRACE` and `ShareProcessNamespace` settings
None
Follow up #6501
This pull request enhances the CoPilot configuration by …
> [FIX] remove SYS_PTRACE and sharenamespace settings

- flytecopilot/cmd/root.go
- flytepropeller/cmd/kubectl-flyte/cmd/root.go
fix some minor issues in the comments
This pull request improves code documentation by updating function names in comments for better clarity. It addresses minor issues without changing any functionality.
</div>
> chore: fix some minor issues in the comments

- flyte-single-binary-local.yaml
- flyteplugins/go/tasks/pluginmachinery/flytek8s/copilot.go
- flyteplugins/go/tasks/pluginmachinery/flytek8s/copilot_test.go
- flyteplugins/go/tasks/plugins/k8s/pod/plugin.go
Containers task sometimes fails because
1. Propeller fails to read the output because it tries to get the output before the sidecar completes.
2. The sidecar is terminated before it can upload the file because the main container finishes before the signal watcher is created. As a result, the sidecar doesn’t handle the SIGTERM signal properly and gets killed by Kubernetes
* Modified `AddCoPilotToPod` to prepend the sidecar container to the list of init containers, ensuring the sidecar starts before the downloader. This guarantees the signal watcher is active before the main container completes. 
* Updated `DemystifyPodStatus` to check the status of init containers in addition to regular containers. This ensures that tasks are only marked as succeeded when both containers and sidecars have …
> refactor: Adjust CoPilot init and Pod status logic

- flyteplugins/go/tasks/pluginmachinery/flytek8s/pod_template_store.go
https://github.com/flyteorg/flyte/issues/6529
Without that, in cases where `podTemplate` is involved we could get unexpected resource overrides from previous runs. 
I changed LoadOrDefault() to return a deep copy of the cached pod template, this ensures that each workflow gets its own independent copy of the pod template, preventing any mutations from affecting other workflows
I've tested it in the Flyte multi-cluster environment of ours (devel)
This is a follow-up for https://github.com/flyteorg/flyte/pull/6483 
This pull request resolves resource state pollution in PodTemplate management within the Flyte framework by ensuring each workflow has an independent PodTemplate copy. This change is vital …
> Fix PodTemplate resource state pollution between workflow runs

- flyteadmin/pkg/config/config.go
- flyteadmin/pkg/config/serverconfig_flags.go
- flyteadmin/pkg/config/serverconfig_flags_test.go
- flyteadmin/pkg/server/service.go
Closes #6274 
To handle SIGTERM properly, ensure cleanup of resources and provide smooth user experience
Implement graceful shutdown for flyteadmin servers
This pull request enhances the flyteadmin servers by implementing a graceful shutdown mechanism with a configurable timeout for resource cleanup. It also improves …
> fix: flyteadmin doesn't shutdown servers gracefully

- flytepropeller/pkg/apis/flyteworkflow/v1alpha1/error.go
- flytepropeller/pkg/apis/flyteworkflow/v1alpha1/iface.go
- flytepropeller/pkg/apis/flyteworkflow/v1alpha1/node_status.go
- flytepropeller/pkg/apis/flyteworkflow/v1alpha1/node_status_test.go
Closes #6520 
The [core propeller logic has a branch which compares the workflow read from etcD to the workflow that may have been mutated by the propeller state machine logic](https://github.com/flyteorg/flyte/blob/master/flytepropeller/pkg/controller/handler.go#L320-L326).The intention is that if the workflow status is the same it does not bother writing the workflow to etcD. The comparator logic for this operation includes bugs where two workflow that have the same state are considered different and thus trigger an etcD write (or at least an API call). As such, a shockingly high amount of our workflow update are redundant, wasted API calls (~60%). 
This pull request proposes to only set the `dirty` flags in TaskNodeStatus when a value is set that differs from the existing value. This …
> Fix workflow equality check

- deployment/stats/prometheus/flytepropeller-dashboard.json
- stats/flytepropeller.dashboard.py
Closes #6545 
These dashboard queries were incorrect
Fixes the dashboard query
Tested in production
Before
After (wfs obfuscated)
This pull request corrects the Grafana dashboard queries for dynamic workflow metrics, ensuring accurate data representation. The modifications have been tested in production to validate their effectiveness.
</div>
> Fix Grafana dashboard queries for dynamic workflow metrics

- charts/flyte-core/README.md
- charts/flyte-core/values-keycloak-idp-flyteclients-without-browser.yaml
- charts/flyte-core/values-sandbox.yaml
- charts/flyte-core/values.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_controlplane_generated.yaml
- deployment/eks/flyte_helm_dataplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_controlplane_generated.yaml
- deployment/gcp/flyte_helm_dataplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- docker/sandbox-bundled/manifests/complete-connector.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
Closes #6562 
Helm charts shouldn't have references to implementation specific ingress annotations, especially ones not even used by Flyte. This should help reduce confusion when folks see the annotations in their Kubernetes resources. 
Note: this may be a breaking change for the rare folks using project contours and relying on the default annotations.
Eliminating projectcontour annotations from the flute-core helm chart
See unit tests
This pull request enhances the Flyte helm charts by removing unused projectcontour annotations, reducing user confusion. It also updates several secrets across manifest files for improved consistency and security. While this may be a breaking change for some users, …
> Remove projectcontour annotations from helm charts by default

- charts/flyte-core/README.md
- charts/flyte-core/templates/flytescheduler/service-monitor.yaml
- charts/flyte-core/templates/flytescheduler/service.yaml
- charts/flyte-core/values.yaml
- docker/sandbox-bundled/manifests/complete-connector.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
Closes #6557 
It is helpful to have service monitors so that prometheus metrics can be scraped and used in dashboards for observability.
Adds the option to render a service monitor for flyte scheduler
Tested in our production environment
This pull request introduces a new feature for configuring a service monitor for the Flyte scheduler, enhancing observability through Prometheus metrics. It includes a ServiceMonitor and service definition in the Helm chart, along with updates to shared secrets in manifest files for improved security.
</div>
> Add option to configure service monitor for flyte scheduler

- flyteadmin/scheduler/core/gocron_scheduler.go
- flyteadmin/scheduler/core/gocron_scheduler_test.go
Related to #6470 
Fix issue where Flyte scheduler enters infinite loop and OOM when given an invalid cron expression like `0 0 31 2 *`. The [cron parser library](https://github.com/unionai/cron/blob/master/parser.go#L88-L153) returns the default date (0001-01-01) for such expressions, which leads to an infinite scheduling loop.
This PR introduces a hotfix to break the while loop and return an error when the Flyte scheduler encounters an invalid cron expression during schedule time calculation. However, the underlying cron parser library should be properly updated to handle invalid cron expressions correctly.
Test workflow:
```
from datetime import datetime
from flytekit import task, workflow, CronSchedule, LaunchPlan
@task
def task_1(message: str) -> str:
return message
@workflow
def …
```
> [BUG] invalid cron date schedule creates infinite loop in flytescheduler

- flyteadmin/auth/cookie_manager_test.go
- flyteadmin/go.mod
- flyteadmin/go.sum
This removes references to a version of golang-jwt that has security issues: https://github.com/flyteorg/flyte/security/dependabot/359
I don't believe we even use this version as we import v4/v5 too.
Remove referene to version-less golang-jwt import. 
This pull request enhances the project's security by removing references to the outdated golang-jwt v3 library and updating to golang-jwt v4. It includes modifications to import statements in test files and updates to go.mod and go.sum files to ensure secure dependencies.
</div>
> Remove usage of golang-jwt v3

- charts/flyte-core/README.md
- charts/flyte-core/templates/datacatalog/deployment.yaml
- charts/flyte-core/templates/datacatalog/hpa.yaml
- charts/flyte-core/values.yaml
- docker/sandbox-bundled/manifests/complete-connector.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
Depending on the workflows being run by FlytePropeller data catalog load can be quite dynamic. It would be nice otherwise support horizontal pod autoscalers. 
Adds support for horizontal pod autoscaler for data catalog.
Tested in our production environment. 
This pull request adds support for horizontal pod autoscalers (HPA) in the Flyte data catalog, enabling dynamic scaling based on workload. It includes a new HPA configuration in the Helm chart and updates several manifests with shared secrets to improve scalability and performance.
</div>
> Add HPA for datacatalog

- flyteplugins/go/tasks/plugins/array/k8s/integration_test.go
- flyteplugins/go/tasks/plugins/k8s/pod/plugin.go
- flyteplugins/go/tasks/plugins/k8s/pod/sidecar_test.go
`v1.PodUnknown` has been deprecated and unused since 2015. My IDE has warning messages and I figured it should be safe to just cleanup this part of the code.
See: https://pkg.go.dev/k8s.io/api/core/v1@v0.28.2#PodUnknown
Removes all references to `v1.PodUnknown` pod phase.
Unit tests
This pull request removes all references to the deprecated pod phase `v1.PodUnknown`, which has been unused since 2015. The updates across multiple files enhance code cleanliness and maintain functionality. Unit tests were added to ensure existing features remain intact.
</div>
> Remove use of deprecated pod phase

- flytepropeller/pkg/controller/nodes/task/handler.go
Closes #6643
The plugin resolution code will return a nil plugin if the task type matches the connector service or agent service but those plugins haven't been enabled and assigned a core plugin.
Add additional nil checks before returning core plugins
No tests, as there are no tests for the new connector service code.
This pull request enhances the plugin resolution logic by adding nil checks before returning core plugins for the connector and agent services. These changes improve robustness by ensuring that a nil plugin is returned if the corresponding services are not enabled, preventing potential errors in plugin resolution.
</div>
> Only return connector/agent plugins if enabled
