- rsts/user/getting_started/create_first.rst
- updated `myworkflow` -> `myflyteproject`
- added a `cd python` step
- updated `workflows` -> `single_step`
- added `mkdir -p workflows` since that directory is preconfigured but not yet created
> updated getting started page with correct instructions

- rsts/user/tasktypes/index.rst
- rsts/user/tasktypes/presto.rst
* Initial set of document which will go in here -- https://lyft.github.io/flyte/user/tasktypes/index.html
> Add initial documentation for presto task

- rsts/introduction/roadmap.rst
- Adds details of how Milestones work and how change management works
> Roadmap document updated with process

- CHANGELOG/CHANGELOG-v0.3.0.md
- Makefile
- deployment/eks/flyte_generated.yaml
- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- end2end/tests/endtoend.yaml
- kustomize/base/admindeployment/deployment.yaml
- kustomize/base/propeller/deployment.yaml
- kustomize/overlays/eks/admindeployment/admindeployment.yaml
- kustomize/overlays/eks/admindeployment/cron.yaml
- kustomize/overlays/sandbox/admindeployment/admindeployment.yaml
- kustomize/overlays/sandbox/admindeployment/cron.yaml
- rsts/administrator/install/getting_started.rst
- rsts/conf.py
- rsts/introduction/docs_overview.rst
- rsts/user/getting_started/create_first.rst
Please refer to https://github.com/lyft/flyte/issues/301 for a listing of the issues included.
> Milestone 0.3.0 release

- CHANGELOG/CHANGELOG-v0.4.0.md
- Makefile
- README.md
- deployment/eks/flyte_generated.yaml
- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- end2end/tests/endtoend.yaml
- kustomize/base/admindeployment/deployment.yaml
- kustomize/base/console/deployment.yaml
- kustomize/base/propeller/deployment.yaml
- kustomize/overlays/eks/admindeployment/admindeployment.yaml
- kustomize/overlays/eks/admindeployment/cron.yaml
- kustomize/overlays/sandbox/admindeployment/admindeployment.yaml
- kustomize/overlays/sandbox/admindeployment/cron.yaml
- rsts/conf.py
Versions:
IDL: [v0.17.32](https://github.com/lyft/flyteidl/releases/tag/v0.17.30)
Admin: [v0.2.8](https://github.com/lyft/flyteadmin/releases/tag/v0.2.8)
Propeller: [v0.2.45](https://github.com/lyft/flytepropeller/releases/tag/v0.2.45)
DataCatalog: [v0.2.1](https://github.com/lyft/datacatalog/releases/tag/v0.2.1)
Flytekit: [v0.8.1](https://github.com/lyft/flytekit/releases/tag/v0.8.1)
FlyteConsole: [v0.5.3](https://github.com/lyft/flyteconsole/releases/tag/v0.5.3)
FlytePlugins: [v0.3.28](https://github.com/lyft/flyteplugins/releases/tag/v0.3.28)
> Milestone v0.4.0

- deployment/eks/flyte_generated.yaml
- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- kustomize/overlays/eks/admindeployment/flyteadmin_config.yaml
- kustomize/overlays/sandbox/admindeployment/clusterresource-templates/ad_spark-role.yaml
- kustomize/overlays/sandbox/admindeployment/clusterresource-templates/ae_spark-service-account.yaml
- kustomize/overlays/sandbox/admindeployment/clusterresource-templates/af_spark-role-binding.yaml
- kustomize/overlays/sandbox/admindeployment/flyteadmin_config.yaml
- kustomize/overlays/sandbox/admindeployment/kustomization.yaml
- Removes the legacy spark whitelist.
- Bump up resource-quotas to minimal values required to run one spark job: one driver and one executor with 1 cpu each.
- Add namespace level roles/bindings
> Update/Add Spark Configs

- kustomize/base/operators/kfoperators/tensorflow/kustomization.yaml
Add kustomization for tensorflow plugin
> kustomization for tensorflow plugin

- CHANGELOG/CHANGELOG-v0.6.0.md
- Makefile
- README.md
- deployment/eks/flyte_generated.yaml
- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- end2end/tests/endtoend.yaml
- kustomize/base/admindeployment/deployment.yaml
- kustomize/base/console/deployment.yaml
- kustomize/base/propeller/deployment.yaml
- kustomize/overlays/eks/admindeployment/admindeployment.yaml
- kustomize/overlays/eks/admindeployment/cron.yaml
- kustomize/overlays/sandbox/admindeployment/admindeployment.yaml
- kustomize/overlays/sandbox/admindeployment/cron.yaml
- rsts/conf.py
FlyteIDL: v0.18.0
FlytePropeller: v0.3.2
FlyteAdmin: v0.3.0
FlytePlugins: v0.4.1
Flytekit: v0.11.3
DataCatalog: v0.2.1
FlyteConsole: v0.8.0
> Milestone 0.6.0 release

- deployment/eks/flyte_generated.yaml
- deployment/gcp/flyte_generated.yaml
- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- kustomize/overlays/eks/config/propeller/enabled_plugins.yaml
- kustomize/overlays/eks/kustomization.yaml
- kustomize/overlays/gcp/config/propeller/enabled_plugins.yaml
- kustomize/overlays/gcp/kustomization.yaml
- kustomize/overlays/sandbox/config/propeller/enabled_plugins.yaml
- kustomize/overlays/sandbox/kustomization.yaml
- kustomize/overlays/test/kustomization.yaml
> Update propeller version and config

- rsts/user/getting_started/end_to_end_workshop.md
Accompanies https://github.com/lyft/flyteplayground/pull/81
> Simplify instructions for Makefile edits

- README.md
https://github.com/spotify/flytekit-java/tree/master/flytekit-scala is the native Scala support layer.
> Add Scala as support language

- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- kustomize/overlays/sandbox/dependencies/storage/storage.yaml
- kustomize/overlays/test/dependencies/storage/storage.yaml
Mostly to enhance the getting starting experience when trying out Flyte.
> Update MinIO Docker image in test and sandbox

- CHANGELOG/CHANGELOG-v0.10.0.md
- Makefile
- deployment/eks/flyte_generated.yaml
- deployment/gcp/flyte_generated.yaml
- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- docs_infra/in_container_rst_generation.sh
- end2end/tests/endtoend.yaml
- kustomize/base/admindeployment/clustersync/cron.yaml
- kustomize/base/admindeployment/deployment.yaml
- kustomize/base/console/deployment.yaml
- kustomize/base/propeller/deployment.yaml
- kustomize/overlays/eks/kustomization.yaml
- kustomize/overlays/gcp/kustomization.yaml
- kustomize/overlays/sandbox/admin/deployment.yaml
- kustomize/overlays/sandbox/kustomization.yaml
- kustomize/overlays/test/kustomization.yaml
- rsts/conf.py
- script/generate_docs.sh
- script/update_ref_docs.sh
FlyteIDL: v0.18.11
FlytePropeller: 0.5.13
FlyteAdmin: v0.3.29
FlytePlugins: v0.5.20
Flytekit: v0.16.0a2
DataCatalog: v0.2.1
FlyteConsole: v0.19.1
> Milestone v0.10.0 release

- Makefile
- rsts/conf.py
- rsts/contributor/docs/index.rst
- rsts/index.rst
See docs
* Ran pycharm format
* Removed an unused Make target, I think.
> Add intersphinx config, docs on how to use

- rsts/conf.py
- rsts/howto/enable_and_use_schedules.rst
Just copied what Katrina had from the old guide
> [Docs] - schedules how to

- README.md
> Docs status added to the README

- rsts/howto/enable_backend_plugin.rst
- rsts/howto/multi_cluster/index.rst
- rsts/howto/resource_quota.rst
- rsts/plugins/spark_k8s.rst
- Explains how to install the plugin
- How to enable it
> Spark plugin docs

- rsts/dive_deep/observability.rst
- rsts/howto/monitoring/index.rst
- rsts/plugins/extend/flyte_backend.rst
- rsts/plugins/extend/flytekit_python.rst
- rsts/plugins/extend/intro.rst
> Docs Update: Extending flyte & deploying observability

- rsts/conf.py
Update the copyright date of the documentation to show it's still maintained.
> Update Docs Copyright date

- .github/workflows/tests.yml
- deployment/eks/flyte_generated.yaml
- deployment/gcp/flyte_generated.yaml
- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- kustomize/base/admindeployment/clustersync/cron.yaml
- kustomize/base/admindeployment/deployment.yaml
- kustomize/base/datacatalog/deployment.yaml
- kustomize/base/propeller/deployment.yaml
- kustomize/overlays/eks/kustomization.yaml
- kustomize/overlays/gcp/kustomization.yaml
- kustomize/overlays/sandbox/flyte/admin/deployment.yaml
- kustomize/overlays/sandbox/kustomization.yaml
- kustomize/overlays/test/flyte/admin/deployment.yaml
- kustomize/overlays/test/kustomization.yaml
Updates flytepropeller to v0.7.1, flyteadmin to v0.3.38 and datacatalog to v0.3.0
> Update deployments with latest k8s library deps

- rsts/conf.py
For consistent header text on nav header
> update tutorials header text

- README.md
> Add striveworks to users list in README

- rsts/conf.py
> show hidden toc

- end2end/tests/endtoend.yaml
Signed-off-by: wild-endeavor <wild-endeavor@users.noreply.github.com>
https://github.com/flyteorg/flytetools/pull/30
> Switch end-to-end test to one that uses flytectl

- rsts/_static/custom.css
- rsts/conf.py
Update dark theme styles for readthedocs search bar
> dark theme updates

- deployment/stats/prometheus/flyteadmin-dashboard.json
- deployment/stats/prometheus/flytepropeller-dashboard.json
- stats/flyteadmin_dashboard.py
- stats/flytepropeller_dashboard.py
- Adds more dashboard metrics
- Useful in understanding any performance problems with Flytepropeller
> Dashboard updates

- .github/workflows/sandbox.yml
- docker/sandbox/Dockerfile
- Added flytectl in sandbox
Pre request:
- https://github.com/flyteorg/flyte/pull/927
> Added flytectl in sandbox

- deployment/eks/flyte_generated.yaml
- deployment/gcp/flyte_generated.yaml
- deployment/sandbox/flyte_generated.yaml
- kustomize/base/ingress/ingress.yaml
- kustomize/overlays/eks/flyte/ingress/ingress_grpc.yaml
https://github.com/flyteorg/flyte/issues/925
> Add Auth Ingress endpoints

- README.md
> Updated Readme.md with CII Badge

- rsts/community/troubleshoot.rst
- rsts/getting_started.rst
- rsts/index.rst
* Added possible workarounds if an error pops up with the `make start` command
* Added `make register` besides `make fast_register` to specify its usage
> Include troubleshooting guide in the docs

- rsts/howto/managing_customizable_resources.rst
> Added link to flytectl customize cluster attributes

- rsts/concepts/admin.rst
- rsts/concepts/admin_service.rst
- rsts/concepts/architecture.rst
- rsts/concepts/customizable_resources.rst
- rsts/concepts/state_machine.rst
- rsts/concepts/tasks.rst
- rsts/conf.py
- rsts/howto/managing_customizable_resources.rst
> Added intersphinx links to IDL docs

- rsts/index.rst
> fix community link

- .github/workflows/create-release.yml
- .github/workflows/generate-flyte-manifest.yml
- .goreleaser.yml
- script/release.sh
- Updated template of flyte release title
- Added auto changelog pick from `CHANGELOG` dir
- Small fix in `release.sh`
- Rename workflow file name and their title (In past it become confusing for everyone)
> Rename flyte manifest Workflow and add changelog support

- helm/.values-template.yaml
Before the change Admin wont come up and the syncresources pod would have the following error.
```
{"json":{"src":"clusterresource.go:104"},"level":"fatal","msg":"Failed to sync cluster resources [Failed to decode namespace config template [ae_spark_service_account.yaml] for namespace [flytectldemo-development] into a kubernetes object with err: yaml: invalid map key: map[interface {}]interface {}{\"defaultIamRole\":interface {}(nil)}, Failed to decode namespace config template [ae_spark_service_account.yaml] for namespace [flytectldemo-staging] into a kubernetes object with err: yaml: invalid map key: map[interface {}]interface {}{\"defaultIamRole\":interface {}(nil)}, Failed to decode namespace config template …
```
> Set a default value for defaultIamRole template value

- rsts/getting_started.rst
> Fixing Getting started

- rsts/deployment/aws/manual.rst
Link to the changes
https://flyte--1189.org.readthedocs.build/en/1189/deployment/aws/manual.html#deployment-aws-manual
> PR Into 1187 : More fixes for the remote docs

- rsts/getting_started.rst
> Added creation and get execution in getting started

- rsts/community/contribute.rst
- rsts/concepts/architecture.rst
- rsts/index.rst
- rsts/reference/index.rst
Update the API Reference section to contain both API and Component reference sections
> update API Reference -> References

- rsts/concepts/tasks.rst
Fixes for some minor typos, punctuation, wording problems.
> Update tasks.rst with minor text fixes

- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
- helm/templates/admin/deployment.yaml
[Related PR](https://github.com/flyteorg/flyte/pull/1087)
> Set correct secret name when `flyteadmin create secrets` runs

- rsts/getting_started_iterate.rst
- rsts/getting_started_scale.rst
https://flyte--1201.org.readthedocs.build/en/1201/getting_started.html
> Updated the create execution command post fast register

- helm/values-eks.yaml
- rsts/deployment/aws/manual.rst
Signed-off-by: wild-endeavor <wild-endeavor@users.noreply.github.com>
> [nit] Tweak db username in manual AWS setup

- rsts/deployment/aws/manual.rst
> Using <REGION> template variable instead of us-east-2 in the examples

- rsts/conf.py
- rsts/deployment/aws/manual.rst
Signed-off-by: wild-endeavor <wild-endeavor@users.noreply.github.com>
Address feedback.
> More AWS manual setup feedback

- CHANGELOG/CHANGELOG-v0.15.0.md
- end2end/tests/endtoend.yaml
- rsts/conf.py
> Milestone 0.15.0 release

- README.md
> Add Flyte Helm Chart Badge

- rsts/deployment/cluster_config/auth_setup.rst
> Fix flytectl auth config documentation

- rsts/index.rst
First example needs to use keyword args
> Update first example

- README.md
- deployment/jpm/flyte_helm_generated.yaml
- helm/templates/namespaces.yaml
- helm/templates/propeller/rbac.yaml
- helm/values-jpm.yaml
Signed-off-by: wild-endeavor <wild-endeavor@users.noreply.github.com>
> [pr into mimimal-perms] Removing propeller cluster role

- rsts/deployment/cluster_config/auth_migration.rst
- rsts/deployment/cluster_config/index.rst
- rsts/deployment/index.rst
> hide "coming soon", update auth migration guide

- end2end/tests/endtoend.yaml
> Update flytetester to latest flytekit v0.21.0

- rsts/getting_started.rst
> --upgrade in pip install flytekit command

- .github/workflows/sync-issues-sheet.yml
> Add github issues sync WF

- rsts/concepts/catalog.rst
Signed-off-by: Bruce Arctor <5032356+brucearctor@users.noreply.github.com>
Closes #1261
> [Docs] update ref from lyft to flyteorg [Closes #1261]

- rsts/concepts/tasks.rst
- script/release.sh
> Fix values file paths in release_automation target

- charts/flyte/templates/minio/service.yaml
- charts/flyte/values-gcp.yaml
- charts/flyte/values-sandbox.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
- Added minio  nodeport to 30084 in helm chart
> Added minio  nodeport to 30084 in helm chart

- rfc/README.md
inserting ` to fix pop-up menu values
> Fix formatting in rfc/README.md

- rfc/README.md
> Fix typo in RFC process

- CHANGELOG/CHANGELOG-v0.17.3b1.md
> Changelog file for v0.17.3b1

- CHANGELOG/CHANGELOG-v0.17.3-b1.md
> Re-release v0.17.3 beta 1 with dash

- rsts/deployment/cluster_config/auth_setup.rst
Updating auth_setup.rst instructions based on my experience as a new Flyte user adding Authentication using Google SSO to a GKE cluster
> Updating auth_setup.rst Instructions

- CHANGELOG/CHANGELOG-v0.17.3-b2.md
- charts/flyte-core/README.md
- charts/flyte-core/values.yaml
- charts/flyte/README.md
- charts/flyte/values.yaml
> Change volumes and volume mounts to list

- README.md
> Adding Union.ai as a contributor and prod user

- README.md
> Fixing the URL for Level-5

- README.md
It's official, we have Flyte deployment at Gojek now 🥳
> Add Gojek to the list of deployments & contributors

- README.md
Adding OSPOCon, KubeCon, PyData and ODSC conference talks (video or session links) plus ODSC podcast.
> Updating Conference talks

- rsts/deployment/plugin_setup/index.rst
- rsts/deployment/plugin_setup/mpi_operator.rst
- rsts/deployment/plugin_setup/pytorch_operator.rst
- rsts/deployment/plugin_setup/spark_operator.rst
Added docs for spark 
Fix: https://github.com/flyteorg/flyte/issues/820
> Added spark plugin docs

- rsts/concepts/admin.rst
- rsts/deployment/index.rst
- rsts/deployment/plugin_setup/aws/batch.rst
- rsts/deployment/plugin_setup/aws/index.rst
- rsts/deployment/plugin_setup/index.rst
fixes: https://github.com/flyteorg/flyte/pull/1779
> AWS Batch Plugin Setup Docs

- rsts/deployment/plugin_setup/k8s/index.rst
- rsts/deployment/plugin_setup/k8s/tensorflow_operator.rst
- Added tensorflow plugin docs 
fix: https://github.com/flyteorg/flyte/issues/1785
> Added tensorflow plugin docs 

- charts/flyte/README.md
- charts/flyte/templates/admin/deployment.yaml
- charts/flyte/templates/flytescheduler/deployment.yaml
- charts/flyte/values.yaml
- deployment/eks/flyte_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
- deployment/test/flyte_generated.yaml
- kustomize/base/admindeployment/deployment.yaml
- kustomize/base/schedulerdeployment/configmap.yaml
- kustomize/base/schedulerdeployment/deployment.yaml
- kustomize/base/schedulerdeployment/kustomization.yaml
- kustomize/base/single_cluster/headless/kustomization.yaml
* Adds kustomize support for scheduler
* Updated the images for flyteadmin and scheduler to latest master tagged images
* Added security fixes for admin from this PR https://github.com/flyteorg/flyte/pull/1798
* Fixed the auth issue with flytescheduler where secrets were not mounted (https://github.com/flyteorg/flyte/issues/1780)
Testing done:
* Deployed sandbox using helm and kustomize
* Registered workflows and launched them successfully
* Enabled auth and verified scheduler container comes up correctly
> Scheduler deployment kustomize support and authentication fix

- README.md
> Add test matrix to README.md

- .github/workflows/tests.yml
- Replace kind with flytectl sandbox 
- Run test against latest release
_How did you fix the bug, make the feature etc. Link to any design docs etc_
fix: flyteorg/flyte#1474
_NA_
OR
> Added flytectl sandbox for running end2end

- charts/flyte-core/templates/flytescheduler/deployment.yaml
- deployment/gcp/flyte_core_helm_generated.yaml
This has already been done in the flyte chart in #1810 but missing in `flyte-core`.
> Fix flytescheduler auth #1780 in flyte-core as well

- README.md
> Live roadmap

- rsts/index.rst
https://github.com/cncf/foundation/blob/master/style-guide.md#2-kubernetes
> docs: fix K8s abbreviation

- README.md
> Readme update: Repos & their status. RFC process

- docker/sandbox/flyte-entrypoint-default.sh
- docker/sandbox/flyte-entrypoint-dind.sh
Rename values file in sandbox entry point (This bug introduce because of helm changes Deprecate duplicate helm template #1759)
> fix sandbox values in entrypoint script

- rsts/deployment/aws/manual.rst
- rsts/deployment/gcp/index.rst
- Update helm registry in docs
- Added docs in eks deployment for flytescheduler and aws native scheduler
> Added helm changes in deployment docs

- rsts/deployment/aws/opta.rst
Content clean-up, fixed broken links.
Context: https://flyte-org.slack.com/archives/C02PN54V5FH/p1639375332006200 & https://flyte-org.slack.com/archives/C02PN54V5FH/p1639308124004500?thread_ts=1639294659.003500&cid=C02PN54V5FH
> Update Opta AWS doc

- charts/flyte-core/README.md
- charts/flyte-core/templates/admin/rbac.yaml
- charts/flyte-core/values.yaml
> [helm] Make FlyteAdmin's ClusterRole creation optional

- charts/flyte-core/values-eks.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- Disable redis resource manager in propeller
> disable redis resource manager in eks

- charts/flyte/README.md
- charts/flyte/README.md.gotmpl
- rsts/deployment/sandbox.rst
- script/generate_helm.sh
Add flytectl init instruction to the end of the sandbox deployment instructions to complete setup
> docs: update sandbox deployment docs

- rsts/deployment/sandbox.rst
- Added minio, postgres cred for sandbox in docs
Fix: https://github.com/flyteorg/flyte/issues/1264
> Added minio, postgres cred in sandbox deployment

- README.md
Adding Office Hours and making some editorial checks.
> Adding Office Hours

- rsts/concepts/architecture.rst
- rsts/concepts/component_architecture/flytepropeller_architecture.rst
Added a toctree and set of buttons to the "Component Architecture" section to dive into each individual component architecture beginning with FlytePropeller's architecture.
> Added FlytePropeller architecture document

- rsts/getting_started.rst
Fix https://github.com/flyteorg/flyte/issues/1835
Before:
1. 
2.
After:
> Show expected outputs by default

- rsts/concepts/tasks.rst
- rsts/concepts/workflows_nodes.rst
How does a workflow work in the presence of independent data? Context: https://flyte-org.slack.com/archives/CNMKCU6FR/p1639103639461200
> Update workflow doc

- rsts/deployment/plugin_setup/aws/index.rst
- rsts/deployment/plugin_setup/aws/sagemaker.rst
Add docs for Sagemaker plugin setup
> Sagemaker plugin setup

- rsts/deployment/cluster_config/eventing.rst
- rsts/deployment/cluster_config/index.rst
https://github.com/flyteorg/flyte/issues/1951
> [Docs] External eventing

- rsts/concepts/architecture.rst
- rsts/concepts/component_architecture/native_scheduler_architecture.rst
https://github.com/flyteorg/flyte/issues/1584
> Added native scheduler documentation

- rsts/concepts/architecture.rst
> Panels were incorrectly aligned

- kustomize/base/operators/kfoperators/pytorch/kustomization.yaml
- rsts/deployment/aws/manual.rst
- rsts/deployment/gcp/manual.rst
- Added project & domain config docs
- Fixed kustmoize build, Currently it's failing because branch doesn't exist
fix: https://github.com/flyteorg/flyte/issues/1583
> Added project & domain config docs

- rsts/community/troubleshoot.rst
More details on this slack thread https://flyte-org.slack.com/archives/C02721ZK6MV/p1640116371261200
> Added troubleshooting section for proxy environment

- rsts/concepts/versioning.rst
fixes: https://github.com/flyteorg/flyte/issues/1918
[Rendered Docs](https://flyte--2003.org.readthedocs.build/en/2003/concepts/versioning.html#divedeep-versioning)
> Versioning docs, adding operational benefits

- rsts/deployment/gcp/manual.rst
Adding syntax edits. The content has not been changed.
> Editorial Review

- README.md
This is how the table is going to look like:
> Add 0.18.2 results to functional tests matrix

- rsts/deployment/plugin_setup/gcp/bigquery.rst
> Update BigQuery plugin docs

- rsts/concepts/basics.rst
- rsts/concepts/flyte_console.rst
- rsts/conf.py
- rsts/deployment/sandbox.rst
- rsts/deployment/security/security.rst
- rsts/getting_started/build.rst
- rsts/getting_started/deploy.rst
- rsts/getting_started/index.rst
- rsts/getting_started/iterate.rst
- rsts/index.rst
This PR should be merged with the following other PRs in order to update the theme to use the navbar header:
- https://github.com/flyteorg/furo/pull/10 << MERGE THIS FIRST
- https://github.com/flyteorg/flyte/pull/2037
- https://github.com/flyteorg/flytesnacks/pull/578
- https://github.com/flyteorg/flytekit/pull/806
- https://github.com/flyteorg/flyteidl/pull/247
- https://github.com/flyteorg/flytectl/pull/259
> docs/2028: update flyte docs for new navbar

- rsts/community/troubleshoot.rst
> Adding flytectl troubleshooting from recent issue

- rsts/deployment/cluster_config/auth_setup.rst
> Updated auth setup to include restarting flytepropeller aswell

- rsts/concepts/admin.rst
> Fix link to matchable resources documentation

- rsts/deployment/overview.rst
> Modified the pub sub integration section on the deployment overview page

- rsts/concepts/admin.rst
> Explain what task resource defaults and limits in flyteadmin are used for

- README.md
> Expand functional test matrix by default

- CHANGELOG/CHANGELOG-v0.19.2-b3.md
Missed in https://github.com/flyteorg/flyte/pull/2098
> Add changelog for 0.19.2-b3 release

- rsts/conf.py
> Update copyright year to 2022

- rsts/deployment/sandbox.rst
> Fixed k3d docs

- end2end/tests/endtoend.yaml
> Run functional tests with env var set

- rsts/deployment/sandbox.rst
> fix: fix typo

- rsts/community/contribute.rst
Replaced Flyteconsole broken link L231, replaced join Slack link L305 and removed the last comment.
> Editorial Check - Contributing

- CHANGELOG/CHANGELOG-v0.19.3-b1.md
> ChangeLog for 0.19.3-b1

- README.md
Update the logo in Readme from incubation logo to graduate logo.
> Update to graduate logo from static-resources repository

- charts/flyte-core/templates/admin/configmap.yaml
- charts/flyte-core/templates/clusterresourcesync/configmap.yaml
- deployment/gcp/flyte_helm_generated.yaml
> Propagate namespace mapping to flyteadmin and clusterresourcesync

- rsts/community/troubleshoot.rst
Adding syntax and grammar fixes. 
Capitalizing Titles. 
Changing FlyteCTL to Flytectl for consistency. 
Replacing the Slack URL with the latest link.
> Editorial Review - Troubleshooting

- rsts/concepts/nodes.rst
Changed 'child' workflow to 'external' workflow
> Updated nodes.rst

- rsts/concepts/versioning.rst
- rsts/concepts/workflows.rst
Fixed registration directive rendering
> Updated workflows rst file to render a directive correctly

- docker/sandbox/wait-for-flyte.sh
Added env variable for customizing the timeout of sandbox wait script
Fix: https://github.com/flyteorg/flyte/issues/2197
> Env variable added for sandbox wait timeout

- rsts/concepts/catalog.rst
> fix catalogue page

- deployment/eks/flyte_helm_controlplane_generated.yaml
- deployment/eks/flyte_helm_dataplane_generated.yaml
- deployment/gcp/flyte_helm_controlplane_generated.yaml
- deployment/gcp/flyte_helm_dataplane_generated.yaml
- rsts/deployment/cluster_config/general.rst
- rsts/deployment/ideal_flow.rst
> Add copy/pastable examples and update matchable attributes admin docs

- deployment/eks/flyte_generated.yaml
- deployment/gcp/flyte_generated.yaml
- deployment/sandbox/flyte_generated.yaml
- deployment/test/flyte_generated.yaml
- kustomize/base/adminserviceaccount/adminserviceaccount.yaml
- kustomize/base/operators/spark/scheduledsparkapplications-crd.yaml
- kustomize/base/operators/spark/spark-operator.yaml
- kustomize/base/operators/spark/sparkapplications-crd.yaml
- kustomize/base/propeller/rbac.yaml
- kustomize/base/wf_crd/wf_crd.yaml
- kustomize/overlays/eks/flyte/config/clusterresource-templates/ad_spark-role.yaml
- kustomize/overlays/eks/flyte/config/clusterresource-templates/af_spark-role-binding.yaml
- kustomize/overlays/gcp/flyte/config/clusterresource-templates/ad_spark-role.yaml
- kustomize/overlays/gcp/flyte/config/clusterresource-templates/af_spark-role-binding.yaml
- kustomize/overlays/sandbox/flyte/config/clusterresource-templates/ad_spark-role.yaml
- kustomize/overlays/sandbox/flyte/config/clusterresource-templates/af_spark-role-binding.yaml
Signed-off-by: Jeev B <jeevb@users.noreply.github.com>
> Update api versions in Kustomize module

- rsts/deployment/cluster_config/auth_setup.rst
> Added keycloak OpenIdConnect/OAuth2.0 Server integration docs for flyte

- README.md
Signed-off-by: Alekhya Sai Punnamaraju <alekhyasaip@gmail.com>
Fix to a GIF in Readme which isn't showing up.
> Fix to the GIF in Readme.

- rsts/deployment/aws/opta.rst
Docs cleanup for PR https://github.com/flyteorg/flyte/pull/2161
Fix: https://github.com/flyteorg/flyte/issues/2116
> removed aws ses & sqs setup from aws opta docs

- rsts/concepts/admin.rst
- rsts/deployment/ideal_flow.rst
Grammar fix
Fixed directive fast registration link
> Fixed errors

- rsts/deployment/sandbox.rst
The Postgres credentials code box at the end wasn't displayed correctly.
> Updated sandbox.rst

- charts/flyte-core/values-gcp.yaml
- deployment/gcp/flyte_helm_dataplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- rsts/deployment/plugin_setup/k8s/index.rst
- script/generate_helm.sh
- Remove spark from GCP by default
- Fix spark docs (https://flyte--2314.org.readthedocs.build/en/2314/deployment/plugin_setup/k8s/index.html#deployment-plugin-setup-k8s)
> Removed spark from GCP helm values

- rsts/deployment/plugin_setup/k8s/index.rst
- Typo Fix in cluster resource
- Updated the helm package for spark operator
> typo fix in spark docs

- charts/flyte-core/templates/_helpers.tpl
- charts/flyte-core/templates/common/ingress.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_controlplane_generated.yaml
- deployment/eks/flyte_helm_dataplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_controlplane_generated.yaml
- deployment/gcp/flyte_helm_dataplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
fixes https://github.com/flyteorg/flyte/issues/2263
> Make signedUrls work with sandbox

- rsts/deployment/cluster_config/auth_setup.rst
[Rendered](https://flyte--2308.org.readthedocs.build/en/2308/deployment/cluster_config/auth_setup.html)
> Add instructions to restart flytescheduler after enabling auth

- opta/aws/flyte.yaml
fix: https://github.com/flyteorg/flyte/issues/2116
> Removed sqs helm values from aws opta

- cmd/single/config.go
- cmd/single/start.go
- flyte_local.yaml
- go.mod
- go.sum
https://github.com/flyteorg/flyte/issues/2266
> Fixing single binary

- .github/workflows/generate_flyte_manifest.yml
- script/generate_config_docs.sh
> Don't clone repos in root dir when generating config docs

- go.mod
- go.sum
> upgraded github.com/flyteorg/flyteadmin v0.6.145 => v0.6.146

- rsts/getting_started/index.rst
> Restructure getting started

- rsts/community/index.rst
Reshuffled top buttons, and added buttons for Newsletter and Wednesday office hours.
> Editorial Review - Community

- rsts/deployment/security/security.rst
Fixes: https://github.com/flyteorg/flyte/issues/2371
> Add certificate requirements for OAuth to work

- rsts/concepts/launchplans.rst
Removed period in between a sentence.
> Updated launchplans.rst

- README.md
- rsts/getting_started/index.rst
Signed-off-by: Alekhya Sai Punnamaraju <alekhyasaip@gmail.com>
Fixes : https://github.com/flyteorg/flyte/issues/1507
> GIF path updates

- rsts/getting_started/index.rst
Signed-off-by: Alekhya Sai Punnamaraju <alekhyasaip@gmail.com>
> Getting started GIF fix

- rsts/deployment/plugin_setup/k8s/index.rst
> spark configuration to run examples on sandbox

- rsts/deployment/plugin_setup/k8s/index.rst
> update k8s plugin setup instructions

- .github/workflows/create_release.yml
Fixes https://github.com/flyteorg/flyte/issues/2432
> add repository dispatch gh action

- script/generate_config_docs.sh
> Use flytescheduler binary from released artifacts

- rsts/deployment/security/security.rst
> Added instruction for cross origin requests

- rsts/deployment/gcp/manual.rst
https://github.com/flyteorg/flyte/issues/2263
> Added signed url perms for GCP

- rsts/deployment/ideal_flow.rst
Signed-off-by: Alekhya Sai Punnamaraju <alekhyasaip@gmail.com>
Fixes: https://github.com/flyteorg/flyte/issues/2415
> Adding a note on workflow promotion

- README.md
Add the new mid-day office hours to the Community & Resources section.
> Add Mid-day Office Hours

- rsts/deployment/aws/opta.rst
wrt https://flyte-org.slack.com/archives/CNMKCU6FR/p1653043128094849?thread_ts=1652895063.733789&cid=CNMKCU6FR
> Updated Opta.rst

- rsts/deployment/aws/index.rst
- rsts/deployment/cluster_config/auth_appendix.rst
- rsts/deployment/cluster_config/auth_setup.rst
- rsts/deployment/cluster_config/general.rst
- rsts/deployment/cluster_config/index.rst
- rsts/deployment/cluster_config/performance.rst
- rsts/deployment/gcp/index.rst
- rsts/deployment/ideal_flow.rst
- rsts/deployment/index.rst
- rsts/deployment/plugin_setup/aws/index.rst
- rsts/deployment/plugin_setup/gcp/index.rst
- rsts/deployment/plugin_setup/index.rst
- rsts/deployment/plugin_setup/webapi/index.rst
- rsts/deployment/sandbox.rst
- fix deployment guide menu card formatting
- fix TOC structure, titles, and menu cards.
> fix deployment guides structure

- CHANGELOG/CHANGELOG-v1.0.2-b2.md
Signed-off-by: Yuvraj <evalsocket@users.noreply.github.com>
> ChangeLog for v1.0.2-b2

- README.md
> Update slack archive URL

- rsts/community/contribute.rst
- rsts/concepts/basics.rst
- rsts/concepts/lifecycle_workflow_with_plugin.rst
- rsts/concepts/workflow_lifecycle.rst
Signed-off-by: David Przybilla <dav.alejandro@gmail.com>
Explaining Flyte plugin machinery for upcoming contributors
Documenting little bits that I've learnt through the office sessions and tiny contributions. 
I did not know what was the best place to link. Also Suggestions for a better title are welcome!
---
> Docs: Explaining plugin machinery for contributors

- rsts/concepts/architecture.rst
Signed-off-by: Vijay Saravana <jvs123456@gmail.com>
> Spelling error - correction

- CHANGELOG/CHANGELOG-v1.1.0.md
> Add 1.1.0 changelog

- charts/flyte-core/templates/clusterresourcesync/deployment.yaml
Signed-off-by: Sean Lin <sean@union.ai>
> Fix indentation in flyte-core Helm chart

- rsts/deployment/cluster_config/general.rst
> Added docs for workflow exeuction config

- rsts/community/troubleshoot.rst
- rsts/deployment/sandbox.rst
Fixes https://github.com/flyteorg/flyte/issues/1582
> Pod name info

- rfc/README.md
- rfc/system/2704-release-cycle-process-updates.md
- rsts/community/roadmap.rst
> Revise Roadmap and add RFC for updating planning & release process

- charts/flyte-core/values-keycloak-idp-flyteclients-without-browser.yaml
Signed-off by: Sujith Samuel samuel_sujith@yahoo.co.in
> Helm values changes for on prem with keycloak IDP and TLS ingress

- charts/flyte-core/templates/propeller/manager.yaml
Signed-off-by: Daniel Rammer <daniel@union.ai>
> Update termination policy in propeller manager

- README.md
Signed-off-by: Bernhard Stadlbauer <11799671+bstadlbauer@users.noreply.github.com>
> Add Pachama to current deployments

- README.md
Signed-off-by: Matheus Moreno <matheus.moreno@hurb.com>
> Add Hurb to current deployments

- README.md
Signed-off-by: Gigi Jackson [gjackson@zymergen.com](mailto:gjackson@zymergen.com)
> Add Zymergen to current deployments

- README.md
Signed-off-by: Robin Kahlow <robin@ntropy.network>
> Add ntropy to current deployments

- README.md
> adds porch to deployments.

- rsts/deployment/plugin_setup/k8s/index.rst
- Install ray operator
- Enable the Ray plugin
- Register a Ray example
https://github.com/flyteorg/flyte/issues/2641
https://flyte--2805.org.readthedocs.build/en/2805/deployment/plugin_setup/k8s/index.html#deployment-plugin-setup-k8s
> Ray plugin setup docs 

- rsts/deployment/aws/manual.rst
Signed-off-by: Steven Kalt <SKalt@users.noreply.github.com>
> fix typo in docs on aws manual deployment

- README.md
Signed-off-by: Rahul Mehta <98349643+rahul-theorem@users.noreply.github.com>
> Add Theorem to current deployments/contributors

- rsts/deployment/sandbox.rst
fix: https://github.com/flyteorg/flyte/issues/2918
> doc updated for flyte sandbox on kubernetes

- CHANGELOG/CHANGELOG-v1.2.0-b5.md
- charts/flyte-core/templates/admin/configmap.yaml
- charts/flyte-core/values-eks.yaml
- deployment/eks/flyte_aws_scheduler_helm_generated.yaml
- deployment/eks/flyte_helm_controlplane_generated.yaml
- deployment/eks/flyte_helm_generated.yaml
- deployment/gcp/flyte_helm_controlplane_generated.yaml
- deployment/gcp/flyte_helm_generated.yaml
- deployment/sandbox/flyte_helm_generated.yaml
- go.mod
- rsts/conf.py
> Update notifications.yaml to text in admin helm template

- rsts/conf.py
> Set release to 1.2.0

- rsts/getting_started/index.rst
> Secure Install Flytectl

- .github/PULL_REQUEST_TEMPLATE.md
Signed-off-by: Krishna Agarwal <dmkrishna.agarwal@gmail.com>
cc @samhita-alla
> feat: Added PULL REQUEST TEMPLATE 🛠

- rsts/deployment/plugin_setup/k8s/index.rst
> Fix k8s deployment instruction

- rsts/concepts/launchplans.rst
> modified launchplans.rst

- rsts/deployment/cluster_config/auth_appendix.rst
Fixes https://github.com/flyteorg/flyte/issues/2804
Mermaid diagrams under sphinx tabs aren't getting rendered properly. Created sub-sections to fix the issue.
> Fix mermaid diagrams

- rsts/concepts/launchplans.rst
Signed-off-by: Utsav Paul <91927689+Smartmind12@users.noreply.github.com>
Closes #2992
> Removing Stale link to launch plans

- charts/flyte-sandbox/README.md
- charts/flyte-sandbox/values.yaml
- docker/sandbox-bundled/manifests/compiled.yaml
Partially addresses: https://github.com/flyteorg/flyte/issues/3080
> Increase log level in flyte-sandbox-bundled from 1 -> 6

- rfc/system/0000-runtime-workflow-control-using-signalling.md
https://hackmd.io/54Pgw1ZRStKYV3LyxELYCQ?view
https://github.com/flyteorg/flyte/issues/208
> RFC - Runtime Workflow Control Using Signals and GateNodes

- rsts/getting_started/index.rst
Partially addresses https://github.com/flyteorg/flyte/issues/3177
Updates getting started guide, removes need to export KUBECONFIG env var.
> fix getting started instructions

- CHANGELOG/CHANGELOG-v1.3.0-b7.md
- rsts/conf.py
> 1.3 b7 change logs

- .github/workflows/create_release.yml
Tested with the local registry.
Original image:
```
> docker manifest inspect --verbose --insecure "localhost:5000/test"
[
{
"Ref": "localhost:5000/test:latest@sha256:ce2f1f75ed6e781c6e44be8bafaa29b8fd7563a739c21206a7fa38c6893ce07f",
"Descriptor": {
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"digest": "sha256:ce2f1f75ed6e781c6e44be8bafaa29b8fd7563a739c21206a7fa38c6893ce07f",
"size": 528,
"platform": {
"architecture": "amd64",
"os": "linux"
}
},
"SchemaV2Manifest": {
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"schemaVersion": 2,
"config": {
"mediaType": "application/vnd.docker.container.image.v1+json",
"digest": "sha256:3da83a1633c5409e0d7cbc9d3442bf07beab6d6392da0a1a03a638d61518ae53",
"size": 882
},
"layers": [
{
"mediaType": …
```
> Support for multiarch images when retagging as release images

- CHANGELOG/CHANGELOG-v1.3.0-b8.md
- rsts/conf.py
> Changelog for 1.3.0-b8

- rsts/getting_started/index.rst
> Add note that flytekit supports python 3.7 - 3.10

- CHANGELOG/CHANGELOG-v1.3.0.md
Just the changelog, no code changes.
> Changelog for 1.3

- rsts/concepts/component_architecture/flytepropeller_architecture.rst
Clarify the idea of CRD and CR
> Clarify CRD and CR in the documentation

- .github/workflows/single-binary.yml
- Makefile
Add a local target for testing.
> Add make target for local use

- charts/flyte-sandbox/templates/proxy/configmap.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
Fixes a bug in sandbox-bundled minio console where bucket contents fail to load.
> Update envoy configuration to support minio console websockets

- charts/flyte-core/templates/admin/configmap.yaml
Signed-off-by: pmahindrakar-oss <prafulla.mahindrakar@gmail.com>
fixes https://github.com/flyteorg/flyte/issues/3296
Tested it and it generates the right region config with indentation
[x] - Correct; marked as done
[X] - Correct; marked as done
[ ] - Not correct; marked as **not** done
> Fixed notification region config

- .github/workflows/generate_flyte_manifest.yml
- .github/workflows/tests.yml
- go.mod
Bumping the go version to 1.19 to fix pull request checks.
^^^
_NA_
_NA_
> Bumping go version to 1.19

- charts/flyte-binary/values.yaml
> docs: fix spelling mistake

- rsts/reference/swagger.rst
Update the link to swapper openapi docs due to changes in Flyte sandbox
- ~~[ ] All new and existing tests passed.~~
> update swagger link in flyte demo

- .github/workflows/generate_flyte_manifest.yml
We should use an existing team in the github action we use to open the "Update Flyte Components" PR, otherwise we now see errors like https://github.com/flyteorg/flyte/actions/runs/4318515846/jobs/7536896252, even though the PR ends up [being opened](https://github.com/flyteorg/flyte/pull/3388).
> Use correct team in create-pull-request

- README.md
Closes #3377 
* Added a Quickstart section
* Reordered and expanded Contributing-related information
* Updated communication channels
* Takes inspiration from [awesome-readme](https://github.com/matiassingers/awesome-readme)
> README: Fix broken links and reorder sections

- flyte-single-binary-local.yaml
The local demo environment writes to the sandbox directory.
> Update example local dev config file

- rsts/concepts/architecture.rst
Adds visual element to accompany description of Flyte components and interactions
> Add logical architecture diagram

- rsts/deployment/configuration/general.rst
This PR replaces TB with Ti in the cluster resources config.
> fix typo in cluster resources doc

- rsts/community/index.rst
Updates Community Meeting link and adds instructions to book Office Hours
> Update community page

- rsts/deployment/plugins/k8s/index.rst
> Adjust MPI operator installation doc

- charts/flyte-binary/eks-production.yaml
Adding example configuration to avoid this error https://github.com/flyteorg/flyte/issues/3789.
> Add EKS example for rolekeyname

- rsts/deployment/plugins/k8s/index.rst
MPI operator is actually not needed. Training operator can run MPI tasks as well.
> Fix mpi/training operator installation doc

- README.md
- rsts/concepts/tasks.rst
> Fix broken links

- rsts/deployment/plugins/k8s/index.rst
In this PR, I add some docs how to install Apache YuniKorn and enable the Gang-scheduling feature.
Provide the other option beside Kubernetes scheduler plugin.
related PR: https://github.com/flyteorg/flyte/pull/3851
> Doc: Apache YuniKorn gang-scheduling for kubeflow training-operator

- boilerplate/flyte/end2end/run-tests.py
> [v1.8.1 Patch] CI stuff

- rsts/community/index.rst
Fixes link for community meeting calendar
> Fix community meeting calendar

- charts/flyte-binary/eks-starter.yaml
> Fix indentation in eks-starter.yaml

- .github/workflows/single-binary.yml
- boilerplate/flyte/end2end/run-tests.py
- rsts/concepts/schedules.rst
- rsts/concepts/tasks.rst
- rsts/deployment/configuration/notifications.rst
> Update the github action workflow in single-binary.yaml

- .github/workflows/helm-charts.yaml
FIxed https://github.com/flyteorg/flyte/actions/runs/6123388735/job/16621177522
> Update publish-development-helm-chart workflow

- .github/workflows/helm-charts.yaml
> Run helm push from the right dir

- .github/workflows/helm-charts.yaml
Update `Package & Push Flyte Helm Charts` workflow. only login to the GitHub registry on push.
> Login to GitHub registry on push

- rsts/community/contribute.rst
> Embed Contribution Guide Video into Documentation

- charts/flyteagent/README.md
- charts/flyteagent/values.yaml
- deployment/agent/flyte_agent_helm_generated.yaml
- script/release.sh
`release.sh` should update flyte agent's version as well.
> Update release script

- .github/workflows/codespell.yml
NA
Update codespell workflow
Ref: https://github.com/codespell-project/actions-codespell
Fixed
> Skip spell check on .pb files

- rsts/community/contribute.rst
Close #3938 
Change the development guide to be compatible with Mac
This change is based on the discussion in https://github.com/flyteorg/flyte/issues/3938
> fix the compatibility to Mac

- rfc/README.md
I've made improvements to the RFC Process section in the README, including restructuring and adding a table of contents for better readability. Additionally, I've made some minor grammar and formatting adjustments for clarity.
Fixes #4286 
N/A
No specific notes for reviewers.
> [fix] #4286 RFC Process Improvement and Documentation Update

- go.mod
Let's decrease the confusion with the monorepo versioning by also using the local version in single-binary's go.mod file.
> Use local version in single-binary

- README.md
-->
NA
Add accessibility features based on: https://github.blog/2023-10-26-5-tips-for-making-your-github-profile-page-accessible/
NA
Accessibility is important!
> Accessibility for README

- .github/workflows/stale.yml
Small change to the stalebot config to exclude issues labeled "untriaged".
N/A
> Chore: Ensure Stalebot doesn't close issues we've not yet triaged.

- .github/workflows/single-binary.yml
Accommodate list of tests modified in https://github.com/flyteorg/flytesnacks/pull/1214
> Update tests in single-binary

- .github/PULL_REQUEST_TEMPLATE.md
https://github.com/flyteorg/flyte/issues/4366
This change will improve the PR quality significantly.
> Add Sections in the PR Template

- boilerplate/flyte/end2end/run-tests.py
_NA_
_NA_
Updating the end2end tests to include new structure. https://github.com/flyteorg/boilerplate/pull/93.
_NA_
_NA_
_NA_
_NA_
> Update boilerplate end2end tests

- rsts/deployment/deployment/sandbox.rst
Moves the sandbox config section from the "Registration patterns" section to Deployment
> Relocate sandbox config

- flyteartifacts/pkg/db/gorm_models.go
- flyteartifacts/pkg/db/migrations.go
> Make trigger key index unique

- flyteadmin/pkg/manager/impl/task_execution_manager.go
- flyteartifacts/pkg/db/storage.go
pr into 4077 - the condition for trigger querying wasn't correct.
> artf/ fix issue with trigger

- datacatalog/pkg/repositories/errors/postgres.go
- flyteadmin/pkg/async/cloudevent/implementations/cloudevent_publisher.go
- flytestdlib/database/postgres.go
> More pgconn handling fixes

- datacatalog/pkg/repositories/handle.go
- datacatalog/pkg/repositories/initialize.go
- flyteadmin/pkg/repositories/errors/postgres.go
- flyteadmin/pkg/repositories/errors/postgres_test.go
- flytestdlib/database/postgres.go
- flytestdlib/database/postgres_test.go
pr into 4077
Add additional handling of pgconn
* Change datacatalog logic to use flytestdlib function instead.
* Change flytestdlib constants to capitalize
* Add handling of the other type to Admin code directly
> artf/ add additional handling where pgconn is cast

- .github/workflows/flyteidl-buf-publish.yml
> Add Buf publish on push to artifacts branch 

- .github/workflows/flyteidl-buf-publish.yml
> Add artifacts branch to publish to buf on push

- flyteidl/protos/flyteidl/artifact/artifacts.proto
Needed to add this in the idl path
> add dummy comment again

- .github/workflows/create_release.yml
Fixing leftover of https://github.com/flyteorg/flyte/pull/4496/. Indentation of `shell` stanza is wrong, being fixed in this PR.
> Fix indentation of `shell: task`

- README.md
Moving community meeting to once per month
> Update community meeting cadence

- monodocs-environment.lock.yaml
- monodocs-environment.yaml
This PR updates the monodocs conda lock file so that docs correctly build locally.
> update conda lock file

- docs/README.md
> Add docs build process readme

- docker/sandbox-bundled/manifests/complete-agent.yaml
- docker/sandbox-bundled/manifests/complete.yaml
- docker/sandbox-bundled/manifests/dev.yaml
NA
https://github.com/flyteorg/flyte/pull/4869 didn't commit the generated files.
> Commit generated files produced by `make -C docker/sandbox-bundled build`

- CHANGELOG/CHANGELOG-v0.11.0.md
- CHANGELOG/CHANGELOG-v0.14.0.md
- CHANGELOG/CHANGELOG-v0.17.0.md
- CHANGELOG/CHANGELOG-v0.5.0.md
- CHANGELOG/CHANGELOG-v0.9.0.md
- CHANGELOG/CHANGELOG-v1.1.0.md
- CHANGELOG/CHANGELOG-v1.2.0.md
- CHANGELOG/CHANGELOG-v1.3.0.md
- CHANGELOG/CHANGELOG-v1.5.0.md
- docs/community/roadmap.rst
- rfc/system/1476-task-resources.md
- rfc/system/1893-caching-of-offloaded-objects.md
- rfc/system/2633-eviction-of-cached-task-outputs.md
> Update broken links

- flyteidl/clients/go/assets/admin.swagger.json
- flyteidl/gen/pb_rust/flyteidl.core.rs
- flyteidl/gen/pb_rust/flyteidl.event.rs
Run `make generate` again to fix the CI error . https://github.com/flyteorg/flyte/actions/runs/7933731012/job/21663180169
> make generate idl

- flyte-single-binary-local.yaml
None
When running using `pyflyte run`, the tasks are killed due to out of memory.
Increase the default memory and CPU in `flyte-single-binary-local.yaml`
> Increase default memory and CPU resource

- docs/community/troubleshoot.rst
Resolves: flyteorg/flyte#4826
When executing spark test, if the spark plugin enabled in the config file, then it will show 'JavaPackage' object is not callable error. Which is difficult to know from this error message.
Add it to the troubleshooting guide.
> docs(troubleshooting): Add spark task execution troubleshooting

- docs/community/troubleshoot.rst
- docs/deployment/deployment/multicluster.rst
N/A
There are redundant `$` characters in the following pages
https://docs.flyte.org/en/latest/deployment/deployment/multicluster.html#control-plane-deployment
https://docs.flyte.org/en/latest/community/troubleshoot.html
Remove the redundant `$` chracters.
> [Docs] Remove redundant dollar signs

- .github/workflows/tests.yml
Fix Monodocs build errors in CI
> Fix Monodocs build

- docs/flyte_agents/developing_agents.md
Adds links to documentation contributing guide and code to "Developing agents" doc to help contributors add their code and docs to the right places.
TBD
> Add links to "Developing agents" doc

- docs/deployment/deployment/cloud_simple.rst
Updates outdated link to flytesnacks repo.
TBD
> Update link to flytesnacks repo

- docs/user_guide/customizing_dependencies/imagespec.md
- Add instructions for overwriting an existing image using `FLYTE_FORCE_PUSH_IMAGE_SPEC=True` command
- Provide code examples for overwriting an existing image using `pyflyte run` and `ImageSpec.force_push()`
- Added `FORCE_PUSH` feature in ImageSpec file
https://github.com/flyteorg/flytekit/pull/2234
> docs: improve documentation for overwriting existing images

- docs/user_guide/productionizing/secrets.md
> [Docs] Remove kustomize link in secrets.md doc

- flyteplugins/go/tasks/plugins/k8s/ray/config_flags.go
- flyteplugins/go/tasks/plugins/k8s/ray/config_flags_test.go
NA
Ray config pflags were updated in https://github.com/flyteorg/flyte/pull/5134/, but that conflicted with https://github.com/flyteorg/flyte/pull/5067.
Just regenerate flyteplugins pflags.
> Regenerate ray pflags

- docs/user_guide/development_lifecycle/caching.md
Moved https://github.com/flyteorg/flytesnacks/pull/1425/ to the correct place.
> Explain how to enable/disable local caching

- docs/user_guide/environment_setup.md
https://github.com/flyteorg/flyte/issues/4708
> [Docs] add envd plugin installation command to the environment setup guide

- docs/user_guide/customizing_dependencies/raw_containers.md
https://github.com/flyteorg/flyte/issues/3876
we need to update both flyte and flytesnacks.
https://github.com/flyteorg/flytesnacks/pull/1654
> [easy] [Docs] Raw Container Local Execution

- docs/deployment/deployment/index.rst
- docs/quickstart_guide.md
This PR fixes slight visual issue with dropdowns:
Before:
After:
> fix dropdown formatting

- .github/workflows/tests.yml
- .readthedocs.yml
- docs/conf.py
- monodocs-environment.lock.yaml
- monodocs-environment.yaml
Testing `sphinx-reredirects` ci build
> test sphinx-reredirects

- flytepropeller/pkg/controller/nodes/executor.go
_NA_
missed in https://github.com/unionai/flyte/pull/229
Enabling parallelism application for ArrayNode from node executor.
Local testing.
_NA_
_NA_
> enabling parallelism controls on arraynode

- flyteplugins/go/tasks/pluginmachinery/flytek8s/copilot.go
NA
Log line is not printed correctly due to wrong types in format string.
Fix the order.
> Fix order of arguments in copilot log

- .github/workflows/flyteidl-release.yml
Flyte releases are not triggering flyteidl releases.
Use the `published` event as opposed to `created`.
Not yet. We're going to test this with a Flyte beta release.
> Use published in flyteidl-release gh workflow

- docs/_templates/page.html
Per request from @kumare3, adds tracking pixel to docs.
TK
> Add tracking pixel

- README.md
Adds tracking pixel to README per @kumare3 request.
> Add tracking pixel to README

- monodocs-environment.yaml
> update flytekit version to 1.12.1b2 in monodocs requirements

- docs/getting_started_with_workflow_development/running_a_workflow_locally.md
Similar to https://github.com/flyteorg/flyte/pull/5440, we need to clearly indicate that jq is needed to install flytectl now, but this time in https://docs.flyte.org/en/latest/getting_started_with_workflow_development/running_a_workflow_locally.html#install-flytectl
> Indicate that jq is needed to install flytectl

- .github/workflows/single-binary.yml
> Install image builder in CI

- docs/user_guide/customizing_dependencies/imagespec.md
> Remove ImageSpec experiment warning

- docs/deployment/plugins/k8s/index.rst
> Fix link to Kubeflow docs

- flytepropeller/pkg/controller/nodes/task/handler.go
- flytepropeller/pkg/controller/nodes/task/handler_test.go
While emitting `ABORTED` events for tasks, all the relevant information was not being emitted, leading to incomplete event details being emitted. 
We add the missing information, bringing it to parity with other task phases like `RUNNING`, `QUEUED`, etc.
This patch was tested on a local instance of flyte. It was validated from the logs that abort events had the relevant data available.
<code>{"json":{"src":"transformer.go:191"},"level":"debug","msg":"TaskExecutionEvent [task_id:\u003cresource_type:TASK project:"flyte-integration-test" domain:"development" name:"smoketests.flows.hello_world.say_hello" version:"2024-07-08-17-17-59" \u003e parent_node_execution_id:\u003cnode_id:"n0" execution_id:\u003cproject:"flyte-integration-test" domain:"development" name:"asmkhnnfqgpbm2ks9vgl" \u003e …
> Fully populate Abort task event fields

- flytepropeller/pkg/compiler/validators/typing.go
- flytepropeller/pkg/compiler/validators/typing_test.go
https://github.com/flyteorg/flyte/issues/5553
Likely similar issue to https://github.com/flyteorg/flyte/issues/2864
Repro idea: `pyflyte run --remote wf.py wf`
```py
import csv
from collections import defaultdict
from pathlib import Path
from typing import List, TypeVar, NamedTuple
import flytekit
from flytekit import task, workflow
from flytekit.types.file import FlyteFile
@task(cache=True, cache_version="3.0")
def t1() -> FlyteFile[TypeVar("csv")]:
columns_to_normalize = ["a", "b"]
out_path = Path(flytekit.current_context().working_directory) / f"normalized.csv"
with out_path.open(mode="w") as output_file:
writer = csv.DictWriter(output_file, fieldnames=columns_to_normalize)
writer.writeheader()
print(columns_to_normalize)
return FlyteFile(path=out_path)
@task(cache=True, …
```
> [fix] Add blob typechecker

- docs/user_guide/productionizing/configuring_access_to_gpus.md
I discovered this issue after merge
> Fix incorrect YAML for unpartitoned GPU

- docs/user_guide/productionizing/configuring_access_to_gpus.md
Me again, the fix introduced another problem. It should be the last
> Another YAML fix

- flytectl/cmd/demo/exec_test.go
- flytectl/cmd/demo/reload_test.go
- flytectl/cmd/demo/status_test.go
- flytectl/cmd/demo/teardown_test.go
- flytectl/cmd/sandbox/exec_test.go
- flytectl/cmd/sandbox/status_test.go
- flytectl/cmd/sandbox/teardown_test.go
- flytectl/go.mod
- flytectl/go.sum
- flytectl/pkg/docker/docker.go
- flytectl/pkg/docker/docker_util.go
- flytectl/pkg/docker/docker_util_test.go
- flytectl/pkg/docker/mocks/docker.go
- flytectl/pkg/sandbox/start_test.go
- flytectl/pkg/sandbox/status_test.go
- flytectl/pkg/sandbox/teardown.go
- flytectl/pkg/sandbox/teardown_test.go
See this advisory https://github.com/moby/moby/security/advisories/GHSA-v23v-6jw2-98fq
Affected version include
> <= v19.03.15, <= v20.10.27, <= v23.0.14, <= v24.0.9, <= v25.0.5, <= v26.0.2, <= v26.1.4, <= v27.0.3, <= v27.1.0
and flytectl is currently pinned to `v24.0.9`
This change upgrades to `v26.1.5` (https://github.com/moby/moby/releases/tag/v26.1.5) which is the minimally higher version with a patch
> Patched versions
> > v23.0.14, > v26.1.4, > v27.1.0
> Upgrade docker dependency to address vulnerability

- docs/deployment/agents/snowflake.rst
> [Doc] Fix snowflake agent secret documentation error

- flyteadmin/pkg/manager/impl/execution_manager.go
> Fix typo in execution manager

- docs/deployment/plugins/k8s/index.rst
closed https://github.com/flyteorg/flyte/issues/4491
document the process of setting ttl for a ray cluster
> [Docs] document the process of setting ttl for a ray cluster

- .github/workflows/single-binary.yml
Latest release of flytekit removed pyarrow as a dependency, but we need pyarrow to run functional tests.
> Install pyarrow in sandbox functional tests

- flytecopilot/cmd/sidecar_test.go
> Correct "sucessfile" to "successfile"

- flyteadmin/pkg/errors/errors.go
- flyteadmin/pkg/errors/errors_test.go
- flyteadmin/pkg/manager/impl/workflow_manager_test.go
NA
When users encounter this error, they do not know what to do
Improve error messaging for invalid arguments.
pyflyte register 
Before:
After:
NA
NA
> Improve error messaging for invalid arguments

- docs/quickstart_guide.md
TK
TK
https://flyte--5654.org.readthedocs.build/en/5654/quickstart_guide.html
> DOC-462 Update "Try Flyte in the browser" text

- flyte-single-binary-local.yaml
https://github.com/flyteorg/flyte/issues/5708
Tested by bringing up the demo environment using flytectl 
Building flytekit image and running a workflow and then making changes in flytekit for additional logging which when built and pushed to demo docker registry reflected when running a new workflow
> Configure imagePullPolicy to be Always pull on flyte sandbox environment

- docs/user_guide/development_lifecycle/decks.md
flyte deck: https://flyte--5781.org.readthedocs.build/en/5781/user_guide/development_lifecycle/decks.html
> [Docs] Flyte Deck example V2

- .github/workflows/single-binary.yml
> [Temporary fix] Pin flytekit version for single binary builds

- .github/workflows/dependency-review.yml
We can leverage an integrated github workflow to disallow certain software licenses.
Define a new gh workflow using https://github.com/actions/dependency-review-action?tab=readme-ov-file#configuration-options to disallow GPL dependencies.
> Add dependency review gh workflow

- flyteidl/README.md
N/A
Current link is broken.
Fix the link.
Link works in preview.
> Fix link in flyteidl README.md

- CODEOWNERS
> Update CODEOWNERS - remove nikki

- docs/deployment/deployment/cloud_simple.rst
> Minor fixes to single-cloud page

- README.md
Current link is broken.
Fix contribute link in README.
> [ Docs ] fix: contribute link 

- .github/workflows/single-binary.yml
Use latest flytectl in single-binary tests
> Unpin flytectl from single-binary tests

- README.md
Stops redirecting to Sandbox and moves to Serverless sign up 
> Update Serverless link

- docs/user_guide/data_types_and_io/index.md
> Update type mapping table to reflect 1.14 changes

- docs/user_guide/development_lifecycle/decks.md
https://flyte--6251.org.readthedocs.build/en/6251/user_guide/development_lifecycle/decks.html
https://github.com/flyteorg/flyte/issues/5574
> [Docs] Streaming Decks

- docs/user_guide/flyte_fundamentals/visualizing_task_input_and_output.md
https://flyte--6272.org.readthedocs.build/en/6272/user_guide/development_lifecycle/decks.html
https://github.com/flyteorg/flyte/issues/5574
> [Docs] Streaming Decks in flyte fundamentals

- flytectl/docs/source/contribute.rst
Change `./bin/flytectl sandbox start` to `./bin/flytectl demo start`
Documentation update for flytectl contribution guide, replacing the outdated cluster setup command './bin/flytectl sandbox start' with the new command './bin/flytectl demo start'. This change ensures accurate setup instructions for new contributors.
<br>
<br>
<br> …
> [DOCS] update contribution docs for flytectl

- flytestdlib/pbhash/pbhash.go
- flytestdlib/utils/marshal_utils.go
The logic of err not being nil has been processed and returned before, so err must be nil here.
This pull request fixes a bug in error handling by modifying return statements in pbhash module and marshal utilities. The changes ensure functions return nil for error values when no errors occur, leading to cleaner and more reliable error management.
<br>
<br>
<br>
<br>
</div>
> fix: return nil instead of error directly

- codecov.yml
NA
The overal numbers in https://app.codecov.io/gh/flyteorg/flyte are brought down by the proto stubs generated as part of flyteidl build process and also the mocks produced by `mockery`. Let's ignore those in codecov reports.
As defined in https://docs.codecov.com/docs/ignoring-paths, we can ignore a folder by using the patter `folder/**/*`. We use this pattern to ignore all generated code under `flyteidl/gen`.
This is important to improve the readability of release …
> Ignore generated code from codecov reports

- datacatalog/go.mod
- datacatalog/go.sum
- flyteadmin/go.mod
- flyteadmin/go.sum
- go.mod
- go.sum
Replaces #6200 
This PR updates the glog dependency from v1.2.0 to v1.2.4 across multiple modules to address security vulnerability CVE-2024-45339. The changes are implemented in go.mod and go.sum files for datacatalog, flyteadmin, and the root project, with necessary checksum entries added and obsolete entries removed to maintain integrity and properly …
> Update glog 1.2.0 -> 1.2.4 - CVE-2024-45339

- datacatalog/go.mod
- datacatalog/go.sum
- docker/sandbox-bundled/bootstrap/go.mod
- docker/sandbox-bundled/bootstrap/go.sum
- flyteidl/go.mod
- flyteidl/go.sum
- flytestdlib/go.mod
- flytestdlib/go.sum
Closes https://github.com/flyteorg/flyte/issues/6152
Fewer CVEs
This PR updates multiple dependency versions to address security vulnerabilities, including github.com/mattn/go-sqlite3 and golang.org/x packages in the docker sandbox bundle. The flyteidl module receives new dependencies with corresponding checksum updates, creating a consistent dependency graph …
> Bump golang.org/x/net and  github.com/mattn/go-sqlite3

- boilerplate/flyte/golang_test_targets/download_tooling.sh
When using goenv, the `bin` folder might not exist so the copy would create an executable called `bin` in that case.
Ensure `bin` folder is created first before copying.
I tested it manually.
This PR fixes a bug in download_tooling.sh by ensuring the Go binary directory exists before copying files. It improves command invocation with proper quoting, adds …
> fix: Ensure $(go env GOPATH)/bin exists

- docs/user_guide/productionizing/secrets.md
Closes #6286 
The current documentation is lacking on this topic.
Minimal documentation to enable and use AWS SM.
NA
- [ * ] I updated the documentation accordingly.
- [ * ] All new and existing tests passed.
- [ * ] All commits are signed-off.
> Document AWS SM

- .github/workflows/single-binary.yml
> Pin flytekit to 1.15.0 to unblock functional tests

- flyteplugins/go/tasks/plugins/array/awsbatch/jobs_store.go
- flytepropeller/manager/shardstrategy/hash.go
- flytepropeller/pkg/compiler/transformers/k8s/utils.go
- flytepropeller/pkg/compiler/transformers/k8s/workflow.go
Use the built-in max/min from the standard library in Go 1.21 to simplify the code.
This PR refactors code to use Go 1.21's built-in min/max functions, removing custom implementations like minInt, intMin, and intMax. The changes span task plugins, shard strategies, and Kubernetes utilities, enhancing maintainability while preserving functionality.
<br>
<br> …
> refactor: use the built-in max/min to simplify the code

- RELEASE.md
As title, it bothered me, David, Kevin, and Yee how to release Flyte.
> [Docs] How to release Flyte

- .github/workflows/tests.yml
NA
docs are now built elsewhere
> ci: Remove docs job from GitHub actions workflow

- .github/workflows/stale.yml
The changes here are designed as a first step to process the current backlog in this repo with the following criteria:
- Close bug reports that haven't received an update for 90 days or more. 7 day grace period. Any update, including comments reset the counter
- Close PRs that have been inactive for 9 months or more. 14-day grace period.
- Close feature request inactive for 9 months or more. 14-day grace period
Yet to be tested
This is important to improve the …
> Update "stale" GH Action

- cmd/single/console.go
Optimize code using a more modern writing style. Official support from Go, for more details visit https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize.
This pull request refactors the console.go file to improve readability and efficiency by replacing HasPrefix and TrimPrefix with the CutPrefix method, in line with Go's modernization …
> refactor: replace HasPrefix+TrimPrefix with CutPrefix

- .github/workflows/stale.yml
Prevent PRs waiting for review are closed. Also looks to fix the PR close warning message not being displayed
> Fix PR stale comment

- .github/workflows/create_release.yml
- script/release.sh
NA
CI is failing. https://github.com/flyteorg/flyte/actions/runs/15453276462/job/43500182447
update file path
This pull request updates file paths in the release workflows to address issues in the continuous integration (CI) process, ensuring the CI does not fail and maintaining the integrity of the deployment process. …
> ci(update paths): Correct file paths in release workflows

- flytectl/pkg/k8s/k8s.go
- flyteplugins/go/tasks/plugins/array/k8s/subtask_exec_context.go
fix inconsistent function name in comment
This pull request improves code clarity by correcting inconsistencies in function names within comments across multiple files. The documentation enhancements ensure that comments accurately reflect the corresponding functions, aiding maintainability. No functional changes were …
> chore: fix inconsistent function name in comment

- .github/workflows/publish-python.yml
- .github/workflows/publish-rust.yml
- gen/rust/Cargo.lock
> python version fix and use OIDC to authenticate crates

- flyteidl/go.mod
We recently were trying to get flyteidl imported into a bezel project and found these confusing replace directives.
This pull request cleans up the `go.mod` file in the `flyteidl` directory by removing unused replace directives, enhancing clarity and maintainability of dependency management.
</div>
> Remove unused replace directives in flyteidl
